import {MethodVisual,methodVisualKinds,methodReadout} from './MethodVisual'
import {useId,useState} from 'react'
import {ArrowUpRight,ChevronLeft,ChevronRight,Layers3,Target} from 'lucide-react'
import type {AnalysisOutput,Figure} from './analysisEngine'
import {presentationProfiles} from './presentationProfiles'
import {AnalysisFigure} from './AnalysisFigure'

const colors=['#a7d5dd','#e2c59b','#9db3d6','#adcec1','#c4b6ce']
const seq=(n:number)=>Array.from({length:n},(_,i)=>i)
const finite=(a:number[])=>a.filter(Number.isFinite)
const path=(values:number[],x:number,y:number,w:number,h:number,lo?:number,hi?:number)=>{
 const list=finite(values),min=lo??Math.min(0,...list),max=hi??Math.max(1e-9,...list);let pen=false
 return values.map((v,i)=>{if(!Number.isFinite(v)){pen=false;return ''}const d=`${pen?'L':'M'}${(x+i/Math.max(1,values.length-1)*w).toFixed(2)},${(y+h-(v-min)/Math.max(1e-8,max-min)*h).toFixed(2)}`;pen=true;return d}).join(' ')
}
const iso=(x:number,z:number,y=0)=>[400+x*.95-z*.65,255+x*.25+z*.4-y]
const poly=(points:number[][])=>points.map(([x,z,y])=>iso(x,z,y).join(',')).join(' ')
const targetKey=(e:React.KeyboardEvent,run:()=>void)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();run()}}
export function presentationReadout(output:AnalysisOutput,position:number,figureIndex=0){
 position=Math.max(0,Math.min(100,position));const f=output.figures[figureIndex]||output.figures[0]
 if(f?.matrix){const i=Math.round(position/100*(f.matrix[0].length-1)),column=f.matrix.map(row=>row[i]),peak=Math.max(...finite(column));return {label:f.x,value:f.range?(f.range[0]+i/Math.max(1,f.matrix[0].length-1)*(f.range[1]-f.range[0])).toFixed(2):String(i+1),detail:`峰值 ${peak.toFixed(3)}`}}
 if(f?.lines){const a=f.lines.at(-1)!,i=Math.round(position/100*(a.length-1));return {label:f.y,value:Number.isFinite(a[i])?a[i].toFixed(3):'—',detail:f.range?`${(f.range[0]+position/100*(f.range[1]-f.range[0])).toFixed(2)} · ${f.x}`:`样本 ${i+1}`}}
 if(f?.points?.length){const i=Math.round(position/100*(f.points.length-1)),p=f.points[i];return {label:`事件 ${i+1}`,value:p[0].toFixed(2),detail:`${f.x} · ${f.y} ${p[1].toFixed(2)}`}}
 return {label:'结构',value:'构型',detail:''}
}

/** A semantic first view for every method. Numeric panels read the same frozen output as exports. */
export function AlgorithmPresentation({output,onProfessional,onCursor}:{output:AnalysisOutput;onProfessional:(i:number)=>void;onCursor:(n:number)=>void}){
 const spec=presentationProfiles[output.id],key=useId().replace(/[^a-zA-Z0-9]/g,''),[position,setPosition]=useState(45),[selected,setSelected]=useState(0),[view,setView]=useState(0),[detail,setDetail]=useState(false)
 const move=(n:number)=>{n=Math.max(0,Math.min(100,n));setPosition(n);onCursor(n/100)}
 const figures=output.figures,lines=figures.find(f=>f.kind==='wave')?.lines||figures.find(f=>f.lines)?.lines||[],matrix=figures.find(f=>f.matrix)?.matrix||[],scatter=figures.find(f=>f.points)?.points||[]
 let readout=presentationReadout(output,position,detail?view:0)
 const selectNode=(i:number)=>{setSelected(i);if(['shot-gather','maps'].includes(output.id))move(i/Math.max(1,lines.length-1)*100);else if(spec.kind==='events')move(i/Math.max(1,scatter.length-1)*100)}
 if(!detail&&['shot-gather','maps'].includes(output.id)&&lines[selected])readout={label:`通道 ${selected+1}`,value:Math.max(...lines[selected].map(Math.abs)).toFixed(3),detail:'当前记录 · 峰值振幅'}
 if(!detail&&output.id==='beamforming'){const a=figures[2].lines?.[0]||[],i=Math.round(position/100*Math.max(0,a.length-1));readout={label:'观察方位',value:`${Math.round(i/Math.max(1,a.length-1)*360)}°`,detail:`波束功率 ${(a[i]??0).toFixed(3)}`}}
 if(!detail&&['mechanism','fracture','risk'].includes(spec.kind))readout={label:spec.kind==='fracture'?'裂缝面':spec.kind==='risk'?'证据来源':'观察方位',value:spec.kind==='mechanism'?`${Math.round(position*3.6)}°`:spec.kind==='risk'?['位移','微震','降雨'][selected%3]:String(selected+1).padStart(2,'0'),detail:''}
 if(!detail)readout=methodReadout(output,position,selected)||readout
 const glass=`url(#${key}glass)`,glow=`url(#${key}glow)`,warm=`url(#${key}warm)`
 const node=(i:number,label:string,children:React.ReactNode)=><g key={i} role="button" tabIndex={0} aria-label={label} onClick={()=>selectNode(i)} onKeyDown={e=>targetKey(e,()=>selectNode(i))} className={selected===i?'domain-node is-selected':'domain-node'}>{children}</g>
 const waveform=(a:number[],i:number)=>{const baseline=100+(i%8)*43;return <g key={i}><path d={`M86 ${baseline}H705`} stroke="#c5e2eb" strokeOpacity=".08"/><path d={path(a,100,baseline-17,570,34,-Math.max(.0001,...a.map(Math.abs)),Math.max(.0001,...a.map(Math.abs)))} fill="none" stroke={selected===i?'#edd5ab':colors[i%3]} opacity={selected===i?1:.48} strokeWidth={selected===i?2:1}/>{node(i,`选择通道 ${i+1}`,<><circle cx="70" cy={baseline} r="12" fill={glass} stroke={selected===i?'#edd5ab':'#7eafc6'} strokeOpacity=".5"/><text x="70" y={baseline+4} textAnchor="middle">{i+1}</text></>)}</g>}
 const renderMain=()=>{
 if(methodVisualKinds[output.id])return <MethodVisual output={output} position={position} selected={selected} onSelect={selectNode} glass={glass}/>
 if(spec.kind==='wave')return <>
  {output.id==='shot-gather'&&<><path d="M84 67L708 67" stroke="#adcedb" strokeOpacity=".4"/>{seq(Math.min(12,lines.length)).map(i=><g key={i}><path d={`M${100+i*51} 67v-18`} stroke="#9abeca"/><ellipse cx={100+i*51} cy="47" rx="6" ry="3" fill={glass} stroke="#adcfdb"/></g>)}</>}
  {lines.slice(Math.floor(selected/8)*8,Math.floor(selected/8)*8+8).map((a,i)=>waveform(a,i+Math.floor(selected/8)*8))}
  {['event-detection','ps-pick'].includes(output.id)&&<><rect x={100+position*5.7-20} y="78" width="40" height={Math.min(8,lines.length)*43} rx="10" fill="#e4bd7c" fillOpacity=".08" stroke="#ddc89b" strokeOpacity=".6"/><text x={100+position*5.7} y="62" textAnchor="middle">{output.id==='ps-pick'?'候选到时':'选中窗口'}</text></>}
  {output.id==='maps'&&<><path d="M385 74V423" stroke="#e1d2ae" strokeDasharray="3 8" strokeOpacity=".5"/><text x="370" y="451">零时延</text><text x="100" y="451">负时延</text><text x="640" y="451">正时延</text></>}
 </>
 if(spec.kind==='energy'){
  const m=view===1&&output.id==='hrlrt'?figures[1].matrix||matrix:matrix,flat=finite(m.flat()),lo=Math.min(...flat),hi=Math.max(...flat),rows=m.length,cols=m[0]?.length||0
  return <><polygon points={poly([[-230,-125,-35],[230,-125,-35],[230,125,-35],[-230,125,-35]])} fill={glass} stroke="#c3dee5" strokeOpacity=".17"/>{seq(Math.min(35,cols)).map((_,j)=>{const col=Math.round(j/34*(cols-1));if(!m[0]||col<0)return null;return <path key={j} d={seq(rows).map((r,i)=>{const height=(m[r][col]-lo)/Math.max(1e-9,hi-lo)*150,[x,y]=iso(-220+j/34*440,-120+r/Math.max(1,rows-1)*240,height-25);return (i?'L':'M')+x+','+y}).join(' ')} stroke={Math.abs(j-position*.34)<1?'#ead3aa':'#98cad5'} strokeOpacity={Math.abs(j-position*.34)<1?1:.38+j*.012} strokeWidth={Math.abs(j-position*.34)<1?2.6:1.1} fill="none"/>})}<text x="140" y="443">{figures[0].x}</text><text x="573" y="387">{figures[0].y}</text>{output.id==='hrlrt'&&<text x="340" y="55">{view===1?'常规对照成果':'高分辨率成果'}</text>}{output.id==='dispersion-pick'&&figures[1].lines?.[0]&&<path d={path(figures[1].lines[0],120,70,550,90,figures[1].range?.[2],figures[1].range?.[3])} stroke="#efd4a2" strokeWidth="2" fill="none" strokeDasharray="4 4"/>}</>
 }
 if(spec.kind==='layers'){
  const f=figures.find(f=>f.matrix)||figures.find(f=>f.kind==='profile'&&f.lines),a=f?.matrix?f.matrix.map(row=>row[Math.round(position/100*(row.length-1))]):f?.lines?.[Math.round(position/100*(f.lines.length-1))]||[]
  const layerValues=seq(6).map(i=>a[Math.min(a.length-1,Math.round(i/5*(a.length-1)))]||0),lo=Math.min(...layerValues),hi=Math.max(...layerValues)
  return <>{seq(6).map(i=>{const top=110-i*35,v=layerValues[i],shade=(v-lo)/Math.max(1,hi-lo);return node(i,`查看层段 ${i+1}`,<><polygon points={poly([[-210,-85,top],[210,-85,top],[210,85,top],[-210,85,top]])} fill={glass} stroke={selected===i?'#e6c89c':'#9abfca'} strokeOpacity={selected===i?1:.45}/><polygon points={poly([[-210,85,top],[210,85,top],[210,85,top-20],[-210,85,top-20]])} fill={colors[i%5]} fillOpacity={.15+shade*.22} stroke="#c1d8df" strokeOpacity=".12"/><path d={seq(45).map((_,j)=>{const x=-200+j*9,variation=f?.matrix?(f.matrix[Math.min(f.matrix.length-1,i*5)][Math.round(j/44*(f.matrix[0].length-1))]-lo)/Math.max(1,hi-lo)*10:0;return (j?'L':'M')+iso(x,80,top+variation+2).join(',')}).join(' ')} stroke="#c8dde3" strokeWidth=".8" fill="none" opacity=".5"/></>)})}<path d={'M'+iso(-210+position*4.2,-85,125).join(',')+'L'+iso(-210+position*4.2,85,-85).join(',')} stroke="#e8c796" strokeWidth="2.5"/><text x="90" y="437">{f?.matrix?'测线切片':'候选层状结构'}</text><text x="555" y="100">层段 {selected+1}</text>{layerValues[selected]!=null&&<text x="555" y="121">{layerValues[selected].toFixed(1)} {f?.matrix?'剖面值':'m/s'}</text>}</>
 }
 if(spec.kind==='array'){
  const beam=output.id==='beamforming',hv=output.id==='hvsr',power=beam?(figures[2].lines?.[0]||[]):hv?(figures[0].lines?.at(-1)||[]):[],max=Math.max(.0001,...power),angle=position/100*Math.PI*2
  return <>{[65,112,168].map((r,i)=><ellipse key={r} cx="365" cy="242" rx={r*1.4} ry={r*.63} fill={i===2?glass:'none'} stroke="#98bccd" strokeOpacity=".3"/>)}{seq(12).map(i=>{const a=i/12*Math.PI*2,x=365+Math.cos(a)*235,y=242+Math.sin(a)*106;return node(i,`选择台站 ${i+1}`,<><path d={`M${x} ${y}L365 242`} stroke="#91c4d2" strokeOpacity={selected===i?.8:.15}/><path d={`M${x} ${y}v-23`} stroke="#b4d3dd" strokeWidth="2"/><ellipse cx={x} cy={y-25} rx="7" ry="4" fill={glass} stroke={selected===i?'#e7cc9e':'#afd7df'}/></>)})}{beam?<><path d={power.map((v,i)=>{const a=i/Math.max(1,power.length-1)*Math.PI*2,r=150*v/max;return (i?'L':'M')+(365+Math.cos(a)*r*1.4)+','+(242+Math.sin(a)*r*.63)}).join(' ')+'Z'} fill="#a7d5d7" fillOpacity=".24" stroke="#c7e2df" strokeWidth="2"/><path d={`M365 242L${365+Math.cos(angle)*240} ${242+Math.sin(angle)*108}`} stroke="#e4c79b" strokeWidth="2"/><text x="590" y="80">{Math.round(position*3.6)}°</text></>:hv?<><path d={path(power,190,55,355,170,0,max)} fill="none" stroke="#dfd4ad" strokeWidth="2.6"/><path d={`M${190+position*3.55} 45V243`} stroke="#cce6e7" strokeOpacity=".55" strokeDasharray="3 6"/><text x="307" y="38">H / V</text></>:<>{seq(4).map(i=><ellipse key={i} cx="365" cy={242-i*29} rx={140-i*26+position*.25} ry={43-i*7} fill="none" stroke={i===selected%4?'#e3c69b':'#a3ccd7'} strokeOpacity={.6-i*.1}/>)}<path d="M365 232V93" stroke="#d0e2e4" strokeOpacity=".5"/><circle cx="365" cy="92" r="6" fill="#e0c99f"/></>}<text x="104" y="415">{beam?'方位—慢度波束':hv?'三分量与共振响应':output.id==='array-design'?'台站几何示意':'径向观测阵列'}</text></>
 }
 if(spec.kind==='events'){
  const points=scatter.length?scatter:seq(48).map(i=>[50+Math.sin(i*1.7)*30,50+Math.cos(i*.91)*25,i%3]),count=output.id==='event-attributes'?Math.max(1,Math.round(position/100*points.length)):points.length
  return <>{seq(3).map(i=><polygon key={i} points={poly([[-205,-100,65-i*58],[205,-100,65-i*58],[205,100,65-i*58],[-205,100,65-i*58]])} fill={glass} stroke="#a5c8d5" strokeOpacity=".25"/>)}{points.slice(0,count).map(([x,y,g],i)=>{const p=iso((x-50)*5,(y-50)*3,25-g*25);return node(i,`选择事件 ${i+1}`,<><circle cx={p[0]} cy={p[1]} r={selected===i?18:output.id==='magnitude-energy'?4+Math.max(0,g)*3:3.5} fill={selected===i?warm:colors[g%3]} opacity={selected===i?.65:.7}/><circle cx={p[0]} cy={p[1]} r={selected===i?6:2} fill={selected===i?'#e6c89d':'#d5e9ee'}/></>)})}<text x="104" y="420">{output.id==='magnitude-energy'?'事件属性':'事件分布'}</text><text x="570" y="76">{count} 个事件</text></>
 }
 if(spec.kind==='mechanism')return <g transform={`translate(390 232) rotate(${position*3.6})`}><circle r="145" fill={glass} stroke="#c8dfe5" strokeOpacity=".45"/><ellipse rx="64" ry="145" transform="rotate(35)" fill="#add3db" fillOpacity=".12" stroke="#adcedb"/><ellipse rx="145" ry="43" transform="rotate(-28)" fill="none" stroke="#e0c99f" strokeWidth="2"/>{output.id==='moment-tensor'?<><path d="M0 -145C115 -108 -115 108 0 145A145 145 0 0 0 0 -145" fill="#9dc9d7" fillOpacity=".42"/>{seq(16).map(i=>{const a=i*Math.PI/8;return node(i,`查看极性点 ${i+1}`,<circle cx={Math.cos(a)*120} cy={Math.sin(a)*120} r="5" fill={i%2?'#dbc6a2':'#294c61'} stroke="#b9d7de"/>)})}</>:seq(3).map(i=>{const a=i*Math.PI*2/3;return <g key={i} transform={`rotate(${a*180/Math.PI})`}><path d="M0 -192V-65m-8-15 8 15 8-15" stroke={colors[i]} strokeWidth="3" fill="none"/><text x="13" y="-170">σ{i+1}</text></g>})}</g>
 if(spec.kind==='fracture')return <><polygon points={poly([[-220,-100,-80],[220,-100,-80],[220,100,-80],[-220,100,-80]])} fill={glass} stroke="#a9ced5" strokeOpacity=".2"/>{seq(15).map(i=>{const x=-170+i%5*75,z=-60+Math.floor(i/5)*57,y=70-(i%3)*20;return node(i,`选择裂缝面 ${i+1}`,<polygon points={poly([[x,z,y],[x+45,z-14,y+28],[x+58,z+30,y-75],[x+5,z+35,y-100]])} fill={selected===i?warm:glass} stroke={selected===i?'#eed4aa':colors[i%3]} strokeOpacity=".65"/> )})}{output.id==='permeability'&&<><ellipse cx="393" cy="238" rx="267" ry="164" fill="none" stroke="#a7d6da" strokeOpacity=".36" strokeDasharray="3 7"/><path className="domain-flow-path" d="M210 115C350 170 250 310 405 301S441 196 600 345" stroke="#e3ca9c" strokeWidth="3" strokeDasharray="6 12" fill="none"/></>}<path d={`M${155+position*4.6} 86V418`} stroke="#cbe8e8" strokeDasharray="3 7" strokeOpacity=".5"/><text x="125" y="450">{output.id==='permeability'?'连通路径示意':'裂缝网络'}</text></>
 if(spec.kind==='forecast'){
  const f=figures[0],a=f.lines||[],observed=a[0]||[],last=observed.reduce((last,v,i)=>Number.isFinite(v)?i:last,-1),max=f.range?.[3]||Math.max(...finite(a.flat())),split=100+last/Math.max(1,observed.length-1)*590,band=(a[2]||[]).map((v,i)=>Number.isFinite(v)&&Number.isFinite(a[3]?.[i])?{x:100+i/Math.max(1,observed.length-1)*590,upper:365-v/max*285,lower:365-a[3][i]/max*285}:null).filter(v=>v!==null)
  return <><rect x={split} y="80" width={Math.max(0,690-split)} height="286" fill={glass} rx="14"/><path d={`M${split} 70V370`} stroke="#cddce5" strokeDasharray="4 7" strokeOpacity=".5"/>{[0,1,2,3].map(i=><path key={i} d={`M100 ${90+i*87}H700`} stroke="#b4d2df" strokeOpacity=".1"/>)}{band.length>1&&<polygon points={[...band.map(p=>p.x+','+p.upper),...band.slice().reverse().map(p=>p.x+','+p.lower)].join(' ')} fill="#b5d8d81b"/>}{a.map((v,i)=><path key={i} d={path(v,100,80,590,285,0,max)} fill="none" stroke={i===0?'#a4d8df':i===1?'#e6c79a':'#c8d9d8'} strokeWidth={i<2?2.5:1} strokeOpacity={i<2?1:.38} strokeDasharray={i?'5 6':undefined}/>)}<path d={`M${100+position*5.9} 70V375`} stroke="#e6c99f" strokeOpacity=".7"/><text x="100" y="413">历史观测</text><text x={split+12} y="413">线性外推</text><text x="640" y="54">mm</text></>
 }
 return <><polygon points={poly([[-200,-105,-25],[200,-105,-25],[200,105,-25],[-200,105,-25]])} fill={glass} stroke="#b1d3dc" strokeOpacity=".4"/>{[[-190,-80], [170,-100], [-170,110]].map(([x,z],i)=>{const p=iso(x,z,80),centre=iso(10,0,0);return node(i,`查看${['位移','微震','降雨'][i]}证据`,<><path className="domain-flow-path" d={`M${p}L${centre}`} stroke={colors[i]} strokeDasharray="4 8" strokeWidth={selected===i?2.5:1} opacity=".7"/><circle cx={p[0]} cy={p[1]} r="31" fill={glass} stroke={colors[i]} strokeOpacity=".6"/><text x={p[0]} y={p[1]+5} textAnchor="middle">{['位移','微震','降雨'][i]}</text></>)})}<ellipse cx="410" cy="257" rx="75" ry="40" fill={warm} stroke="#e3c292" strokeOpacity=".5"/><ellipse cx="410" cy="257" rx="45" ry="22" fill="none" stroke="#e3c292"/><path d="M410 238v22m0 8v2" stroke="#f4dcb8" strokeWidth="3"/></>
 }
 return <div className="algorithm-experience domain-presentation" data-experience={output.id}><div className="experience-layout"><section className="experience-stage domain-stage"><header className="experience-stage-heading"><span>{spec.title}</span><button aria-label="展开专业图面" onClick={()=>onProfessional(view)}><ArrowUpRight size={15}/></button></header>{detail?<div className="domain-detail-figure"><AnalysisFigure figure={figures[view]} cursor={position/100} onCursor={n=>move(n*100)} selected={selected} onSelect={setSelected}/></div>:<svg className="domain-main-svg" viewBox="0 0 800 490" role="group" aria-label={spec.title}><defs><linearGradient id={key+'glass'} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#c3e5ed" stopOpacity=".26"/><stop offset=".55" stopColor="#8bb9d1" stopOpacity=".06"/><stop offset="1" stopColor="#aaceda" stopOpacity=".22"/></linearGradient><radialGradient id={key+'glow'}><stop stopColor="#98ccda" stopOpacity=".2"/><stop offset="1" stopColor="#98ccda" stopOpacity="0"/></radialGradient><radialGradient id={key+'warm'}><stop stopColor="#edd1a2" stopOpacity=".5"/><stop offset="1" stopColor="#ddbe8a" stopOpacity=".1"/></radialGradient></defs><ellipse cx="400" cy="296" rx="315" ry="170" fill={glow}/>{renderMain()}</svg>}<div className="domain-stage-tools"><button aria-pressed={!detail} onClick={()=>setDetail(false)}><Layers3 size={14}/>成果视景</button><button aria-pressed={detail} onClick={()=>setDetail(true)}><Target size={14}/>数据图面</button><label>{spec.control}<input aria-label={spec.control} type="range" min="0" max="100" step="1" value={position} onChange={e=>{move(+e.target.value);if(['shot-gather','maps'].includes(output.id))setSelected(Math.round(+e.target.value/100*Math.max(0,lines.length-1)))}}/></label></div></section><aside className="experience-rail"><div className="experience-panel domain-readout"><span>{readout.label}</span><strong>{readout.value}</strong><small>{readout.detail}</small></div><div className="domain-view-options">{spec.views.map((title,i)=><button key={title} aria-pressed={view===i} onClick={()=>{setView(i);if(!(output.id==='hrlrt'&&i<2))setDetail(i!==0)}}><span>0{i+1}</span>{title}<ArrowUpRight size={14}/></button>)}</div>{output.mode==='computed'&&<div className="experience-panel domain-metrics">{output.metrics.slice(0,2).map(m=><div key={m.label}><small>{m.label}</small><strong>{m.value}<em>{m.unit}</em></strong></div>)}</div>}</aside></div></div>
}
