import { useState } from 'react'
import { specFor } from './algorithms'
import { SciencePlot } from './AlgorithmStudio'
import { InstrumentPlot } from './InstrumentPlot'
export function AlgorithmEvidence({id,scale,excluded}:{id:string;scale:number;excluded:string[]}){
 const spec=specFor(id),[view,setView]=useState('过程诊断'),[sample,setSample]=useState(1),[layer,setLayer]=useState(2)
 const micro=['events','wave','mechanism','stress'].includes(spec.plot),profile=['profile','model'].includes(spec.plot)
 const chain=spec.steps.map((label,i)=>({label,value:Math.max(.002,.22*Math.exp(-i*.9)/(Math.max(.3,scale)))}))
 return <div className="algorithm-evidence"><div className="diagnostic-toolbar"><span>专业辅助视图 / 参数联动样例</span><select aria-label="诊断样例" value={sample} onChange={e=>setSample(+e.target.value)}>{[1,2,3].map(s=><option key={s} value={s}>对照批次 {s}</option>)}</select><button onClick={()=>setView(v=>v==='过程诊断'?'空间解释':'过程诊断')}>{view==='过程诊断'?'切换空间解释':'切换过程诊断'}</button></div>
 <div className="diagnostic-grid"><article><h3>{micro?'输入通道与到时质检':profile?'约束输入与初始模型':'输入炮集 / 频率窗口'}</h3><p>样例批次 {sample} · 已排除 {excluded.length} 个通道</p>{micro?<InstrumentPlot family="micro" frame={sample*20+scale*10}/>:<SciencePlot id={profile?'surface-inversion':'shot-gather'} scale={scale+sample*.2}/>}</article><article><h3>{view==='空间解释'?'空间响应与人工解释':'处理步骤与收敛路径'}</h3><p>{view==='空间解释'?'点击剖面分层查看解释位置':'中间结果可视化，不代表数值求解精度'}</p><svg viewBox="0 0 500 245" role="img" aria-label={view==='空间解释'?'地质剖面辅助解释':'算法收敛路径示意'}>
 <rect width="500" height="245" fill="#f2f7fb"/>{view==='空间解释'?<>{Array.from({length:6},(_,i)=><g key={i} className="interpretation-layer" role="button" aria-label={`选择解释层${i+1}`} tabIndex={0} onClick={()=>setLayer(i)} onKeyDown={e=>e.key==='Enter'&&setLayer(i)}><path d={`M30 ${35+i*30} Q170 ${8+i*31+sample*5} 265 ${44+i*26} T475 ${31+i*31} V${62+i*31} Q360 ${75+i*29} 265 ${68+i*26} T30 ${65+i*30}Z`} fill={['#ccddd8','#aecad2','#8fb0c5','#7398b7','#557d9d','#386581'][i]} stroke={layer===i?'#cf9652':'#ffffff'} strokeWidth={layer===i?3:1}/><text x="37" y={53+i*30} fontSize="11" fill={i>3?'#deebf2':'#53748c'}>L{i+1}</text></g>)}<path d={`M${235+sample*10} 22L${250+scale*8} 221`} stroke="#ca985e" strokeWidth="2" strokeDasharray="4 4"/><text x="320" y="228" fill="#8e6a3d" fontSize="11">当前解释层 L{layer+1}</text></>:<>{[1,2,3,4].map(i=><path key={i} d={`M45 ${i*45}H475`} stroke="#dbe6ef"/>)}<path d={Array.from({length:80},(_,i)=>`${i?'L':'M'}${45+i*5.3},${205-165*Math.exp(-i/(12+scale*5+sample))}`).join(' ')} stroke="#346f9e" strokeWidth="2.5" fill="none"/>{chain.map((s,i)=><g key={s.label}><circle cx={60+i*125} cy={i?172+i*8:58} r="5" fill="#437fa6"/><text x={50+i*120} y="230" fontSize="10" fill="#7692a8">{s.label}</text></g>)}<text x="45" y="20" fontSize="10" fill="#7891a4">归一化残差 / 迭代样例</text></>}</svg></article></div><div className="algorithm-checkpoints">{chain.map((s,i)=><article key={s.label}><small>中间产物 0{i+1}</small><h4>{s.label}</h4><p>{[spec.input,'质量控制与有效窗口','参数响应及中间结果',spec.output][i]}</p><span>{i===1&&excluded.length?'剔除通道已生效':'可复核 / 可追溯'}</span></article>)}</div></div>
}
