import {useEffect,useId,useRef,useState} from 'react'
import {Download,Home,Minus,Plus,Grid2X2} from 'lucide-react'
import {useWorkspaceAppearance} from './ScientificUI'
import {exportFile} from './store'
import type {Figure} from './analysisEngine'
import {AnalysisVolume} from './AnalysisVolume'
import {DispersionSurface} from './DispersionSurface'
const colors=['#72cad0','#e7b374','#8eaee8','#b7ce87','#c1a0d3','#8da9b5']
const ramp=(v:number)=>{const a=Math.max(0,Math.min(1,v)),stops=[[17,37,50],[49,80,101],[104,152,171],[176,208,208],[232,211,173]];const p=a*4,i=Math.min(3,Math.floor(p)),f=p-i;return `rgb(${stops[i].map((c,j)=>Math.round(c*(1-f)+stops[i+1][j]*f)).join(',')})`}
interface AnalysisFigureProps {figure:Figure;compact?:boolean;cursor?:number;onCursor?:(n:number)=>void;onPick?:(n:number)=>void;slice?:number;selected?:number;onSelect?:(n:number)=>void;compare?:boolean;exporting?:boolean;annotations?:number[];responsive?:boolean}
export function AnalysisFigure(props:AnalysisFigureProps){
 const scientific=useWorkspaceAppearance()==='scientific'
 const [surface,setSurface]=useState(!scientific)
 const spatial=props.figure.title==='相位叠加频散能量'&&!props.compact&&!props.exporting
 return spatial?<div className="figure-viewport surface-workspace"><div className="surface-view-switch"><button aria-pressed={surface} onClick={()=>setSurface(true)}>三维能量面</button><button aria-pressed={!surface} onClick={()=>setSurface(false)}>二维图面</button></div>{surface?<DispersionSurface figure={props.figure} onCursor={props.onCursor}/>:<FigureBody {...props}/>}</div>:<FigureBody {...props}/>
}
function FigureBody({figure,compact=false,cursor=-1,onCursor,onPick,slice=100,selected=0,onSelect,compare=false,exporting=false,annotations=[],responsive=false}:AnalysisFigureProps){
 const scientific=useWorkspaceAppearance()==='scientific',colors=scientific?['#1767ad','#bd6328','#7357b0','#258673','#bc4977','#5c7386']:['#72cad0','#e7b374','#8eaee8','#b7ce87','#c1a0d3','#8da9b5']
 const [grid,setGrid]=useState(true),[offset,setOffset]=useState(0),[zoom,setZoom]=useState(1),[hover,setHover]=useState<{x:number;y:number}|null>(null),[localPick,setLocalPick]=useState(-1);const clip=useId().replace(/:/g,''),ref=useRef<SVGSVGElement>(null),[size,setSize]=useState({w:760,h:360}),f=exporting?figure:{...figure,title:figure.title.replaceAll('参考成果','成果'),x:figure.x.replaceAll('参考',''),y:figure.y.replaceAll('参考','')},fluid=responsive&&!compact&&!exporting&&['heat','wave','lines','profile','scatter'].includes(f.kind),w=fluid?size.w:760,h=fluid?size.h:360,left=fluid?72:58,top=28,pw=w-left-(fluid?54:52),ph=h-top-(fluid?45:50)
 useEffect(()=>{const el=ref.current;if(!fluid||!el)return;const observer=new ResizeObserver(([entry])=>{const w=Math.max(300,Math.round(entry.contentRect.width)),h=Math.max(150,Math.round(entry.contentRect.height));setSize(v=>v.w===w&&v.h===h?v:{w,h})});observer.observe(el);return()=>observer.disconnect()},[fluid,f.kind])
 const isVolume=f.kind==='geometry'&&!['array','pairs','circle','survey','bins'].includes(f.variant||'')
 if(isVolume&&!compact)return <div className="figure-viewport spatial"><AnalysisVolume variant={f.variant} slice={slice} selected={selected} onSelect={onSelect}/></div>
 const matrix=f.matrix||[],flat=matrix.flat().filter(Number.isFinite),lo=flat.length?Math.min(...flat):0,hi=flat.length?Math.max(...flat):1
 const values=(f.lines||[]).flat().filter(Number.isFinite),min=f.range?.[2]??(f.kind==='profile'?0:values.length?Math.min(...values):0),max=f.range?.[3]??(f.kind==='profile'?160:f.kind==='scatter'?100:values.length?Math.max(...values):1),xmin=f.range?.[0]??(f.kind==='profile'?180:0),xmax=f.range?.[1]??(f.kind==='profile'?830:f.kind==='scatter'?100:Math.max(1,...(f.lines||[]).map(a=>a.length-1)))
 const sx=(n:number)=>left+n*pw,sy=(n:number)=>top+ph-n*ph,path=(a:number[],index=0)=>{let drawing=false;return a.map((v,i)=>{if(!Number.isFinite(v)){drawing=false;return ''}const x=sx(i/Math.max(1,a.length-1)),y=f.kind==='wave'?top+18+index*(ph-20)/Math.max(1,f.lines!.length-1)-v*12:sy((v-min)/Math.max(1e-8,max-min));const d=`${drawing?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`;drawing=true;return d}).join(' ')}
 const point=(e:React.MouseEvent<SVGSVGElement>)=>{const matrix=e.currentTarget.getScreenCTM(),box=e.currentTarget.getBoundingClientRect(),point=matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):{x:(e.clientX-box.left)/box.width*w,y:(e.clientY-box.top)/box.height*h},x=point.x,y=point.y;return {x:Math.max(0,Math.min(1,offset+(x-left)/pw/zoom)),y:Math.max(0,Math.min(1,(top+ph-y)/ph))}}
 const select=(n:number)=>{setLocalPick(n);onSelect?.(n)}
 const circular=f.kind==='polar'||f.kind==='mechanism'||f.kind==='stereo'
 return <div className={`figure-viewport ${compact?'compact':''}`}><svg ref={ref} viewBox={compact&&!exporting?isVolume?'100 10 550 340':circular?'218 10 324 324':`${left} ${top} ${pw} ${ph}`:`0 0 ${w} ${h}`} preserveAspectRatio={compact&&!exporting&&!circular&&!isVolume?'none':'xMidYMid meet'} role="img" aria-label={f.title} onPointerMove={compact?undefined:e=>{const p=point(e);setHover(p);onCursor?.(p.x)}} onPointerLeave={()=>setHover(null)} onClick={compact?undefined:e=>{const p=point(e);setLocalPick(p.x);onCursor?.(p.x);onPick?.(p.x)}}>
 <defs><clipPath id={clip}><rect x={left} y={top} width={pw} height={ph}/></clipPath><linearGradient id={clip+'r'}>{[0,.25,.5,.75,1].map(v=><stop key={v} offset={`${v*100}%`} stopColor={ramp(v)}/>)}</linearGradient></defs><rect width={w} height={h} fill={scientific?'#fff':'transparent'}/>
 {(!compact||exporting)&&!circular&&!isVolume&&<g className="figure-axes" fill={scientific?'#536776':'#8baabc'} fontSize="10">{Array.from({length:6},(_,i)=><g key={i}><path d={`M${sx(i/5)} ${top}V${top+ph}M${left} ${sy(i/5)}H${left+pw}`} stroke={scientific?'#dce4eb':'#294455'} opacity={grid?1:0} strokeWidth=".7" strokeDasharray="3 5"/><text x={sx(i/5)} y={top+ph+19} textAnchor="middle">{(xmin+(xmax-xmin)*(offset+i/5/zoom)).toFixed(xmax<5?2:0)}</text><text x={left-10} y={sy(i/5)+4} textAnchor="end">{f.kind==='wave'?Math.round((1-i/5)*(f.lines?.length||24)):f.kind==='heat'||f.matrix?(f.range?f.range[2]+(f.range[3]-f.range[2])*(f.kind==='profile'?1-i/5:i/5):i/5).toFixed(f.range&&Math.max(Math.abs(f.range[2]),Math.abs(f.range[3]))<2?2:0):(min+(max-min)*(f.kind==='profile'?1-i/5:i/5)).toFixed(Math.abs(max)<10?2:0)}</text></g>)}<text x={left} y="16">{f.y}</text><text x={left+pw} y={h-10} textAnchor="end">{f.x}</text></g>}
 <g clipPath={circular?undefined:`url(#${clip})`}><g transform={!circular&&zoom>1?`translate(${left*(1-zoom)-offset*pw*zoom} 0) scale(${zoom} 1)`:undefined}>
 {!!matrix.length&&f.kind!=='polar'&&matrix.map((row,y)=>row.map((v,x)=>{const stride=compact&&!exporting?4:1;if(y%stride||x%stride)return null;return <rect key={`${x}-${y}`} x={left+x*pw/row.length} y={f.kind==='profile'?top+y*ph/matrix.length:top+ph-(y+stride)*ph/matrix.length} width={pw/row.length*stride+.5} height={ph/matrix.length*stride+.5} fill={ramp((v-lo)/Math.max(1e-8,hi-lo))}/>}))}
 {f.lines&&f.kind!=='profile'&&f.lines.map((a,i)=><path key={i} d={path(a,i)} fill="none" stroke={colors[i%colors.length]} opacity={f.lines!.length>6&&f.kind!=='wave'&&i<f.lines!.length-1?.35:.95} strokeWidth={compact?1.4:f.lines!.length>6?1.2:2} strokeDasharray={compare&&i===1?'5 4':undefined}/>)}
 {f.kind==='profile'&&f.lines&&f.lines.map((a,j)=><path key={j} d={a.map((v,i)=>`${i?'L':'M'}${sx((v-180)/650)},${top+i/(a.length-1)*ph}`).join(' ')} stroke={j===4?'#e6b577':'#7eafc4'} strokeWidth={j===4?2.5:1.2} opacity={j===4?1:.45} fill="none"/>)}
 {f.kind==='scatter'&&f.points?.map(([x,y,g],i)=><g key={i} onClick={compact?undefined:e=>{e.stopPropagation();select(i)}} role="button" tabIndex={compact?-1:0} aria-label={`选择事件 ${i+1}`} onKeyDown={compact?undefined:e=>e.key==='Enter'&&select(i)}><circle cx={sx(x/100)} cy={sy(y/100)} r={selected===i?7:4} fill={colors[g%3]} opacity=".85"/>{selected===i&&<ellipse cx={sx(x/100)} cy={sy(y/100)} rx="21" ry="14" fill="none" stroke="#e1ba7d"/>}</g>)}
 {f.kind==='geometry'&&(isVolume?<g>
 {['velocity','coverage','location','risk'].includes(f.variant||'')&&Array.from({length:5},(_,i)=><path key={i} d={`M140 ${110+i*24}L370 ${45+i*24}L615 ${125+i*24}L390 ${212+i*24}Z`} fill={colors[i%3]} fillOpacity=".13" stroke="#779ab1" strokeOpacity=".3"/>)}
 {['fracture','connected'].includes(f.variant||'')&&Array.from({length:13},(_,i)=>{const x=160+(i%5)*81,y=85+Math.floor(i/5)*73;return <path key={i} d={`M${x} ${y}l64 -18 30 65 -64 18Z`} fill={colors[i%3]} fillOpacity=".28" stroke={colors[i%3]} strokeOpacity=".75"/>})}
 {f.variant==='srv'&&<><ellipse cx="380" cy="182" rx="220" ry="112" fill="#76b8be" fillOpacity=".15" stroke="#81ced0"/><ellipse cx="380" cy="182" rx="220" ry="43" fill="none" stroke="#81ced0" strokeDasharray="4 4"/><ellipse cx="380" cy="182" rx="94" ry="112" fill="none" stroke="#81ced0"/></>}
 {f.variant==='stress'?['σ₁','σ₂','σ₃'].map((label,i)=><g key={label}><path d={['M370 210L370 55','M370 210L560 275','M370 210L185 275'][i]} stroke={colors[i]} strokeWidth="5"/><text x={[375,580,150][i]} y={[45,280,290][i]} fill={colors[i]} fontSize="23">{label}</text></g>):Array.from({length:34},(_,i)=><g key={i}>{f.variant==='location'&&i%5===0&&<path d={`M${150+i%6*83} 70L380 210`} stroke="#729aae" strokeOpacity=".5"/>}<circle cx={380+Math.sin(i*1.71)*175} cy={180+Math.cos(i*.84)*85} r={i%4===0?5:3} fill={colors[i%3]}/></g>)}
 <text x="60" y="340" fill="#7192a8" fontSize="11">空间索引预览 · 打开查看三维结构</text>
 </g>:<g>{(f.points||Array.from({length:12},(_,i)=>f.variant==='circle'?[Math.cos(i*Math.PI/6)*30,Math.sin(i*Math.PI/6)*30,0]:[i*5,0,0])).map(([x,y,isShot],i,a)=>{const xs=a.map(p=>p[0]),ys=a.map(p=>p[1]),xp=left+35+(x-Math.min(...xs))/Math.max(1,Math.max(...xs)-Math.min(...xs))*(pw-70),yp=170-(y-(Math.min(...ys)+Math.max(...ys))/2)/Math.max(1,Math.max(...ys)-Math.min(...ys))*210;return <g key={i} onClick={compact?undefined:e=>{e.stopPropagation();select(i)}}>{f.variant!=='array'&&<path d={`M${xp} ${yp}L380 235`} stroke="#52829b" opacity=".45"/>}<circle cx={xp} cy={yp} r={selected===i?7:4} fill={isShot===1?'#efc67c':colors[i%3]}/><text x={xp-7} y={yp+22} fontSize="9" fill={scientific?'#536c80':'#8bafc4'}>{String(i+1).padStart(2,'0')}</text></g>})}</g>)}
 {circular&&<g transform="translate(380 176)">{[35,70,105,140].map(r=><circle key={r} r={r} fill={r===140?(scientific?'#f5f8fb':'#142f43'):'none'} stroke="#426072"/>)}{Array.from({length:12},(_,i)=><g key={i} transform={`rotate(${i*30})`}><path d="M0 -140V0" stroke="#345365"/><text y="-151" textAnchor="middle" fill="#91afbf" fontSize="11">{i*30}°</text></g>)}
 {f.kind==='polar'&&matrix.map((row,r)=>row.map((v,i)=>{const a=i*2*Math.PI/row.length,b=(i+1)*2*Math.PI/row.length,r1=r/matrix.length*140,r2=(r+1)/matrix.length*140;return <path key={`${r}-${i}`} d={`M${Math.sin(a)*r1} ${-Math.cos(a)*r1}L${Math.sin(a)*r2} ${-Math.cos(a)*r2}A${r2} ${r2} 0 0 1 ${Math.sin(b)*r2} ${-Math.cos(b)*r2}L${Math.sin(b)*r1} ${-Math.cos(b)*r1}Z`} fill={ramp(v)}/>}))}
 {f.kind==='mechanism'&&<g transform={`rotate(${selected%6*12})`}><circle r="134" fill="#d8e4e7"/><path d="M0 -134A134 134 0 0 1 0 134Q-128 0 0 -134Z" fill="#35678b"/><path d="M-134 0Q0 -105 134 0Q0 96 -134 0Z" fill="#35678b"/>{Array.from({length:18},(_,i)=><circle key={i} cx={Math.sin(i*1.7)*115} cy={Math.cos(i*.91)*95} r="4" fill={i%3?'#e6b675':'white'} stroke="#1b425c"/>)}</g>}
 {f.kind==='stereo'&&<>{Array.from({length:24},(_,i)=><ellipse key={i} rx={38+i%5*8} ry="132" transform={`rotate(${i*7})`} fill="none" stroke="#779daf" opacity=".22"/>)}{[[-45,-75,f.variant==='fracture'?'P₁':'σ₁'],[80,-20,f.variant==='fracture'?'P₂':'σ₂'],[-30,95,f.variant==='fracture'?'P₃':'σ₃']].map(([x,y,t],i)=><g key={t}><circle cx={x} cy={y} r="8" fill={colors[i]}/><text x={Number(x)+14} y={y} fill={colors[i]} fontSize="16">{t}</text></g>)}</>}
 </g>}
 {f.kind==='slope'&&<g>{['#416171','#65827e','#8a9c83'].map((color,i)=><path key={i} d={`M58 ${90+i*39}H275L485 ${225+i*24}H708V310H58Z`} fill={color}/>)}<path d="M58 181Q320 151 550 282L708 288" stroke="#6ac7e8" strokeWidth="3" fill="none"/>{Array.from({length:7},(_,i)=><path key={i} d={`M${180+i*12} 90Q${250+i*20} ${280+i*3} ${500+i*14} 255`} fill="none" stroke={i===selected%7?'#f1c48a':'#b0c4c5'} strokeWidth={i===selected%7?3:1} strokeOpacity=".75"/>)}</g>}
 {f.kind==='evidence'&&<g>{['GNSS 位移','微震事件','雨量记录','数据质量'].map((s,i)=><g key={s} onClick={compact?undefined:e=>{e.stopPropagation();select(i)}}><path d={`M260 ${65+i*68}C330 ${65+i*68} 350 165 455 165`} fill="none" stroke={colors[i]} strokeWidth={i===selected%4?5:2} opacity=".6"/><rect x="78" y={43+i*68} width="180" height="44" rx="5" fill={scientific?'#edf3f9':'#1c3c50'} stroke={colors[i]}/><text x="96" y={70+i*68} fill={scientific?'#31495d':'#c7dbe6'} fontSize="14">{s}</text></g>)}<rect x="455" y="130" width="178" height="72" rx="8" fill="#785538" stroke="#d6aa6d"/><text x="485" y="173" fill="#f1d7ae" fontSize="17">风险候选 / 复核</text></g>}
 </g></g>
 {!compact&&!circular&&!isVolume&&annotations.map((value,i)=>value<offset||value>offset+1/zoom?null:<g key={i} className="figure-annotation" pointerEvents="none"><path d={`M${sx((value-offset)*zoom)} ${top}V${top+ph}`} stroke="#bf8740" strokeWidth="1" strokeDasharray="3 4"/><path d={`M${sx((value-offset)*zoom)-4} ${top}h8l-4 7Z`} fill="#bf8740"/><text x={sx((value-offset)*zoom)+5} y={top+14} fill="#91651e" fontSize="10">P{i+1}</text></g>)}
 {!compact&&!circular&&cursor>=offset&&cursor<=offset+1/zoom&&<g><path d={`M${sx((cursor-offset)*zoom)} ${top}V${top+ph}`} stroke="#b8d7e4" strokeDasharray="4 4"/><rect x={Math.min(w-100,sx((cursor-offset)*zoom)+7)} y="33" width="83" height="21" rx="3" fill="#294b62"/><text x={Math.min(w-95,sx((cursor-offset)*zoom)+12)} y="47" fill="#d6e4ec" fontSize="10">{(xmin+cursor*(xmax-xmin)).toFixed(2)}</text></g>}
 {matrix.length>0&&<g><rect x={w-185} y="9" width="130" height="6" fill={`url(#${clip}r)`}/><text x={w-192} y="16" textAnchor="end" fill="#8cabbf" fontSize="9">{lo.toFixed(2)}</text><text x={w-49} y="16" fill="#8cabbf" fontSize="9">{hi.toFixed(2)}</text></g>}
 </svg>{!compact&&!!f.labels?.length&&<div className="figure-legend">{f.labels.map((label,i)=><span key={label}><i style={{background:colors[i%colors.length]}}/>{label}</span>)}</div>}{!compact&&<div className="figure-controls"><span>{hover?`${f.x.split('/')[0]} ${(xmin+hover.x*(xmax-xmin)).toFixed(2)}${matrix.length?` · 值 ${(matrix[Math.min(matrix.length-1,Math.floor((f.kind==='profile'?1-hover.y:hover.y)*matrix.length))]?.[Math.min(matrix[0].length-1,Math.floor(hover.x*matrix[0].length))]||0).toFixed(3)}`:''}`:localPick>=0?'已选中':''}</span>{!circular&&<><button aria-label="放大成果图" title="放大" onClick={()=>{setZoom(v=>Math.min(4,v+1));setOffset(0)}}><Plus size={14}/></button><button aria-label="缩小成果图" title="缩小" disabled={zoom===1} onClick={()=>{setZoom(v=>Math.max(1,v-1));setOffset(0)}}><Minus size={14}/></button><button aria-label="复位成果图" title="复位" onClick={()=>{setZoom(1);setOffset(0)}}><Home size={14}/></button>{zoom>1&&<input aria-label="图面平移" title="水平平移" type="range" min="0" max={1-1/zoom} step=".005" value={offset} onChange={e=>setOffset(+e.target.value)}/>}<button aria-label="切换坐标网格" title="坐标网格" aria-pressed={grid} onClick={()=>setGrid(v=>!v)}><Grid2X2 size={14}/></button></>}<button aria-label="导出当前图面" title="导出 SVG" onClick={()=>{if(ref.current){const copy=ref.current.cloneNode(true) as SVGSVGElement;copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.querySelectorAll('.figure-axes text').forEach(t=>t.setAttribute('fill',scientific?'#536776':'#8baabc'));exportFile(`${f.title}.svg`,new XMLSerializer().serializeToString(copy),'image/svg+xml')}}}><Download size={14}/></button></div>}</div>
}
