import {orbitSpeed,frameSeconds,getRotationMode} from './sceneMotion'
import {useEffect,useRef,useState} from 'react'
import {useWorkspaceAppearance} from './ScientificUI'
import * as THREE from 'three'
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'
export function AnalysisVolume({variant='events',slice=100,selected=0,onSelect}:{variant?:string;slice?:number;selected?:number;onSelect?:(i:number)=>void}){
 const scientific=useWorkspaceAppearance()==='scientific'
 const [layers,setLayers]=useState({strata:true,events:true,structures:true}),pose=useRef<{variant:string;position:THREE.Vector3;target:THREE.Vector3}|null>(null)
 const host=useRef<HTMLDivElement>(null),callback=useRef(onSelect);callback.current=onSelect
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{el.textContent='三维显示不可用，请查看下方剖面';return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));el.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,1000);camera.position.set(180,125,185)
 const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,-20,0);if(pose.current?.variant===variant){camera.position.copy(pose.current.position);orbit.target.copy(pose.current.target)}orbit.enableZoom=false;orbit.enableDamping=true;orbit.autoRotate=true;orbit.autoRotateSpeed=orbitSpeed('analysis');const wheel=(e:WheelEvent)=>{orbit.enableZoom=e.ctrlKey};renderer.domElement.addEventListener('wheel',wheel,{capture:true,passive:true});orbit.update()
 scene.add(new THREE.AmbientLight(0xb4d3ed,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(100,180,40);scene.add(light);const grid=new THREE.GridHelper(180,18,scientific?0x9bafbf:0x38576a,scientific?0xd0dce6:0x20394b);grid.position.y=-73;scene.add(grid)
 const pickables:THREE.Object3D[]=[];const material=(color:number,opacity=1)=>new THREE.MeshStandardMaterial({color,transparent:opacity<1,opacity,roughness:.55,side:THREE.DoubleSide,depthWrite:opacity>.6})
 const add=(g:THREE.BufferGeometry,c:number,pos:number[],opacity=1)=>{const mesh=new THREE.Mesh(g,material(c,opacity));mesh.position.set(pos[0],pos[1],pos[2]);scene.add(mesh);return mesh}
 const layerColors=[0x719ea4,0x557b92,0x355b77,0x28475d]
 if(layers.strata)for(let i=0;i<4;i++){const layer=add(new THREE.BoxGeometry(140,14,115),layerColors[i],[0,-i*18,0],variant==='velocity'?.65:.12);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(layer.geometry),new THREE.LineBasicMaterial({color:0x83a6bd,transparent:true,opacity:.25}));layer.add(edge)}
 if(layers.structures&&['fracture','connected','srv'].includes(variant))for(let i=0;i<14;i++){if(i/14*100>slice)continue;const mesh=add(new THREE.PlaneGeometry(22+i%4*5,27+i%3*5),[0x5c9fb0,0xd6a76b,0x91b28d][i%3],[Math.sin(i*2.1)*48,-12-i%4*14,Math.cos(i*1.1)*37],.7);mesh.rotation.set(.4+i*.19,.3+i*.7,.2);mesh.userData.index=i;pickables.push(mesh)}
 if(layers.structures&&variant==='srv')add(new THREE.SphereGeometry(45,24,16),0x65bfc2,[0,-24,0],.12).scale.set(1,.6,.85)
 if(layers.events)for(let i=0;i<75;i++){const z=-5-(i%5)*12;if((i%5)/4*100>slice)continue;const mesh=add(new THREE.SphereGeometry(i===selected?3.7:1.7,8,6),i===selected?(scientific?0xb65526:0xffffff):[0x79cdd1,0xe0b16c,0x9cb3dd][i%3],[Math.sin(i*2.39)*46+(i%3)*6,z,Math.cos(i*.83)*34]);mesh.userData.index=i;pickables.push(mesh)}
 if(layers.structures&&['location','coverage','risk'].includes(variant))for(let i=0;i<8;i++){const pos=new THREE.Vector3(Math.cos(i*Math.PI/4)*65,10,Math.sin(i*Math.PI/4)*52);add(new THREE.CylinderGeometry(2,2,7,8),0xadd1e3,[pos.x,pos.y,pos.z]);const geometry=new THREE.BufferGeometry().setFromPoints([pos,new THREE.Vector3(0,-30,0)]);scene.add(new THREE.Line(geometry,new THREE.LineBasicMaterial({color:0x5b9bb9,transparent:true,opacity:.5})))}if(layers.structures&&variant==='location')add(new THREE.SphereGeometry(15,24,16),0xf0bc7b,[0,-30,0],.16).scale.set(1,.7,1.4)
 if(layers.structures&&variant==='stress'){const origin=new THREE.Vector3(0,5,0);[new THREE.Vector3(1,.2,.1),new THREE.Vector3(.1,1,.1),new THREE.Vector3(.1,.1,1)].forEach((v,i)=>scene.add(new THREE.ArrowHelper(v.normalize(),origin,62,[0xe7b16c,0x7cbec4,0x809fda][i],8,4)))}
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let down=[0,0];const start=(e:PointerEvent)=>{down=[e.clientX,e.clientY]},pick=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=el.getBoundingClientRect();mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(pickables)[0];if(hit)callback.current?.(hit.object.userData.index)};el.addEventListener('pointerdown',start);el.addEventListener('pointerup',pick)
 const resize=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;if(w&&h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}});resize.observe(el);let visible=true;const observer=new IntersectionObserver(([entry])=>visible=entry.isIntersecting);observer.observe(el);let raf=0,last=0;const animate=(t:number)=>{raf=requestAnimationFrame(animate);if(!visible||document.hidden||t-last<32)return;const dt=frameSeconds(t,last);last=t;orbit.autoRotate=getRotationMode()>0;orbit.autoRotateSpeed=orbitSpeed('analysis');orbit.update(dt);renderer.render(scene,camera)};raf=requestAnimationFrame(animate)
 return()=>{pose.current={variant,position:camera.position.clone(),target:orbit.target.clone()};cancelAnimationFrame(raf);resize.disconnect();observer.disconnect();orbit.dispose();el.removeEventListener('pointerdown',start);el.removeEventListener('pointerup',pick);renderer.domElement.removeEventListener('wheel',wheel,true);scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments||o instanceof THREE.Line){o.geometry.dispose();const m=Array.isArray(o.material)?o.material:[o.material];m.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove()}
 },[variant,slice,selected,layers,scientific]);return <div className="analysis-volume-shell"><div className="analysis-volume" ref={host} aria-label={`${variant}三维成果视图`}/><div className="analysis-volume-layers">{([['strata','地层'],['events','事件'],['structures','结构']] as const).map(([k,label])=><button key={k} aria-pressed={layers[k]} onClick={()=>setLayers(v=>({...v,[k]:!v[k]}))}>{label}</button>)}</div></div>
}
