import {RecordSummary} from './RecordSummary'
import {ArrowLeft,ArrowRight,Database,FileCheck2,Orbit,Download} from 'lucide-react'
import {useMemo} from 'react'
import {useDemo,exportFile} from './store'
import {computeAnalysis} from './analysisEngine'
import {AnalysisFigure} from './AnalysisFigure'
import {goWorkspace} from './navigation'
import {moduleCatalog} from '../data/catalog'
export function AnalysisTrace({taskId}:{taskId:string}){const {state,visibleDevices}=useDemo(),task=state.tasks.find(t=>t.id===taskId&&(!t.source||visibleDevices.some(d=>d.id===t.source?.deviceId))),record=task?.analysis,result=useMemo(()=>record?record.result||computeAnalysis(record.request):null,[record]);if(!task||!record||!result)return <div className="empty">成果记录不存在。</div>;return <section><div className="lab-trace-heading"><div><small>数据回溯 / 已归档分析</small><h2>{moduleCatalog.find(m=>m.id===task.algorithm)?.name} · V{task.version}</h2></div><button onClick={()=>goWorkspace({page:'algorithm',id:task.algorithm,task:task.id,device:task.source?.deviceId})}><ArrowLeft size={14}/>返回此版本</button></div><div className="workspace-bridge"><span>{task.id}<small>{task.time}</small></span><span>#{record.digest}</span><span>{record.result?'归档图面':'兼容引擎重建'}</span><span>{record.mode==='computed'?'本地计算':'参考成果'}</span><button onClick={()=>exportFile(`${task.id}-证据包.json`,JSON.stringify({task,result,dataOrigin:result.source},null,2))}><Download size={14}/>导出证据包</button></div><div className="analysis-evidence-chain">{[{icon:Database,title:'输入记录',value:record.request.dataset},{icon:Orbit,title:'处理参数',value:`${Object.keys(record.request.params).length} 项 / ${record.request.excluded.length} 项排除`},{icon:FileCheck2,title:'冻结成果',value:`V${task.version} / ${record.digest}`}].map((n,i)=><article key={n.title}><n.icon size={22}/><div><small>{n.title}</small><strong>{n.value}</strong></div>{i<2&&<ArrowRight size={17}/>}</article>)}</div><div className="lab-trace-figures"><div><AnalysisFigure figure={result.figures[0]}/></div><div><AnalysisFigure figure={result.figures[1]}/></div></div><details className="analysis-source-details"><summary>数据来源与不可变输入</summary><p>{result.source} · {result.method}</p><p>关联设备仅为业务上下文，不代表合成记录由该设备现场采集。重放依据已保存的输入和引擎版本，不读取当前设备值。</p><RecordSummary value={record}/></details></section>}
