import {gnssObservationV2} from './demoSignals'
import {algorithmSpecs} from './algorithms'
export type FigureKind='wave'|'heat'|'lines'|'profile'|'polar'|'geometry'|'mechanism'|'stereo'|'slope'|'evidence'|'scatter'
export interface Figure {kind:FigureKind;title:string;x:string;y:string;matrix?:number[][];lines?:number[][];labels?:string[];range?:[number,number,number,number];points?:number[][];variant?:string}
export interface AnalysisOutput {id:string;dataset:string;mode:'computed'|'reference';method:string;source:string;figures:Figure[];metrics:{label:string;value:string;unit:string}[];digest:string;version:string}
export interface AnalysisRequest {id:string;dataset:string;params:Record<string,number>;excluded:string[]}
export const analysisGroups=[{name:'主动源面波',ids:algorithmSpecs.slice(0,9).map(s=>s.id)},{name:'被动源与微动',ids:algorithmSpecs.slice(9,17).map(s=>s.id)},{name:'微震与地下结构',ids:algorithmSpecs.slice(17,28).map(s=>s.id)},{name:'边坡与风险',ids:algorithmSpecs.slice(28).map(s=>s.id)}]
export const localMethods=new Set(['shot-gather','taup','fk','phase-shift-active','slant-stack','dispersion-pick','maps','beamforming','hvsr','event-detection','ps-pick','gnss-prediction'])
export const datasets=[{id:'L01',name:'北帮测线 L01',type:'面波',source:'合成校验记录 · 24 道 / 128 Hz',seed:1},{id:'L02',name:'南帮测线 L02',type:'面波',source:'合成校验记录 · 24 道 / 128 Hz',seed:2},{id:'EVT-006',name:'事件 EVT-006',type:'微震',source:'合成三分量事件 · 128 Hz',seed:3},{id:'GNSS-24H',name:'GNSS 24 h 序列',type:'位移',source:'合成趋势校验序列 · 30 min',seed:4},{id:'GNSS-24H-V2',name:'GNSS 多阶段位移',type:'位移',source:'合成多阶段观测 · 30 min / V2',seed:4}]
export const defaultDataset=(id:string)=>id==='gnss-prediction'?'GNSS-24H-V2':/multi-risk|slope/.test(id)?'GNSS-24H':analysisGroups[2].ids.includes(id)?'EVT-006':'L01'
export const datasetsFor=(id:string)=>datasets.filter(d=>id==='gnss-prediction'?['GNSS-24H','GNSS-24H-V2'].includes(d.id):defaultDataset(id)==='L01'?['L01','L02'].includes(d.id):d.id===defaultDataset(id))
export const parameterMax=(id:string,key:string,max:number)=>id==='fk'&&key==='频率上限'?63:id==='taup'&&key==='时间窗'||id==='slant-stack'&&key==='窗长'?2:id==='slant-stack'&&key==='叠加道数'||id==='gnss-prediction'&&key==='历史窗口'?24:max
export const defaultParams=(id:string)=>Object.fromEntries((algorithmSpecs.find(s=>s.id===id)||algorithmSpecs[0]).params.map(p=>[p[0],Math.min(p[1],parameterMax(id,p[0],p[3]))]))
const range=(n:number,fn:(i:number)=>number)=>Array.from({length:n},(_,i)=>fn(i))
const sum=(a:number[])=>a.reduce((s,x)=>s+x,0)
const peak=(a:number[])=>a.reduce((best,x,i)=>x>a[best]?i:best,0)
const normalize=(a:number[])=>{const m=Math.max(...a.map(Math.abs),1e-9);return a.map(v=>v/m)}
export function fft(input:number[]){const n=input.length;if(n<2||(n&(n-1)))throw new Error('FFT requires a power-of-two sample count');const re=[...input],im=range(n,()=>0);for(let i=1,j=0;i<n;i++){let b=n>>1;for(;j&b;b>>=1)j^=b;j^=b;if(i<j)[re[i],re[j]]=[re[j],re[i]]}for(let len=2;len<=n;len<<=1){const a=-2*Math.PI/len;for(let start=0;start<n;start+=len)for(let j=0;j<len/2;j++){const c=Math.cos(a*j),s=Math.sin(a*j),k=start+j,l=k+len/2,tr=re[l]*c-im[l]*s,ti=re[l]*s+im[l]*c;re[l]=re[k]-tr;im[l]=im[k]-ti;re[k]+=tr;im[k]+=ti}}return {re,im,power:re.slice(0,n/2).map((v,i)=>Math.hypot(v,im[i])/n)}}
export function syntheticTraces(seed=1,n=256){return Array.from({length:24},(_,c)=>range(n,i=>{const t=i/128,delay=c*.017,arrive=.48+seed*.028+delay;return Math.sin((t-arrive)*2*Math.PI*(13+seed))*Math.exp(-1*((t-arrive)/.12)**2)+.58*Math.sin((t-arrive-.34)*2*Math.PI*8)*Math.exp(-1*((t-arrive-.34)/.19)**2)+.045*Math.sin(i*1.73+c*3.11+seed)+(c===2?.23*Math.sin(i*2.4):0)}))}
export function staLta(trace:number[],sta:number,lta:number){const e=trace.map(v=>v*v),p=[0];for(const v of e)p.push(p[p.length-1]+v);return e.map((_,i)=>i<lta?0:((p[i+1]-p[Math.max(0,i+1-sta)])/sta)/Math.max(1e-9,(p[i+1]-p[i+1-lta])/lta))}
export function triggerWindows(values:number[],on:number,off=on*.55){const out:[number,number][]=[];let begin=-1;values.forEach((v,i)=>{if(begin<0&&v>=on)begin=i;if(begin>=0&&(v<off||i===values.length-1)){out.push([begin,i]);begin=-1}});return out}
export function linearFit(values:number[]){const n=values.length,x=sum(range(n,i=>i)),xx=sum(range(n,i=>i*i)),y=sum(values),xy=sum(values.map((v,i)=>v*i)),slope=(n*xy-x*y)/Math.max(1,n*xx-x*x),intercept=(y-slope*x)/n;return {slope,intercept,rmse:Math.sqrt(sum(values.map((v,i)=>(v-intercept-slope*i)**2))/n)}}
const cache=new Map<string,AnalysisOutput>()
export function computeAnalysis(request:AnalysisRequest):AnalysisOutput{
 const {id,dataset,excluded}=request,p={...defaultParams(id),...request.params},seed=datasets.find(d=>d.id===dataset)?.seed||1
 if(!algorithmSpecs.some(s=>s.id===id))throw new Error('未识别的分析方法')
 if(!datasetsFor(id).some(d=>d.id===dataset))throw new Error('输入记录类型与分析方法不匹配')
 for(const spec of algorithmSpecs.find(s=>s.id===id)?.params||[]){if(!Number.isFinite(p[spec[0]])||p[spec[0]]<spec[2]||p[spec[0]]>spec[3])throw new Error(`参数超出范围：${spec[0]}`)}
 if(id==='phase-shift-active'&&p['最低相速度']>=p['最高相速度'])throw new Error('最低相速度必须小于最高相速度')
 if(id==='event-detection'&&p['STA 窗长']>=p['LTA 窗长'])throw new Error('STA 窗长必须小于 LTA 窗长')
 if(id==='hvsr'&&Array.from({length:8},(_,i)=>`CH-${String(i+1).padStart(2,'0')}`).filter(c=>!excluded.includes(c)).length<2)throw new Error('至少保留两个有效窗口')
 if(id==='beamforming'&&Array.from({length:12},(_,i)=>`CH-${String(i+1).padStart(2,'0')}`).filter(c=>!excluded.includes(c)).length<3)throw new Error('至少保留三个有效台站')
 const key=JSON.stringify([id,dataset,p,[...excluded].sort()]);if(cache.has(key))return cache.get(key)!
 const all=syntheticTraces(seed),indices=all.map((_,i)=>i).filter(i=>!excluded.includes(`CH-${String(i+1).padStart(2,'0')}`)),traces=indices.map(i=>all[i]);if(traces.length<2)throw new Error('至少保留两个有效通道')
 const spectra=traces.map(a=>fft(a)),reference=!localMethods.has(id),figures:Figure[]=[]
 const metric=(label:string,value:number|string,unit='')=>({label,value:typeof value==='number'?Number(value.toFixed(3)).toString():value,unit})
 let metrics=[metric('有效通道',traces.length,'道'),metric('采样率',128,'Hz'),metric('记录时长',2,'s')],method='可复现的本地数据处理'
 const wave=(title='原始炮集',data=traces):Figure=>({kind:'wave',title,x:'时间 / s',y:'通道',lines:data,range:[0,2,0,data.length]})
 const lines=(title:string,data:number[][],x:string,y:string,labels:string[]=[],bounds?:Figure['range']):Figure=>({kind:'lines',title,x,y,lines:data,labels,range:bounds})
 const heat=(title:string,matrix:number[][],x:string,y:string,bounds?:Figure['range']):Figure=>({kind:'heat',title,x,y,matrix,range:bounds})
 const spectral=()=>lines('通道振幅谱',spectra.slice(0,3).map(s=>s.power.slice(1,100)),'频率 / Hz','振幅',indices.slice(0,3).map(i=>`CH-${String(i+1).padStart(2,'0')}`),[.5,49.5,0,Math.max(...spectra.flatMap(s=>s.power))])
 const fc=(phase=false)=>Array.from({length:36},(_,v)=>range(64,f=>{const speed=(p['最低相速度']||100)+v*((p['最高相速度']||900)-(p['最低相速度']||100))/35,k=f+2;let re=0,im=0;spectra.forEach((s,j)=>{const a=2*Math.PI*k*.5*indices[j]*(p['道间距']||5)/speed,m=phase?Math.max(Math.hypot(s.re[k],s.im[k]),1e-8):1;re+=(s.re[k]*Math.cos(a)-s.im[k]*Math.sin(a))/m;im+=(s.re[k]*Math.sin(a)+s.im[k]*Math.cos(a))/m});return Math.hypot(re,im)/traces.length}))
 if(id==='shot-gather'){const gap=p['道间距'],shot=p['炮点号'];figures.push(wave(),{kind:'geometry',title:'测线与炮点',x:'测线距离 / m',y:'位置',points:indices.map(i=>[i*gap,0,i===shot?1:0]),variant:'array',range:[0,23*gap,-1,1]},spectral());metrics=[metric('保留道数',traces.length,'道'),metric('测线长度',23*gap,'m'),metric('炮点号',shot)];method='道集整理 / 原始采样不做插值'}
 else if(id==='taup'||id==='slant-stack'){
  const dt=1/128,slowness=(p['慢度上限']||8)/1000,window=Math.min(2,p['时间窗']||p['窗长']||2),n=Math.round(window*128),matrix=Array.from({length:40},(_,r)=>range(80,i=>{const t=i*n/80;return sum(traces.slice(0,p['叠加道数']||24).map((a,j)=>a[Math.round(t+indices[j]*5*r/39*slowness/dt)]||0))/Math.min(traces.length,p['叠加道数']||24)}));figures.push(heat(id==='taup'?'τ-p 变换 / 相干振幅':'倾斜叠加 / 扫描响应',matrix,'截距时间 / s','慢度 / ms·m⁻¹',[0,window,0,slowness*1000]),wave(),lines('扫描能量',matrix.map(a=>a.map(v=>v*v)).filter((_,i)=>i%8===0),'时间 / s','能量',[],[0,window,0,Math.max(...matrix.flat().map(v=>v*v))]));method='时域线性移位叠加，最近邻采样';metrics=[metric('有效时窗',window,'s'),metric('扫描慢度',slowness*1000,'ms/m'),metric('叠加道数',Math.min(traces.length,p['叠加道数']||24),'道')]
 }else if(id==='fk'){
  const kmax=p['波数上限'],fmax=Math.min(63,p['频率上限']),m=Array.from({length:40},(_,r)=>range(70,i=>{const k=Math.round(i*fmax/69*2),spatial=-kmax+2*kmax*r/39;let re=0,im=0;spectra.forEach((s,j)=>{const a=2*Math.PI*spatial*indices[j]*5;re+=s.re[k]*Math.cos(a)+s.im[k]*Math.sin(a);im+=s.im[k]*Math.cos(a)-s.re[k]*Math.sin(a)});return Math.hypot(re,im)/traces.length}));figures.push(heat('频率—波数能量谱',m,'频率 / Hz','波数 / m⁻¹',[0,fmax,-kmax,kmax]),wave(),spectral());method='时间 FFT + 空间离散傅里叶扫描（原记录 256 点）'
 }else if(id==='phase-shift-active'||id==='dispersion-pick'){
  const m=fc(true),curve=range(64,f=>{const column=m.map(a=>a[f]),v=peak(column);return (id==='dispersion-pick'&&column[v]<(p['能量门槛']||.6))?NaN:(p['最低相速度']||100)+v*((p['最高相速度']||900)-(p['最低相速度']||100))/35});figures.push(heat(id==='dispersion-pick'?'频散曲线拾取与有效频段':'相位叠加频散能量',m,'频率 / Hz','相速度 / m·s⁻¹',[1,32.5,p['最低相速度']||100,p['最高相速度']||900]),lines('能量脊线 / 逐频峰值', [curve],'频率 / Hz','相速度 / m·s⁻¹',['峰值曲线'],[1,32.5,p['最低相速度']||100,p['最高相速度']||900]),wave());method=id==='dispersion-pick'?'相位谱逐频最大值 + 能量门槛筛选':'归一化频谱的相移速度扫描';metrics=[metric('有效频点',curve.filter(Number.isFinite).length,'点'),metric('速度范围',`${p['最低相速度']||100}–${p['最高相速度']||900}`,'m/s'),metric('扫描频带','1–32.5','Hz')]
 }else if(id==='maps'){
  const max=80,cor=traces.slice(1,9).map(a=>range(max*2+1,j=>{const lag=j-max;return sum(traces[0].map((v,i)=>v*(a[i+lag]||0)))/traces[0].length}));figures.push({...wave('双台互相关道集',cor),range:[-max/128,max/128,0,cor.length],x:'时延 / s'},lines('相关叠加',[range(max*2+1,i=>sum(cor.map(a=>a[i]))/cor.length)],'时延 / s','相关幅值',['叠加'],[-max/128,max/128,-.15,.15]),{kind:'geometry',title:'参与台站对',x:'X / m',y:'Y / m',variant:'pairs',points:indices.slice(0,9).map(i=>[i*5,0,0]),range:[0,115,-1,1]});method='归一化前的时域互相关 / 等权叠加'
 }else if(id==='beamforming'){
  const m=Array.from({length:24},(_,r)=>range(72,i=>{const angle=i*2*Math.PI/72,slow=r/23*p['慢度上限']/1000,f=p['中心频率'];let re=0,im=0;for(const j of indices.filter(i=>i<12)){const a=j*Math.PI/6,x=30*Math.cos(a),y=30*Math.sin(a),observed=(x*Math.cos(2.1+seed*.04)+y*Math.sin(2.1+seed*.04))*.0032,trial=(x*Math.cos(angle)+y*Math.sin(angle))*slow,phase=2*Math.PI*f*(observed-trial);re+=Math.cos(phase);im+=Math.sin(phase)}return Math.hypot(re,im)/Math.max(1,indices.filter(i=>i<12).length)}));figures.push({kind:'polar',title:'方位—慢度波束功率',x:'传播方位 / °',y:'慢度 / ms·m⁻¹',matrix:m,range:[0,360,0,p['慢度上限']]},{kind:'geometry',title:'圆形台阵与传播方向',x:'东向 / m',y:'北向 / m',variant:'circle',points:indices.filter(i=>i<12).map(j=>[30*Math.cos(j*Math.PI/6),30*Math.sin(j*Math.PI/6),0]),range:[-30,30,-30,30]},lines('最大波束功率',[range(72,i=>Math.max(...m.map(a=>a[i])))],'方位 / °','相干幅值',['波束'],[0,360,0,1]));method='合成平面波的窄带延时求和 / 十二站圆形阵列';metrics=[metric('入射方位',(2.1+seed*.04)*180/Math.PI,'°'),metric('扫描慢度',p['慢度上限'],'ms/m'),metric('中心频率',p['中心频率'],'Hz')]
 }else if(id==='hvsr'){
  const components=Array.from({length:8},(_,w)=>{const z=fft(range(256,i=>Math.sin(i*.22)+.4*Math.sin(i*.62)+.12*Math.sin(i*1.71+w))),x=fft(range(256,i=>Math.sin(i*.22)+(2+w*.08+seed*.12)*Math.sin(i*.62)+.15*Math.sin(i*1.71+w))),y=fft(range(256,i=>.85*(Math.sin(i*.22)+(2+w*.08+seed*.12)*Math.sin(i*.62)+.15*Math.sin(i*1.71+w))));return {x:x.power,y:y.power,z:z.power,index:w}}).filter(w=>!excluded.includes(`CH-${String(w.index+1).padStart(2,'0')}`))
  const windows=components.map(c=>range(70,i=>Math.min(6,Math.hypot(c.x[i+2],c.y[i+2])/Math.SQRT2/Math.max(.004,c.z[i+2])))),mean=range(70,i=>sum(windows.map(a=>a[i]))/windows.length),componentMean=(axis:'x'|'y'|'z')=>range(70,i=>sum(components.map(c=>c[axis][i+2]))/components.length)
  figures.push(lines('H/V 谱比与窗口集合',[...windows,mean],'频率 / Hz','H/V',[...components.map(c=>`窗口 ${c.index+1}`),'均值'],[1,35.5,0,6]),lines('三分量平均振幅谱',['x','y','z'].map(axis=>componentMean(axis as 'x'|'y'|'z')),'频率 / Hz','振幅',['水平 X','水平 Y','垂向 Z'],[1,35.5,0,Math.max(...components.flatMap(c=>[...c.x,...c.y,...c.z]))]),heat('各窗口谱比',windows,'频率 / Hz','窗口',[1,35.5,1,windows.length]));method='合成三分量 FFT / 水平分量均方根与垂向谱比';metrics=[metric('主峰频率',(peak(mean)+2)*.5,'Hz'),metric('峰值谱比',Math.max(...mean)),metric('统计窗数',windows.length,'窗')]
 }else if(id==='event-detection'||id==='ps-pick'){
  const a=traces[0],sta=Math.max(2,Math.round((p['STA 窗长']||p['P 窗长']||.05)*128)),lta=Math.max(sta+1,Math.round((p['LTA 窗长']||.5)*128)),ratio=staLta(a,sta,lta),threshold=p['触发比']||2.5,triggers=triggerWindows(ratio,threshold);figures.push(wave(id==='ps-pick'?'三分量与候选到时':'连续记录与事件窗口',traces.slice(0,6)),lines('短长时能量比与触发门槛',[ratio,range(256,()=>threshold)],'时间 / s','STA/LTA',['特征值','门槛'],[0,2,0,Math.max(6,...ratio)]),heat('逐通道能量包络',traces.slice(0,12).map(a=>range(80,j=>Math.abs(a[Math.round(j*255/79)]))),'时间 / s','通道',[0,2,1,12]));method='滑动均方能量 STA/LTA；P/S 标记需人工复核';metrics=[metric('候选窗口',triggers.length,'个'),metric('首触发',triggers.length?triggers[0][0]/128:'未触发','s'),metric('峰值比',Math.max(...ratio))]
 }else if(id==='gnss-prediction'){
  const history=range(48,i=>dataset==='GNSS-24H-V2'?gnssObservationV2(i):2+i*.18+.22*Math.sin(i*.42+seed)),n=Math.min(48,Math.round(p['历史窗口']*2)),recent=history.slice(-n),fit=linearFit(recent),horizon=Math.round(p['预测时长']*2),full=history.length+horizon,pred=range(full,i=>i<48-n?NaN:fit.intercept+fit.slope*(i-(48-n))),upper=pred.map((v,i)=>i<47?NaN:v+1.96*fit.rmse*Math.sqrt(1+(i-47)/n)),lower=pred.map((v,i)=>i<47?NaN:v-1.96*fit.rmse*Math.sqrt(1+(i-47)/n));figures.push(lines('位移观测、线性外推与残差带',[[...history,...range(horizon,()=>NaN)],pred,upper,lower],'时间 / h','累计位移 / mm',['观测','线性模型','上界','下界'],[0,dataset==='GNSS-24H-V2'?(full-1)/2:full/2,0,dataset==='GNSS-24H-V2'?Math.max(...upper.filter(Number.isFinite),...history)+.3:Math.max(...pred.filter(Number.isFinite))+1]),lines('拟合残差',[recent.map((v,i)=>v-fit.intercept-fit.slope*i)],'样本','残差 / mm',['残差']),lines('相邻时段增量',[history.slice(1).map((v,i)=>v-history[i])],'时间 / h','增量 / mm',['增量']));method='最小二乘直线外推；带宽为残差估计，不代表校准预测概率';metrics=[metric('趋势速率',fit.slope*2,'mm/h'),metric('拟合 RMSE',fit.rmse,'mm'),metric('预测时长',p['预测时长'],'h')]
 }else{
  // Authored reference records: immutable analysis scenes, never presented as a numerical solver.
  method='参考成果审阅 / 固定模型库 V1（非现场求解）'
  const f=referenceFigures(id,seed);figures.push(...f);metrics=[metric('成果视图',f.length,'幅'),metric('参考版本','V1'),metric('模式','成果审阅')]
 }
 const digest=hashText(key),out:AnalysisOutput={id,dataset,mode:reference?'reference':'computed',method,source:reference?'内置参考模型 / 合成场景':datasets.find(d=>d.id===dataset)?.source||'合成校验数据',figures,metrics,digest,version:'analysis-v1'}
 if(cache.size>24)cache.delete(cache.keys().next().value!);cache.set(key,out);return out
}
export function hashText(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return (h>>>0).toString(16).padStart(8,'0')}
function referenceFigures(id:string,seed:number):Figure[]{
 const line=(title:string,lines:number[][],x:string,y:string):Figure=>({kind:'lines',title,lines,x,y})
 const section=(title:string,variant:string):Figure=>({kind:'profile',title,x:'测线距离 / m',y:'深度 / m',variant,range:[0,480,0,160],matrix:Array.from({length:35},(_,z)=>range(65,x=>variant==='fracture'?.08+.88*Math.exp(-1*((x-34)/14)**2-((z-17)/9)**2):variant==='permeability'?1+60*Math.exp(-1*((x-34)/14)**2-((z-17)/9)**2):variant==='coverage'?Math.exp(-1*((x-32)/29)**2-z/40):250+z*16-230*Math.exp(-1*((x-34)/10)**2-((z-17)/6)**2)+25*Math.sin(x*.13+seed)))})
 const space=(title:string,variant:string):Figure=>({kind:'geometry',title,x:'东向 / m',y:'北向 / m',variant})
 const fit=()=>line('观测与模型响应',[range(80,i=>220+560*Math.exp(-i/26)),range(80,i=>226+552*Math.exp(-i/27)+8*Math.sin(i*.2))],'频率 / Hz','相速度 / m·s⁻¹')
 const model=()=>({kind:'profile' as const,title:'Vs—深度候选模型',x:'横波速度 / m·s⁻¹',y:'深度 / m',variant:'layers',lines:Array.from({length:9},(_,j)=>range(60,i=>220+Math.floor(i/10)*88+18*Math.sin(i*.04+j)))})
 const dispersion=(title:string,variant=0):Figure=>({kind:'heat',title,x:'频率 / Hz',y:'相速度 / m·s⁻¹',range:[1,60,100,1200],matrix:Array.from({length:35},(_,r)=>range(65,c=>Math.exp(-1*((r-7-20*Math.exp(-c/(20+variant)))/1.4)**2)+.5*Math.exp(-1*((r-14-20*Math.exp(-c/26))/1.1)**2)))})
 const residual=()=>line('归档迭代残差',[range(65,i=>.48*Math.exp(-i/13)+.015),range(65,i=>.3*Math.exp(-i/9)+.04)],'迭代步','归一化残差')
 switch(id){
  case 'hrlrt':return [dispersion('高分辨率频散 / 参考成果'),dispersion('常规频散 / 对照成果',12),residual()]
  case 'surface-inversion':return [model(),fit(),residual()]
  case 'section-imaging':return [section('测线 L01 · 拟二维速度剖面','section'),model(),space('测线与反演位置','survey')]
  case 'spac':return [line('距离组自相关系数',Array.from({length:5},(_,j)=>range(100,i=>Math.cos(i*(.08+j*.02))/Math.sqrt(1+i*.07))),'频率 / Hz','相关系数'),space('距离分组与台站对','circle'),dispersion('SPAC 频散参考成果')]
  case 'remi':return [dispersion('ReMi · 频率—相速度成果',5),{kind:'heat',title:'窗口质量与能量分布',x:'窗口',y:'频率 / Hz',matrix:Array.from({length:24},(_,r)=>range(48,c=>Math.abs(Math.sin(c*.13)*Math.cos(r*.2))))},space('线性台阵','survey')]
  case 'fh':return [dispersion('F-H 变换能量',9),space('同心阵列与积分环','circle'),line('径向响应',[range(100,i=>Math.sin(i*.2)/Math.sqrt(1+i*.1))],'距离 / m','响应')]
  case 'cmp-ts':return [section('CMP 叠加剖面','cmp'),space('共中点分箱覆盖','bins'),line('各分箱覆盖次数',[range(64,i=>Math.floor(3+8*Math.sin(i/64*Math.PI)))],'中点箱号','覆盖次数')]
  case 'passive-inversion':return [model(),fit(),line('H/V 约束拟合',[range(80,i=>1+3*Math.exp(-1*((i-28)/9)**2)),range(80,i=>1+2.8*Math.exp(-1*((i-29)/10)**2))],'频率 / Hz','H/V')]
  case 'array-design':return [space('台阵布设与几何覆盖','coverage'),section('深度切片 · 几何敏感度','coverage'),space('台站方位分布','circle')]
  case 'velocity-model':return [space('Vp / Vs 分层体与剖切','velocity'),section('速度体切片','velocity'),model()]
  case 'event-location':return [space('事件位置与台站射线','location'),line('各台站到时残差',[range(12,i=>4*Math.sin(i*1.3))],'台站','残差 / ms'),{kind:'scatter',title:'事件平面投影与误差',x:'东向 / m',y:'北向 / m',points:rangePoints(60,seed)}]
  case 'magnitude-energy':return [line('位移谱与拐角拟合',[range(100,i=>1/(1+(i/23)**2)*(1+.08*Math.sin(i))),range(100,i=>1/(1+(i/23)**2))],'频率 / Hz','归一化位移谱'),{kind:'scatter',title:'事件震级—能量分布',x:'震级 ML',y:'log 能量',points:rangePoints(45,seed)},line('台站幅值校正',[range(20,i=>.4+.2*Math.sin(i*.7))],'台站','幅值')]
  case 'moment-tensor':return [{kind:'mechanism',title:'震源机制与初动极性',x:'方位',y:'倾角'},line('观测 / 合成响应',[range(150,i=>Math.sin(i*.4)*Math.exp(-1*((i-60)/23)**2)),range(150,i=>.93*Math.sin(i*.4+.08)*Math.exp(-1*((i-61)/22)**2))],'时间 / s','振幅'),{kind:'scatter',title:'候选解拟合度',x:'解编号',y:'拟合残差',points:rangePoints(30,seed)}]
  case 'stress-inversion':return [{kind:'stereo',title:'主应力方向 · 赤平投影',x:'方位角',y:'倾角'},space('三向主应力轴','stress'),line('事件组角度失配',[range(40,i=>8+6*Math.abs(Math.sin(i*.6)))],'事件组','失配角 / °')]
  case 'fracture-network':return [space('DFN · 裂缝面与事件簇','fracture'),{kind:'stereo',title:'裂缝产状与优势方向',x:'走向',y:'倾角',variant:'fracture'},section('裂缝相对密度剖面 / 归一化','fracture')]
  case 'permeability':return [space('SRV 包络与连通簇','srv'),section('等效渗透率切片 / mD','permeability'),space('连通路径','connected')]
  case 'event-attributes':return [space('时空事件群','events'),{kind:'heat',title:'时段—深度事件密度',x:'时间 / h',y:'深度 / m',matrix:Array.from({length:35},(_,r)=>range(65,c=>Math.exp(-1*((r-18)/8)**2-((c-35)/13)**2)+.1*Math.abs(Math.sin(c+r))))},line('事件数量与能量演变',[range(60,i=>3+Math.abs(Math.sin(i*.14))*10),range(60,i=>4+Math.abs(Math.cos(i*.1))*8)],'时间 / h','归一化属性')]
  case 'slope-stability':return [{kind:'slope',title:'边坡剖面 · 地下水与候选滑面',x:'水平距离 / m',y:'高程 / m'},line('归档工况对比',[range(6,i=>1.52-i*.07),range(6,i=>1.43-i*.085)],'工况编号','参考安全系数'),space('工程地层','velocity')]
  default:return [{kind:'evidence',title:'风险证据关联',x:'来源',y:'状态'},line('位移 / 微震 / 降雨 · 时间对齐',[range(100,i=>i*.3+5*Math.sin(i*.13)),range(100,i=>7+25*Math.exp(-1*((i-67)/11)**2)),range(100,i=>5+30*Math.exp(-1*((i-48)/16)**2))],'时间 / h','归一化响应'),space('风险关联区域','risk')]
 }
}
export function rangePoints(n:number,seed=1){return Array.from({length:n},(_,i)=>[50+27*Math.sin(i*1.73+seed)+i*.1,50+23*Math.cos(i*.83+seed),i%3])}
