import {BoardSelectionContext} from './BoardSelection'
import {BoardViewport} from './BoardViewport'
import {WorkspaceDrawer} from './WorkspaceDrawer'
import {AlgorithmCover} from './AlgorithmCover'
import {Undo2,Redo2,PanelLeftClose,PanelLeftOpen,Settings2,History,RotateCcw,Play,Pause,ChevronLeft,ChevronRight} from 'lucide-react'
import {sceneTime} from './sceneCatalog'
import { useEffect, useRef, useState, type PointerEvent, type CSSProperties } from 'react'
import { GripVertical, Plus, Trash2, Save, MonitorPlay, LayoutTemplate, Star, ArrowLeft, Maximize2, Info, Mountain } from 'lucide-react'
import { widgetCatalog, widgetCategoryOrder } from '../data/catalog'
import { CompactWidget } from './ModuleWorkbench'
import { useDemo } from './store'
import { arrangeBoard, boardDisplayName, pageDisplayName, BOARD_DRAFT_KEY, BOARD_KEY, boardTemplates, makePage, migrateBoard, newBoard, normalizeBoard, PAGE_LIMIT, reorderBoard, type BoardDocument, type BoardPage } from './boardLayout'
const valid=new Set(widgetCatalog.map(w=>w.kind))
export function loadBoard(draft=false){
 try{const saved=localStorage.getItem(draft?BOARD_DRAFT_KEY:BOARD_KEY);if(saved){const doc=normalizeBoard(JSON.parse(saved),valid);if(doc)return doc}
 if(draft){const doc=localStorage.getItem(BOARD_KEY);if(doc){const parsed=normalizeBoard(JSON.parse(doc),valid);if(parsed)return parsed}}
 for(const key of ['kuangda-dashboard-layout-3x3','kuangda-dashboard-layout']){const raw=localStorage.getItem(key);if(raw){const doc=migrateBoard(JSON.parse(raw),valid);if(doc)return doc}}
 }catch{/* Keep previous saved entries intact if a stale draft cannot be parsed. */}
 return newBoard()
}
export function BoardStudio({presentation=false,onPreview,onBack}:{presentation?:boolean;onPreview?:()=>void;onBack?:()=>void}){
 const {can,state,visibleDevices,selectDevice,control}=useDemo(),[doc,setDoc]=useState<BoardDocument>(()=>loadBoard(!presentation)),[pageIndex,setPageIndex]=useState(()=>{try{return Math.max(0,Number(sessionStorage.getItem('kuangda-board-page'))||0)}catch{return 0}}),[category,setCategory]=useState('全部'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(()=>{try{return !presentation&&!!localStorage.getItem(BOARD_DRAFT_KEY)&&JSON.stringify(loadBoard(true))!==JSON.stringify(loadBoard(false))}catch{return false}}),[focus,setFocus]=useState(''),[drop,setDrop]=useState(''),[fullscreenError,setFullscreenError]=useState('')
 const [paletteOpen,setPaletteOpen]=useState(()=>typeof window!=='undefined'&&window.innerWidth>800),[settings,setSettings]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[revision,setRevision]=useState(0)
 const past=useRef<BoardDocument[]>([]),future=useRef<BoardDocument[]>([]),saved=useRef(JSON.stringify(loadBoard(false)))
 const versions=useRef<{time:string;doc:BoardDocument}[]>((()=>{try{return JSON.parse(localStorage.getItem('kuangda-board-versions')||'[]').filter((v:{doc:BoardDocument})=>normalizeBoard(v.doc,valid))}catch{return []}})())
 const restore=(next:BoardDocument)=>{past.current.push(doc);future.current=[];setDoc(next);setDirty(JSON.stringify(next)!==saved.current);setRevision(v=>v+1)}
 const travel=(forward:boolean)=>{if(!can('config'))return;const from=forward?future:past,to=forward?past:future,next=from.current.pop();if(!next)return;to.current.push(doc);setDoc(next);setDirty(JSON.stringify(next)!==saved.current);setRevision(v=>v+1);setNotice(forward?'已重做':'已撤销')}
 const drag=useRef<{source:string;x:number;y:number;moved:boolean;target:string}|null>(null)
 useEffect(()=>{try{sessionStorage.setItem('kuangda-board-page',String(pageIndex))}catch{}},[pageIndex])
 const page=doc.pages[Math.min(pageIndex,doc.pages.length-1)],tiles=arrangeBoard(page),used=new Set(page.items.map(i=>i.kind))
 useEffect(()=>{if(!presentation&&can('config'))try{localStorage.setItem(BOARD_DRAFT_KEY,JSON.stringify(doc))}catch{setNotice('草稿无法持久保存，请导出或释放本地存储。')}},[doc,presentation,state.role])
 const change=(next:BoardDocument)=>{if(!can('config'))return;past.current=[...past.current.slice(-39),doc];future.current=[];setDoc(next);setDirty(JSON.stringify(next)!==saved.current);setRevision(v=>v+1)}
 const choose=(id:string)=>{selectDevice(id);if(!presentation)change({...doc,context:{device:id,frame:state.frame}})}
 useEffect(()=>{if(doc.context){selectDevice(doc.context.device);control({frame:doc.context.frame,playing:false})}},[doc.context?.device,doc.context?.frame])
 const setPage=(next:BoardPage)=>change({...doc,pages:doc.pages.map(p=>p.id===page.id?next:p)})
 const save=()=>{if(!can('config'))return false;try{const next={...doc,context:{device:state.selectedDevice,frame:state.frame}};localStorage.setItem(BOARD_KEY,JSON.stringify(next));localStorage.setItem(BOARD_DRAFT_KEY,JSON.stringify(next));setDoc(next);saved.current=JSON.stringify(next);versions.current=[{time:new Date().toLocaleString('zh-CN',{hour12:false}),doc:structuredClone(next)},...versions.current].slice(0,8);try{localStorage.setItem('kuangda-board-versions',JSON.stringify(versions.current))}catch{/* Main saved document is already durable. */}setDirty(false);setNotice('已保存');return true}catch{setNotice('保存失败：请检查本地存储。');return false}}
 const add=(kind:string,beforeId?:string)=>{if(used.has(kind)||page.items.length>=PAGE_LIMIT)return;const item={id:crypto.randomUUID(),kind},items=[...page.items],index=items.findIndex(i=>i.id===beforeId);items.splice(index<0?items.length:index,0,item);setPage({...page,items,primary:beforeId&&page.items.find(i=>i.id===beforeId)?.kind===page.primary?kind:page.primary||kind});setFocus(item.id);if(typeof window!=='undefined'&&window.innerWidth<=800)setPaletteOpen(false);setNotice('已添加')}
 const nudge=(id:string,delta:number)=>{const items=tiles.map(t=>t.item),from=items.findIndex(i=>i.id===id),to=from+delta;if(from<0||to<0||to>=items.length)return;setPage(reorderBoard(page,id,items[to].id))}
 const movePointer=(e:PointerEvent<HTMLElement>)=>{const d=drag.current;if(!d)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>5)d.moved=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-board-item]')?.dataset.boardItem||(document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-board-canvas]')?'canvas':'');d.target=target;setDrop(target)}
 const finish=(e:PointerEvent<HTMLElement>)=>{const d=drag.current;drag.current=null;setDrop('');if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!d?.moved||!d.target)return;if(d.source.startsWith('palette:'))add(d.source.slice(8),d.target);else setPage(reorderBoard(page,d.source,d.target))}
 const start=(e:PointerEvent<HTMLElement>,source:string)=>{if(e.button!==0||!can('config'))return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={source,x:e.clientX,y:e.clientY,moved:false,target:''}}
 const selectedTile=tiles.find(t=>t.item.id===focus)||tiles[0]
 const remove=(id:string)=>{if(!can('config')){setNotice('当前为角色预览，请退出预览后编排。');return}const item=page.items.find(i=>i.id===id);setPage({...page,items:page.items.filter(i=>i.id!==id),primary:page.primary===item?.kind?'':page.primary});setFocus('');setNotice('已移除，可撤销')}
 const grid=<BoardViewport ratio={doc.ratio}><div className={`board-canvas ratio-${doc.ratio.replace(':','-')}`} data-board-canvas>{tiles.map(t=><section key={t.item.id} data-board-item={t.item.id} data-kind={t.item.kind} data-rect={`${t.x},${t.y},${t.w},${t.h}`} className={`board-tile variant-${t.variant} ${drop===t.item.id?'drop-target':''} ${!presentation&&selectedTile?.item.id===t.item.id?'tile-focused':''}`} style={{'--tile-col':`${t.x+1} / span ${t.w}`,'--tile-row':`${t.y+1} / span ${t.h}`} as CSSProperties}>
 {!presentation&&<div className="board-tile-controls"><button aria-label={`移动${widgetCatalog.find(w=>w.kind===t.item.kind)?.name}`} onPointerDown={e=>start(e,t.item.id)} onPointerMove={movePointer} onPointerUp={finish} onPointerCancel={()=>{drag.current=null;setDrop('')}}><GripVertical size={13}/></button><button aria-label={`前移${widgetCatalog.find(w=>w.kind===t.item.kind)?.name}`} disabled={tiles[0]?.item.id===t.item.id} onClick={()=>nudge(t.item.id,-1)}><ChevronLeft size={13}/></button><button aria-label={`后移${widgetCatalog.find(w=>w.kind===t.item.kind)?.name}`} disabled={tiles.at(-1)?.item.id===t.item.id} onClick={()=>nudge(t.item.id,1)}><ChevronRight size={13}/></button><button aria-label={`设为主视区${t.item.kind}`} title="设为主视区" onClick={()=>setPage({...page,primary:t.item.kind})}><Star size={12} fill={page.primary===t.item.kind?'currentColor':'none'}/></button><button aria-label={`移除${widgetCatalog.find(w=>w.kind===t.item.kind)?.name}`} disabled={!can('config')} onClick={()=>remove(t.item.id)}><Trash2 size={12}/></button></div>}
 <CompactWidget kind={t.item.kind} editing={!presentation}/>{!presentation&&<button className="board-select-surface" aria-label={`选择${widgetCatalog.find(w=>w.kind===t.item.kind)?.name}`} onClick={()=>setFocus(focus===t.item.id?'':t.item.id)}/>}</section>)}{!tiles.length&&<div className="board-empty"><LayoutTemplate size={35}/><h3>添加组件</h3><p></p></div>}</div></BoardViewport>
 return <BoardSelectionContext.Provider value={{choose}}><div className={`board-studio ${presentation?'studio board-presentation':''} ${paletteOpen?'':'palette-collapsed'}`} data-revision={revision}>
 <div className="board-heading"><div className="board-title">{presentation?<><Mountain size={23}/><strong>矿大</strong><h2>{boardDisplayName(doc.name)}</h2></>:<><button aria-label="退出大屏编排" onClick={onBack}><ArrowLeft size={16}/></button><input aria-label="大屏方案名称" value={doc.name} onChange={e=>change({...doc,name:e.target.value})}/></>}</div><div className="tool-row">{presentation?<><details className="board-source"><summary aria-label="大屏数据来源" title="数据来源"><Info size={16}/></summary><p>当前使用本地工况、合成记录及概念模型，未接入现场设备。地图来源见地图署名。</p></details><button aria-label="大屏全屏" title="全屏" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setFullscreenError('当前容器不允许全屏，可使用浏览器全屏模式。')}}}><Maximize2 size={16}/></button><button onClick={onBack}><ArrowLeft size={15}/>编排</button></>:<><button aria-label={paletteOpen?'收起组件库':'展开组件库'} title="组件库" onClick={()=>setPaletteOpen(v=>!v)}>{paletteOpen?<PanelLeftClose size={16}/>:<PanelLeftOpen size={16}/>}</button><button aria-label="撤销排版" title="撤销" disabled={!past.current.length||!can('config')} onClick={()=>travel(false)}><Undo2 size={16}/></button><button aria-label="重做排版" title="重做" disabled={!future.current.length||!can('config')} onClick={()=>travel(true)}><Redo2 size={16}/></button><button aria-label="排版设置" title="设置" onClick={()=>setSettings(true)}><Settings2 size={16}/></button><button aria-label="排版历史" title="历史" onClick={()=>setHistoryOpen(true)}><History size={16}/></button><select className="board-ratio-inline" aria-label="大屏比例" value={doc.ratio} onChange={e=>change({...doc,ratio:e.target.value as BoardDocument['ratio']})}><option>16:9</option><option>21:9</option></select><button disabled={!can('config')} onClick={save}><Save size={15}/>{dirty?'保存修改':'保存方案'}</button><button className="primary" onClick={()=>{if(!can('config')||save())onPreview?.()}}><MonitorPlay size={15}/>保存并预览</button></>}</div></div>
 <div className="board-context-bar"><select aria-label="大屏联动设备" value={visibleDevices.some(d=>d.id===state.selectedDevice)?state.selectedDevice:''} onChange={e=>choose(e.target.value)}><option value="">全部设备</option>{visibleDevices.map(d=><option key={d.id} value={d.id}>{d.id} · {d.type}</option>)}</select>{state.selectedDevice&&<button onClick={()=>choose('')} aria-label="清除设备选择">×</button>}<div className="board-context-time"><button aria-label={state.playing?'暂停大屏回放':'播放大屏回放'} onClick={()=>control({playing:!state.playing,frame:state.frame>=120?0:state.frame})}>{state.playing?<Pause size={13}/>:<Play size={13}/>}</button><time>{sceneTime(state.frame)}</time><input aria-label="大屏联动时间" type="range" min="0" max="120" value={state.frame} onChange={e=>{control({frame:+e.target.value,playing:false});if(!presentation)change({...doc,context:{device:state.selectedDevice,frame:+e.target.value}})}}/></div>{!presentation&&<span>{dirty?'未保存修改':'已保存'}</span>}</div>
 {!presentation&&!can('config')&&<div className="role-preview-banner"><span>{state.role} · 只读预览</span><button onClick={()=>control({role:'项目管理员'})}>退出预览并编排</button></div>}
 {(!presentation||doc.pages.length>1)&&<div className="board-pages">{doc.pages.map((p,i)=><button key={p.id} className={i===Math.min(pageIndex,doc.pages.length-1)?'active':''} onClick={()=>setPageIndex(i)}>{pageDisplayName(p.name)}{!presentation&&<small>{p.items.length}</small>}</button>)}{!presentation&&<button disabled={!can('config')} onClick={()=>{const next={id:crypto.randomUUID(),name:`自定义屏 ${doc.pages.length+1}`,items:[],primary:''};change({...doc,pages:[...doc.pages,next]});setPageIndex(doc.pages.length)}}><Plus size={13}/>新增屏页</button>}</div>}
 {(notice||fullscreenError)&&<div className="board-notice" role="status">{fullscreenError||notice}</div>}
 {presentation?<>{grid}</>:<>

 <div className="board-editor"><aside className="board-palette"><div><h3>组件库 <small>{widgetCatalog.length}</small></h3><input placeholder="搜索组件" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="组件分类" value={category} onChange={e=>setCategory(e.target.value)}>{['全部',...widgetCategoryOrder].map(c=><option key={c}>{c}</option>)}</select></div><div className="board-palette-list">{widgetCatalog.filter(w=>(category==='全部'||w.category===category)&&`${w.name}${w.description}`.toLowerCase().includes(query.toLowerCase())).map(w=><article key={w.kind} className={used.has(w.kind)?'used':''} onPointerDown={e=>{if(!(e.target as HTMLElement).closest('button'))start(e,`palette:${w.kind}`)}} onPointerMove={movePointer} onPointerUp={finish} onPointerCancel={()=>drag.current=null}><div className="board-palette-thumb">{w.kind.startsWith('algorithm-')?<AlgorithmCover id={w.kind.slice(10)}/>:<LayoutTemplate size={22}/>}</div><div><strong>{w.name}</strong><small>{w.category}</small></div><button disabled={!can('config')||!used.has(w.kind)&&page.items.length>=PAGE_LIMIT} aria-label={used.has(w.kind)?`取消添加${w.name}`:`添加${w.name}`} onClick={()=>used.has(w.kind)?remove(page.items.find(i=>i.kind===w.kind)!.id):add(w.kind)}>{used.has(w.kind)?<Trash2 size={14}/>:<Plus size={14}/>}</button></article>)}</div><p>{page.items.length>=PAGE_LIMIT?'当前屏 12 项已满，可新建屏页继续添加。':'每项限用一次'}</p></aside><div className="board-edit-main"><div className="board-page-meta"><input aria-label="屏页名称" value={page.name} onChange={e=>setPage({...page,name:e.target.value})}/><span>{page.items.length}/12 项</span></div><div className="board-selection-toolbar" aria-label="所选组件操作"><select aria-label="选择编排组件" value={selectedTile?.item.id||''} onChange={e=>setFocus(e.target.value)}>{!tiles.length&&<option value="">未添加组件</option>}{tiles.map(t=><option key={t.item.id} value={t.item.id}>{widgetCatalog.find(w=>w.kind===t.item.kind)?.name}</option>)}</select><div><button disabled={!selectedTile||!can('config')||selectedTile.item.id===tiles[0]?.item.id} aria-label="前移所选组件" onClick={()=>nudge(selectedTile!.item.id,-1)}><ChevronLeft size={16}/></button><button disabled={!selectedTile||!can('config')||selectedTile.item.id===tiles.at(-1)?.item.id} aria-label="后移所选组件" onClick={()=>nudge(selectedTile!.item.id,1)}><ChevronRight size={16}/></button><button disabled={!selectedTile||!can('config')} onClick={()=>setPage({...page,primary:selectedTile!.item.kind})}><Star size={14}/>主视区</button><button disabled={!selectedTile||!can('config')} onClick={()=>remove(selectedTile!.item.id)}><Trash2 size={14}/>移除</button></div></div>{grid}</div></div></>}
 {settings&&<WorkspaceDrawer title="排版设置" onClose={()=>setSettings(false)}><label className="board-settings-ratio">屏幕比例<select aria-label="目标屏幕比例" value={doc.ratio} disabled={!can('config')} onChange={e=>change({...doc,ratio:e.target.value as BoardDocument['ratio']})}><option>16:9</option><option>21:9</option></select></label><div className="board-template-cards">{Object.keys(boardTemplates).map(n=><button key={n} disabled={!can('config')} onClick={()=>{const p=makePage(n);change({...doc,pages:[...doc.pages,p]});setPageIndex(doc.pages.length);setSettings(false)}}><LayoutTemplate size={24}/><strong>{n}</strong><span>{boardTemplates[n].length} 个组件</span></button>)}</div><small>模板添加为新屏页，原有排版保留。各组件使用预设规格，不开放自由拉伸。</small></WorkspaceDrawer>}
 {historyOpen&&<WorkspaceDrawer title="排版历史" onClose={()=>setHistoryOpen(false)}><div className="board-version-list">{versions.current.length?versions.current.map((v,i)=><button key={i} disabled={!can('config')} onClick={()=>{const next=normalizeBoard(v.doc,valid);if(next){restore(next);setPageIndex(0);setHistoryOpen(false);setNotice('已恢复到草稿，保存后生效')}}}><History size={18}/><span>{v.time}<small>{v.doc.name} · {v.doc.pages.length} 屏</small></span><RotateCcw size={15}/></button>):<p>保存方案后，这里会保留最近 8 个版本。</p>}</div></WorkspaceDrawer>}
 </div></BoardSelectionContext.Provider>
}
