export const businessFields:Record<string,string[]>={
 spatialObjectManager:['空间对象','父级区域','坐标 / 高程','绑定监测点'],multiSourceOverview:['数据源类型','覆盖区域','采集周期','成果索引'],projectSwitcher:['客户项目','项目负责人','区域范围','访问说明'],
 deviceLifecycle:['设备编号','生命周期状态','启用日期','变更原因'],monitorPointBinding:['设备编号','监测点编号','坐标 / 高程','通道对应关系'],channelManager:['通道编号','监测指标 / 单位','采样率 / 量程','标定参数'],gatewayManager:['网关编号','部署位置','固件版本','绑定设备列表'],simCardManager:['ICCID / 设备编号','运营商 / 套餐','到期日期','月流量 / 余额'],firmwareAuth:['设备型号','固件版本','凭证有效期','认证状态说明'],deviceAlarmCenter:['告警设备','维护责任人','告警时间','故障与恢复依据'],remoteControl:['目标设备','控制指令','审批责任人','指令参数'],deviceModelLibrary:['厂家与型号','支持指标','默认采样率','协议与通道模板'],maintenancePlan:['巡检对象','维护责任人','计划日期','巡检内容与备件'],calibrationLedger:['设备 / 标定批次','标定人员','有效日期','标定系数与复核结论'],
 tcpSession:['会话 / 设备','IP 与端口','心跳周期','超时与拆包策略'],mqttSession:['客户端 / 设备','Topic 范围','QoS 等级','会话与回执策略'],httpAccess:['接口路径','调用设备','幂等键规则','签名与限流策略'],fileUploadCenter:['文件 / 数据类型','归属测线','批次日期','校验和与解析说明'],duplicateDisorder:['数据流 / 设备','幂等字段','迟到容忍时长','重复与乱序策略'],rangeDrift:['指标 / 单位','适用设备','有效范围','漂移阈值'],timeSync:['设备编号','时钟源','偏差阈值','校时结果'],storageArchive:['存储分区','冷热级别','保留天数','归档规则'],fileResultCenter:['成果文件','关联算法任务','生成批次','版本与空间范围'],dataExport:['数据对象','导出格式','查询时间窗','筛选条件'],metricDictionary:['指标编码','指标名称 / 单位','有效范围','精度与换算规则'],
 riskRuleCenter:['规则名称','风险等级','持续时间 / 次数','阈值与质量门槛'],riskLevelHistory:['关联风险事件','等级变化','操作时间','变更依据'],notificationCenter:['通知对象','通知渠道','重试次数','消息与回执规则'],emergencyPlan:['应急预案','应急责任组','演练日期','响应措施与复盘'],customerProjectManager:['客户项目','责任单位','联系人','项目实施范围'],sensitiveApproval:['操作对象','审批责任人','提交时间','审批原因与依据'],
 protocolLibrary:['厂家 / 协议名称','适配器版本','支持型号','字段解析规则'],adapterSelfTest:['测试用例名称','目标适配器','预期字段','样例 JSON 报文'],configurationVersion:['配置名称','生效范围','当前版本','配置变更内容'],releaseRollback:['发布对象','灰度范围','观察时长','发布与回滚条件'],serviceHealth:['服务名称','依赖服务','健康检查周期','诊断与恢复策略'],resourceMonitor:['资源对象','监控区域','告警阈值','容量与采样策略'],messageQueueMonitor:['Topic / 消费组','所属链路','积压阈值','重试与回放策略'],openApiMonitor:['API 路径','调用项目','限流阈值','错误重试策略'],shiftHandover:['班次与岗位','交接人员','交接时间','未闭环事项'],acceptanceChecklist:['验收条目','责任人','目标日期','验收证据与问题'],deploymentReadiness:['部署对象','运行环境','检查日期','资源与依赖检查'],deliverableCenter:['交付物名称','版本编号','交付日期','文件与验收说明'],
}
export function businessSamples(kind:string,name:string,fields:string[]){
 const unique:Record<string,string[]>={gatewayManager:['GW-001 / 北帮网关','北帮边坡','FW 1.4.2','GNSS-001 · MS-002 · RADAR-003'],maintenancePlan:['北帮季度巡检','陈工','2026/09/28','供电接头、天线、安装基础'],firmwareAuth:['KD-GNSS G2','FW 2.1.0','2026/12/31','凭证待本地复核'],tcpSession:['GNSS-001 / TCP','127.0.0.1:9001','30 s','超时 90 s / 帧长 256 B'],mqttSession:['GNSS-001','/north/gnss/telemetry','QoS 1','心跳 30 s / 重试 3 次'],httpAccess:['/api/v1/telemetry','GNSS-001','设备编号 + 采样序号','批量 100 条 / 限流 60 次每分钟'],duplicateDisorder:['北帮回传流','设备 + 通道 + 序号','3 s','同键去重 / 迟到窗口重排'],timeSync:['GNSS-001','GNSS PPS','20 ms','偏差超限待核验'],storageArchive:['北帮监测数据','热存储','90 天','冷层保留 365 天'],notificationCenter:['北帮值班组','站内通知','3 次','确认后停止重试'],emergencyPlan:['北帮边坡处置预案','现场值班组','2026/09/30','核查 → 隔离 → 撤离 → 复核'],deviceLifecycle:['GNSS-001','已激活','2026/09/20','入场验收通过'],spatialObjectManager:['北帮 / L01','露天矿区','X 120 / Y 85 / Z 32 m','GNSS-001 · MS-002'],simCardManager:['89860…001 / GNSS-001','中国移动 / 10 GB','2026/12/31','已用 2.8 GB / 剩余 7.2 GB'],channelManager:['GNSS-001 / CH-01','三维位移 / mm','1 Hz / ±100 mm','系数 1.000 / 零偏 0'],remoteControl:['MS-002','采样率调整（模拟）','陈工 → 项目管理员','1000 Hz → 2000 Hz，回执演示'],protocolLibrary:['KD-GNSS / MQTT','adapter-gnss-v1.2','KD-GNSS G2','raw_value → displacement / 1000'],adapterSelfTest:['GNSS 标准报文','adapter-gnss-v1.2','device_id,raw_value','{"device_id":"GNSS-001","raw_value":5800}'],riskRuleCenter:['位移持续加速','橙色候选','15 min / 连续 3 次','位移速率 > 2 mm/h，质量 > 0.8'],resourceMonitor:['演示工作站','Windows 本地','CPU < 80% / 内存 < 85%','硬件配置参考当前交付；不读取真实资源指标'],deploymentReadiness:['矿大演示工作站','Windows 10/11 x64','2026/09/21','WebView2 / 无外网依赖 / 本地文件写入'],releaseRollback:['算法参数配置','北帮 20% 测点','观察 30 min','质量不达标时恢复上一版本']}
 const base=unique[kind]||[`${name} / 北帮`,'项目组','2026/09/21',`${fields[3]}：待专业人员复核`]
 return Array.from({length:3},(_,i)=>base.map((v,j)=>i===0?v:j===0?v.includes('北帮')?v.replaceAll('北帮',['北帮','南帮','东帮'][i]):`${v} / ${String(i+1).padStart(2,'0')}`:v))
}
