import {useEffect,useRef,useState} from 'react'
import * as C from 'cesium'
import 'cesium/Build/Cesium/Widgets/widgets.css'
import {platformFor,platformPosition,observationFrame,platforms} from './sceneCatalog'
import type {Device} from './store'
export interface DEM {bounds:{west:number;east:number;south:number;north:number};width:number;height:number;heights:number[];source:string}
export function demHeight(d:DEM,lon:number,lat:number){const x=Math.max(0,Math.min(d.width-1,(lon-d.bounds.west)/(d.bounds.east-d.bounds.west)*(d.width-1))),y=Math.max(0,Math.min(d.height-1,(d.bounds.north-lat)/(d.bounds.north-d.bounds.south)*(d.height-1))),a=Math.floor(x),b=Math.floor(y),nx=Math.min(a+1,d.width-1),ny=Math.min(b+1,d.height-1),dx=x-a,dy=y-b;return (d.heights[b*d.width+a]*(1-dx)+d.heights[b*d.width+nx]*dx)*(1-dy)+(d.heights[ny*d.width+a]*(1-dx)+d.heights[ny*d.width+nx]*dx)*dy}
export default function CesiumReference({devices,frame,selected,onSelect}:{devices:Device[];frame:number;selected:string;onSelect:(id:string)=>void}){
 const host=useRef<HTMLDivElement>(null),viewer=useRef<C.Viewer|null>(null),data=useRef<DEM|null>(null),latest=useRef({devices,frame,selected,onSelect}),[message,setMessage]=useState('加载本地公开高程…'),[online,setOnline]=useState(false)
 latest.current={devices,frame,selected,onSelect}
 useEffect(()=>{const el=host.current;if(!el)return;let disposed=false,v:C.Viewer|undefined,handler:C.ScreenSpaceEventHandler|undefined;const abort=new AbortController()
  fetch('./scene-assets/baiyun-dem.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('地形文件缺失');return r.json()}).then((dem:DEM)=>{
   if(disposed)return;data.current=dem;const b=dem.bounds,scheme=new C.GeographicTilingScheme(),provider=new C.CustomHeightmapTerrainProvider({width:32,height:32,tilingScheme:scheme,credit:'Mapzen / Tilezen • SRTM/GMTED2010 courtesy of USGS',callback:(x,y,level)=>{const rect=scheme.tileXYToRectangle(x,y,level),h=new Float32Array(1024);for(let row=0;row<32;row++)for(let col=0;col<32;col++)h[row*32+col]=demHeight(dem,C.Math.toDegrees(rect.west+(rect.east-rect.west)*col/31),C.Math.toDegrees(rect.north-(rect.north-rect.south)*row/31));return h}})
   v=new C.Viewer(el,{animation:false,timeline:false,baseLayerPicker:false,baseLayer:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,terrainProvider:provider,requestRenderMode:true,maximumRenderTimeChange:Infinity,contextOptions:{webgl:{alpha:true}}});viewer.current=v;v.resolutionScale=Math.min(devicePixelRatio,1.3);v.scene.backgroundColor=C.Color.fromCssColorString('#0a1724');v.scene.globe.baseColor=C.Color.fromCssColorString('#60736a');v.scene.globe.cartographicLimitRectangle=C.Rectangle.fromDegrees(b.west,b.south,b.east,b.north);v.scene.globe.depthTestAgainstTerrain=true;v.scene.globe.enableLighting=false;v.scene.verticalExaggeration=1;v.scene.globe.showGroundAtmosphere=false;if(v.scene.skyAtmosphere)v.scene.skyAtmosphere.show=false;if(v.scene.skyBox)v.scene.skyBox.show=false;if(v.scene.sun)v.scene.sun.show=false;if(v.scene.moon)v.scene.moon.show=false
   // A hillshade made from the same DEM, not a misregistered satellite photograph.
   const canvas=document.createElement('canvas');canvas.width=dem.width;canvas.height=dem.height;const ctx=canvas.getContext('2d')!,img=ctx.createImageData(dem.width,dem.height);for(let y=0;y<dem.height;y++)for(let x=0;x<dem.width;x++){const idx=y*dem.width+x,h=dem.heights[idx],slope=dem.heights[y*dem.width+Math.max(0,x-1)]-dem.heights[y*dem.width+Math.min(dem.width-1,x+1)],shade=Math.max(.55,Math.min(1.4,.95+slope*.025)),t=(h-1485)/222;img.data.set([Math.min(255,(90+t*67)*shade),Math.min(255,(113+t*47)*shade),Math.min(255,(111+t*29)*shade),255],idx*4)}ctx.putImageData(img,0,0);const image=C.SingleTileImageryProvider.fromUrl(canvas.toDataURL(),{rectangle:C.Rectangle.fromDegrees(b.west,b.south,b.east,b.north),credit:'公开高程着色 / 非卫星影像'});image.then(p=>{if(!disposed){v!.imageryLayers.addImageryProvider(p);v!.scene.requestRender()}}).catch(()=>{})
   v.camera.lookAt(C.Cartesian3.fromDegrees(110,41.8,1600),new C.HeadingPitchRange(C.Math.toRadians(20),C.Math.toRadians(-48),12500));v.camera.lookAtTransform(C.Matrix4.IDENTITY)
   handler=new C.ScreenSpaceEventHandler(v.scene.canvas);handler.setInputAction((e:{position:C.Cartesian2})=>{const picked=v!.scene.pick(e.position);if(picked?.id?.id)latest.current.onSelect(String(picked.id.id))},C.ScreenSpaceEventType.LEFT_CLICK)
   setMessage('白云鄂博周边 · 本地公开高程 · 实际高程比例 · 演示布点')
  }).catch(e=>{if(!disposed)setMessage(`地形加载失败：${String(e.message)}。可切回概念矿区继续演示。`)})
  return()=>{disposed=true;abort.abort();handler?.destroy();if(v&&!v.isDestroyed())v.destroy();viewer.current=null}
 },[])
 useEffect(()=>{const v=viewer.current,d=data.current;if(!v||!d)return;const visible=new Set(devices.map(x=>x.id));for(const entity of [...v.entities.values])if(!visible.has(entity.id))v.entities.remove(entity)
  for(const device of devices){const k=platformFor(device),p=k?platformPosition(k,observationFrame(device,frame)):[device.x*1.65,0,device.y*1.7],lon=110+p[0]/11000,lat=41.8-p[2]/14500,alt=demHeight(d,lon,lat)+(k==='satellite'?1700:k==='drone'?240:20);let entity=v.entities.getById(device.id);if(!entity)entity=v.entities.add({id:device.id,name:device.name,position:C.Cartesian3.fromDegrees(lon,lat,alt),label:{show:!!k||device.id===selected,text:device.id,font:'12px sans-serif',fillColor:C.Color.WHITE,showBackground:true,backgroundColor:C.Color.fromCssColorString('#112c40'),pixelOffset:new C.Cartesian2(0,-32),disableDepthTestDistance:Number.POSITIVE_INFINITY},...(k?{model:{uri:`./scene-assets/${k}.glb`,scale:k==='satellite'?22:10,minimumPixelSize:44,maximumScale:60}}:{point:{pixelSize:9,color:C.Color.fromCssColorString('#87c8e9'),outlineColor:C.Color.WHITE,outlineWidth:1}})});entity.position=new C.ConstantPositionProperty(C.Cartesian3.fromDegrees(lon,lat,alt));if(entity.label)entity.label.show=new C.ConstantProperty(!!k||device.id===selected);if(entity.label)entity.label.backgroundColor=new C.ConstantProperty(C.Color.fromCssColorString(device.id===selected?'#1b58a1':'#112c40'));if(k)entity.orientation=new C.ConstantProperty(C.Transforms.headingPitchRollQuaternion(C.Cartesian3.fromDegrees(lon,lat,alt),new C.HeadingPitchRoll(frame/120*Math.PI*2,0,0)))}v.scene.requestRender()
 },[devices,frame,selected,message])
 useEffect(()=>{const v=viewer.current;if(!v||!online)return;const imagery=new C.UrlTemplateImageryProvider({url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',maximumLevel:17,credit:'© OpenStreetMap contributors — openstreetmap.org/copyright'}),layer=v.imageryLayers.addImageryProvider(imagery);setMessage('在线底图加载中；设备为示意位置，不代表真实部署');const remove=imagery.errorEvent.addEventListener(()=>setMessage('在线底图暂不可用；关闭在线底图可继续查看本地公开高程'));const timer=window.setTimeout(()=>{if(!v.isDestroyed())setMessage(m=>m.includes('暂不可用')?m:'OpenStreetMap 在线参照 / 本地高程 / 演示布点')},3000);return()=>{clearTimeout(timer);remove();if(!v.isDestroyed())v.imageryLayers.remove(layer,true)}},[online])
 return <div className="terrain-reference"><div className="terrain-view" ref={host}/><div className="terrain-caption"><span>{message}</span><label><input type="checkbox" checked={online} onChange={e=>setOnline(e.target.checked)}/>在线道路底图</label></div></div>
}
