export interface Channel {id:string;axis:string;enabled:boolean;source:string;metric:string;unit:string;scale:number;offset:number}
export interface Calibration {id:string;time:string;channel:string;scale:number;offset:number;errorBefore:number;errorAfter:number}
export interface ChannelConfig {channels:Channel[];rate:number;gain:number;trigger:number;calibrations:Calibration[]}
export function defaultChannels(type:string):ChannelConfig{const count=type==='数采板'?8:3,gnss=type==='GNSS';return {channels:Array.from({length:count},(_,i)=>({id:`CH${String(i+1).padStart(2,'0')}`,axis:gnss?['E','N','U'][i]:['X','Y','Z'][i%3],enabled:i<3,source:'',metric:gnss?'位移':'振动幅值',unit:gnss?'mm':'mV',scale:.001,offset:0})),rate:gnss?1:1000,gain:1,trigger:200,calibrations:[]}}
export function validChannelConfig(v:unknown):v is ChannelConfig{const x=v as ChannelConfig;return !!x&&Array.isArray(x.channels)&&x.channels.length>0&&x.channels.length<=32&&x.channels.every(c=>typeof c.id==='string'&&typeof c.axis==='string'&&typeof c.source==='string'&&typeof c.metric==='string'&&typeof c.unit==='string'&&typeof c.enabled==='boolean'&&Number.isFinite(c.scale)&&c.scale>0&&Number.isFinite(c.offset))&&Number.isFinite(x.rate)&&x.rate>0&&x.rate<=100000&&Number.isFinite(x.gain)&&x.gain>0&&x.gain<=128&&Number.isFinite(x.trigger)&&x.trigger>=0&&Array.isArray(x.calibrations)&&x.calibrations.every(c=>typeof c.id==='string'&&typeof c.channel==='string'&&typeof c.time==='string'&&[c.scale,c.offset,c.errorBefore,c.errorAfter].every(Number.isFinite))}
export function channelErrors(c:ChannelConfig){if(!validChannelConfig(c))return ['参数超出有效范围'];const bindings=c.channels.filter(v=>v.enabled&&v.source).map(v=>`${v.source}/${v.axis}`);return [...new Set(bindings.filter((v,i)=>bindings.indexOf(v)!==i))].map(v=>`${v} 重复绑定`)}
export const mappedValue=(raw:number,c:Pick<Channel,'scale'|'offset'>)=>raw*c.scale+c.offset
export function sampleChannel(rate:number,gain:number,axis=0){const count=Math.max(2,Math.min(320,Math.round(rate)));return Array.from({length:count},(_,i)=>{const t=i/Math.max(rate,1);return gain*(Math.sin(t*2*Math.PI*12+axis*.6)*.48+Math.sin(t*2*Math.PI*37)*.17+Math.sin(t*2*Math.PI*6)*.11)*(0.35+Math.exp(-(((i/count-.54)/.17)**2)))})}
export function storageEstimate(c:ChannelConfig){const bytesPerSecond=c.channels.filter(x=>x.enabled).length*c.rate*3;return {bytesPerSecond,megabytesPerDay:bytesPerSecond*86400/1e6}}
export function fitCalibration(raw:number[],reference:number[]){if(raw.length!==reference.length||raw.length<3||![...raw,...reference].every(Number.isFinite))throw Error('标定样本不足');const n=raw.length,mx=raw.reduce((a,b)=>a+b,0)/n,my=reference.reduce((a,b)=>a+b,0)/n,den=raw.reduce((s,x)=>s+(x-mx)**2,0);if(den<1e-12)throw Error('标定输入没有变化');const scale=raw.reduce((s,x,i)=>s+(x-mx)*(reference[i]-my),0)/den,offset=my-scale*mx;if(scale<=0)throw Error('标定系数必须大于零');const error=Math.sqrt(raw.reduce((s,x,i)=>s+(x*scale+offset-reference[i])**2,0)/n);return {scale,offset,error}}
