import {useState} from 'react'
import {Activity,ArrowRight,Check,Download,Save,SlidersHorizontal,Info} from 'lucide-react'
import {useDemo,exportCSV,now,type Device} from './store'
import {useBusinessConfig} from './useBusinessConfig'
import {defaultChannels,validChannelConfig,channelErrors,mappedValue,sampleChannel,storageEstimate,fitCalibration,type Channel,type ChannelConfig} from './channelConfig'
import {WorkspaceDrawer} from './WorkspaceDrawer'
const tabs=['通道配置','指标映射','采样参数','标定记录']
export function SignalTrace({values,color='#8bcbd5',limit}:{values:number[];color?:string;limit?:number}){const max=limit||Math.max(.001,...values.map(Math.abs));return <svg className="business-wave" viewBox="0 0 640 150" role="img" aria-label="采样预览"><path d="M0 75H640" stroke="#a4c6d322"/><polyline points={values.map((v,i)=>`${i/Math.max(1,values.length-1)*640},${75-v/max*60}`).join(' ')} fill="none" stroke={color} strokeWidth="1.8"/></svg>}
export function ChannelWorkspace(){const {visibleDevices,state}=useDemo(),devices=visibleDevices.filter(d=>['GNSS','微震节点','数采板'].includes(d.type)),[selected,setSelected]=useState(state.selectedDevice);const device=devices.find(d=>d.id===selected)||devices[0];return device?<ChannelDevice key={device.id} device={device} devices={devices} onDevice={setSelected}/>:<p>暂无可配置通道</p>}
function ChannelDevice({device,devices,onDevice}:{device:Device;devices:Device[];onDevice:(id:string)=>void}){
 const cfg=useBusinessConfig('channelSettings',device.id,defaultChannels(device.type),'device',validChannelConfig),c=cfg.value,[tab,setTab]=useState(tabs[0]),[selected,setSelected]=useState(c.channels[0].id),[info,setInfo]=useState(false),[batch,setBatch]=useState(''),[zero,setZero]=useState(16),[sensitivity,setSensitivity]=useState(1.045)
 const channel=c.channels.find(v=>v.id===selected)||c.channels[0],errors=channelErrors(c),estimate=storageEstimate(c),change=(patch:Partial<Channel>)=>{cfg.setValue({...c,channels:c.channels.map(v=>v.id===channel.id?{...v,...patch}:v)});cfg.setNotice('')},set=(patch:Partial<ChannelConfig>)=>{cfg.setValue({...c,...patch});cfg.setNotice('')}
 const references=[-2,-1.5,-1,-.5,0,.5,1,1.5,2],raw=references.map((v,i)=>v*1000*sensitivity+zero+Math.sin(i*2.1)*5),fitted=fitCalibration(raw,references),before=raw.map(v=>mappedValue(v,channel)),after=raw.map(v=>v*fitted.scale+fitted.offset),errorBefore=Math.sqrt(before.reduce((s,v,i)=>s+(v-references[i])**2,0)/before.length),activeBatch=c.calibrations.find(v=>v.id===batch),readout=activeBatch||{scale:fitted.scale,offset:fitted.offset,errorBefore,errorAfter:fitted.error}
 const calibrate=()=>{if(errors.length)return;const record={id:crypto.randomUUID(),time:now(),channel:channel.id,scale:fitted.scale,offset:fitted.offset,errorBefore,errorAfter:fitted.error};const next={...c,calibrations:[record,...c.calibrations].slice(0,30),channels:c.channels.map(v=>v.id===channel.id?{...v,scale:fitted.scale,offset:fitted.offset}:v)};cfg.save(next,'保存通道标定');setBatch(record.id)}
 return <section className="business-console channel-console" data-business="channels"><header className="business-console-bar"><select aria-label="通道设备" value={device.id} onChange={e=>onDevice(e.target.value)}>{devices.map(d=><option key={d.id} value={d.id}>{d.id} · {d.type}</option>)}</select><nav>{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav><button aria-label="通道数据与方法" onClick={()=>setInfo(true)}><Info size={16}/></button><button disabled={!cfg.allowed||!!errors.length} onClick={()=>cfg.save()}><Save size={15}/>{cfg.dirty?'保存修改':'保存配置'}</button></header>
 <div className="business-channel-chips">{c.channels.map(v=><button key={v.id} aria-pressed={v.id===channel.id} onClick={()=>setSelected(v.id)}><i className={v.enabled?'online':''}/>{v.id}<small>{v.axis}</small></button>)}</div>
 {tab==='通道配置'&&<div className="business-two-panel" data-view="channel-wiring"><div className="glass-business-panel"><svg className="channel-wiring" viewBox="0 0 700 390" role="img" aria-label="数采通道连接"><rect x="210" y="45" width="280" height="280" rx="22" fill="#44697c22" stroke="#aacddd55"/><rect x="290" y="130" width="120" height="95" rx="10" fill="#163143" stroke="#b5ced366"/><text x="350" y="185" textAnchor="middle" fill="#c7e3ea">{device.id}</text>{c.channels.map((v,i)=>{const left=i%2===0,y=85+Math.floor(i/2)*65;return <g key={v.id} role="button" tabIndex={0} aria-label={`配置${v.id}`} onClick={()=>setSelected(v.id)} onKeyDown={e=>e.key==='Enter'&&setSelected(v.id)}><path d={`M${left?135:565} ${y}H${left?285:415}`} stroke={v.enabled?'#8bd0d1':'#486572'} strokeWidth={v.id===channel.id?3:1} strokeDasharray={v.enabled?undefined:'4 5'}/><rect x={left?25:565} y={y-19} width="110" height="38" rx="12" fill={v.id===channel.id?'#426678':'#17303f'} stroke="#bddbe944"/><text x={left?80:620} y={y+5} textAnchor="middle" fill="#c8e2e7">{v.id} · {v.axis}</text><circle cx={left?285:415} cy={y} r="5" fill={v.enabled?'#9dcdbb':'#6e7986'}/></g>})}</svg></div><div className="glass-business-panel business-editor"><h3>{channel.id}</h3><label>采集状态<button aria-pressed={channel.enabled} disabled={!cfg.allowed} onClick={()=>change({enabled:!channel.enabled})}>{channel.enabled?'已启用':'已停用'}</button></label><label>方向<select value={channel.axis} disabled={!cfg.allowed} onChange={e=>change({axis:e.target.value})}>{['X','Y','Z','E','N','U'].map(v=><option key={v}>{v}</option>)}</select></label><label>关联探头<select value={channel.source} disabled={!cfg.allowed} onChange={e=>change({source:e.target.value})}><option value="">设备本机</option>{devices.filter(d=>d.id!==device.id&&d.type!=='数采板').map(d=><option key={d.id}>{d.id}</option>)}</select></label><div className="business-key-readings"><span><b>{c.channels.filter(v=>v.enabled).length}</b>启用</span><span><b>{c.channels.length}</b>通道</span></div></div></div>}
 {tab==='指标映射'&&<div data-view="channel-mapping" className="glass-business-panel"><div className="mapping-station"><div><small>{channel.id} 原始值</small><strong>1250</strong></div><ArrowRight/><div className="business-editor"><label>系数<input type="number" step="0.0001" value={channel.scale} disabled={!cfg.allowed} onChange={e=>change({scale:Number(e.target.value)})}/></label><label>零点<input type="number" step="0.01" value={channel.offset} disabled={!cfg.allowed} onChange={e=>change({offset:Number(e.target.value)})}/></label></div><ArrowRight/><div><small>{channel.metric}</small><strong>{mappedValue(1250,channel).toFixed(3)} <em>{channel.unit}</em></strong></div></div><div className="business-form-row"><label>指标<select value={channel.metric} disabled={!cfg.allowed} onChange={e=>change({metric:e.target.value,unit:({'位移':'mm','振动幅值':'mV','加速度':'m/s²','电压':'V'} as Record<string,string>)[e.target.value]})}><option>位移</option><option>振动幅值</option><option>加速度</option><option>电压</option></select></label><label>单位<select value={channel.unit} disabled={!cfg.allowed} onChange={e=>change({unit:e.target.value})}>{['mm','mV','m/s²','V'].map(u=><option key={u}>{u}</option>)}</select></label></div><div className="mapping-samples">{[0,500,1250,2500,5000].map(v=><div key={v}><span>{v}</span><ArrowRight size={13}/><strong>{mappedValue(v,channel).toFixed(3)} {channel.unit}</strong></div>)}</div></div>}
 {tab==='采样参数'&&<div className="business-two-panel" data-view="channel-sampling"><div className="glass-business-panel"><div className="business-panel-label"><Activity size={16}/>{channel.id}<span>{c.rate} Hz</span></div><SignalTrace values={sampleChannel(c.rate,c.gain,c.channels.indexOf(channel))} limit={Math.max(1,c.gain)}/><div className="sample-trigger-result"><span>峰值 {Math.max(...sampleChannel(c.rate,c.gain,c.channels.indexOf(channel)).map(Math.abs)).toFixed(3)} mV</span><span>越阈 {sampleChannel(c.rate,c.gain,c.channels.indexOf(channel)).filter(v=>Math.abs(v)*1000>c.trigger).length} 点</span></div><div className="sample-clock" aria-label="采样间隔">{Array.from({length:Math.min(50,Math.max(2,Math.round(c.rate/50)))},(_,i)=><i key={i}/>)}</div><div className="business-key-readings"><span><b>{(1000/c.rate).toFixed(2)}</b>ms / 点</span><span><b>{(estimate.bytesPerSecond/1000).toFixed(1)}</b>kB/s</span><span><b>{estimate.megabytesPerDay.toFixed(1)}</b>MB / 天</span></div></div><div className="glass-business-panel business-editor"><label>采样率<select value={c.rate} disabled={!cfg.allowed} onChange={e=>set({rate:Number(e.target.value)})}>{[1,50,100,250,500,1000,2000,4000].map(v=><option key={v} value={v}>{v} Hz</option>)}</select></label><label>增益<select value={c.gain} disabled={!cfg.allowed} onChange={e=>set({gain:Number(e.target.value)})}>{[1,2,4,8,16].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><label>触发阈值 / μV<input type="number" min="0" max="10000" value={c.trigger} disabled={!cfg.allowed} onChange={e=>set({trigger:Number(e.target.value)})}/></label><small>24 bit · {channel.enabled?'采集开启':'通道停用'}</small></div></div>}
 {tab==='标定记录'&&<div data-view="channel-calibration" className="business-two-panel"><div className="glass-business-panel"><div className="business-panel-label">{channel.id}<span>标定样本</span><select aria-label="标定批次" value={batch} onChange={e=>setBatch(e.target.value)}><option value="">当前样本</option>{c.calibrations.map(v=><option key={v.id} value={v.id}>{v.time} / {v.channel}</option>)}</select></div>{!activeBatch?<><div className="calibration-overlay"><SignalTrace values={before} color="#d8ac78" limit={4.2}/><SignalTrace values={after} limit={4.2}/></div><div className="business-form-row"><label>零点偏移<input type="number" min="-1000" max="1000" value={zero} onChange={e=>setZero(Math.max(-1000,Math.min(1000,Number(e.target.value))))}/></label><label>灵敏度<input type="number" min="0.5" max="2" step="0.005" value={sensitivity} onChange={e=>setSensitivity(Math.max(.5,Math.min(2,Number(e.target.value))))}/></label></div></>:<div className="calibration-comparison"><span>标定前<i style={{width:'100%'}}/>{readout.errorBefore.toFixed(5)}</span><span>标定后<i style={{width:`${Math.max(2,readout.errorAfter/Math.max(.00001,readout.errorBefore)*100)}%`}}/>{readout.errorAfter.toFixed(5)}</span></div>}<div className="business-key-readings"><span><b>{readout.errorBefore.toFixed(4)}</b>标定前 RMSE</span><span><b>{readout.errorAfter.toFixed(4)}</b>标定后 RMSE</span></div></div><div className="glass-business-panel business-editor"><h3>线性标定</h3><label>系数<strong>{readout.scale.toFixed(7)}</strong></label><label>零点<strong>{readout.offset.toFixed(5)}</strong></label><button disabled={!cfg.allowed||!!activeBatch||!!errors.length} onClick={calibrate}><Check size={15}/>应用并留存</button><button onClick={()=>exportCSV(`${device.id}-标定.csv`,['时间','通道','系数','零点','标定前RMSE','标定后RMSE'],c.calibrations.map(v=>[v.time,v.channel,v.scale,v.offset,v.errorBefore,v.errorAfter]))}><Download size={15}/>导出记录</button><span>{c.calibrations.length} 次标定</span></div></div>}
 <footer className="business-console-status" role="status"><span>{errors.join('；')||cfg.notice||(cfg.dirty?'未保存修改':`V${cfg.version||1}`)}</span><span>{device.status}</span></footer>{info&&<WorkspaceDrawer title="通道数据与方法" onClose={()=>setInfo(false)}><p>通道配置保存在本机，不向硬件下发。波形为确定性合成样本；线性标定使用当前零点与灵敏度生成的样本，按最小二乘拟合，不代表硬件已完成实际标定。存储估算按 24 bit、启用通道和采样率计算，不含协议开销。</p></WorkspaceDrawer>}</section>
}
