import {useMemo,useState} from 'react'
import {ArrowRight,Radio,Network,Database,Workflow,FileCheck2,ShieldCheck} from 'lucide-react'
import {useDemo,PacketData} from './store'
import {historicalDevices,frameTime,type Packet} from './telemetry'
import {moduleCatalog} from '../data/catalog'
import {goWorkspace} from './navigation'
import {DataSignalPanel} from './DataSignalPanel'

export const dataStageKinds=['capture','transport','mapping','quality','storage','input'] as const
export function DataStageView({stage,packet,onDetail}:{stage:number;packet?:Packet;onDetail:()=>void}){
 const {state,visibleDevices}=useDemo(),[point,setPoint]=useState(60)
 const series=useMemo(()=>Array.from({length:61},(_,i)=>PacketData(historicalDevices(visibleDevices,i*2),i*2,state.mapping).find(p=>p.device===packet?.device)).filter((p):p is Packet=>!!p),[visibleDevices,packet?.device,state.mapping])
 if(!packet)return <div className="empty">暂无记录</div>
 if(stage===0)return <DataSignalPanel deviceId={packet.device}/>
 const selected=series[point]||packet,online=packet.status!=='中断',valid=packet.status==='已入库',tasks=state.tasks.filter(t=>t.source?.deviceId===packet.device),buckets=Array.from({length:12},(_,i)=>series.filter(p=>p.frame>=i*10&&p.frame<(i+1)*10+(i===11?1:0))),good=series.filter(p=>p.status==='已入库').length
 return <section className="data-stage-view" data-stage-view={dataStageKinds[stage]}><header><strong>{packet.device}</strong><span className={`status ${valid?'ok':'warn'}`}>{packet.status}</span><button aria-label="查看当前记录详情" onClick={onDetail}>详情<ArrowRight size={14}/></button></header>
 {stage===1&&<><div className={`transport-scene ${online?'':'is-offline'}`}><div className="transport-node"><Radio size={37}/><b>{packet.device}</b><span>{online?'已连接':'已断开'}</span></div><div className="transport-link"><i/><span>{packet.protocol}</span></div><div className="transport-node"><Network size={40}/><b>网关</b><span>{online?'已接收':'等待重连'}</span></div><div className="transport-link"><i/><span>{packet.delay} s</span></div><div className="transport-node"><Database size={36}/><b>{valid?'已入库':online?'隔离区':'待回传'}</b><span>{frameTime(packet.frame)}</span></div></div><div className="transport-metrics"><button onClick={onDetail}><small>帧序号</small><b>{packet.frame}</b></button><button onClick={onDetail}><small>当前延迟</small><b>{packet.delay}<em>s</em></b></button><button onClick={()=>goWorkspace({page:'workspace',id:'returnLinkTopology',device:packet.device})}><small>链路详情</small><Network size={24}/></button></div></>}
 {stage===2&&<><div className="mapping-stage"><button onClick={onDetail}><small>原始值</small><strong>{packet.raw}</strong></button><div className="mapping-transform"><span>÷ 1000</span><ArrowRight size={28}/><span>× {state.mapping}</span></div><button onClick={onDetail}><small>{packet.metric}</small><strong>{packet.value}<em>{packet.unit}</em></strong></button></div><div className="mapping-field-cards">{[['device_id',packet.device,'设备'],['seq',String(packet.frame),'采样帧'],['quality',packet.status,'处理状态']].map(([field,value,name])=><button key={field} onClick={onDetail}><small>{field}</small><ArrowRight size={15}/><span>{name}</span><b>{value}</b></button>)}</div></>}
 {stage===3&&<><div className="quality-summary"><ShieldCheck size={36}/><strong>{Math.round(good/Math.max(1,series.length)*100)}<small>%</small></strong><span>完整率</span></div><div className="quality-time-grid" aria-label="历史记录质量">{series.map((p,i)=><button key={p.id} aria-label={`${frameTime(p.frame)} ${p.status}`} aria-pressed={point===i} className={p.status==='已入库'?'good':p.status==='中断'?'lost':'isolated'} title={`${frameTime(p.frame)} · ${p.status}`} onClick={()=>setPoint(i)}><i/></button>)}</div><div className="quality-axis"><span>09:00</span><span>09:30</span><span>10:00</span></div><div className="quality-selected"><time>{frameTime(selected.frame)}</time><span className={selected.status==='已入库'?'ok':'warn'}>{selected.status}</span><span>{selected.value} {selected.unit}</span><button onClick={()=>goWorkspace({page:'trace',device:packet.device,frame:String(selected.frame)})}>回溯<ArrowRight size={13}/></button></div><div className="quality-legend"><span><i className="good"/>入库</span><span><i className="isolated"/>隔离</span><span><i className="lost"/>中断</span></div></>}
 {stage===4&&<><div className="storage-stage"><div className="storage-stat"><Database size={38}/><strong>{good}<small>条</small></strong><span>已入库</span></div><div className="storage-bars" aria-label="每五分钟入库记录">{buckets.map((rows,i)=>{const count=rows.filter(p=>p.status==='已入库').length;return <button key={i} aria-label={`${i*5}至${(i+1)*5}分钟，${count}条`} onClick={()=>goWorkspace({page:'trace',device:packet.device,frame:String(i*10)})}><span>{count}</span><i style={{height:Math.max(3,count*22)}}/><small>{String(i*5).padStart(2,'0')}</small></button>})}</div></div><div className="storage-actions"><button onClick={()=>goWorkspace({page:'trace',device:packet.device})}>历史索引<ArrowRight size={14}/></button><button onClick={onDetail}>当前记录<FileCheck2 size={14}/></button></div></>}
 {stage===5&&<><div className="algorithm-input-link"><div><Database size={29}/><b>{packet.device}</b><small>F{packet.frame}</small></div><ArrowRight size={24}/><div><Workflow size={32}/><b>{tasks.length} 项任务</b><small>{valid?'可作为输入':'待恢复数据'}</small></div><button onClick={()=>goWorkspace({page:'algorithm',device:packet.device})}>选择算法<ArrowRight size={15}/></button></div><div className="input-task-grid">{tasks.slice(0,6).map(t=><button key={t.id} onClick={()=>goWorkspace({page:'trace',task:t.id,device:packet.device,tab:'成果证据链'})}><Workflow size={20}/><strong>{moduleCatalog.find(a=>a.id===t.algorithm)?.name||t.algorithm}</strong><span>{t.id}</span><small>{t.status}</small></button>)}</div>{!tasks.length&&<div className="empty">暂无关联任务</div>}</>}
 </section>
}
