import {RecordSummary} from './RecordSummary'
import {useState} from 'react'
import {useDemo,PacketData,type Device} from './store'
import {AnalysisFigure} from './AnalysisFigure'
import {historicalDevices} from './telemetry'
export function DataSignalPanel({deviceId,replayFrame,onFrame,sampleDevices,mapping}: {deviceId?:string;replayFrame?:number;onFrame?:(frame:number)=>void;sampleDevices?:Device[];mapping?:number}){
 const {state,visibleDevices}=useDemo(),[tab,setTab]=useState('曲线'),[windowSize,setWindowSize]=useState(60),[cursor,setCursor]=useState(-1)
 const device=visibleDevices.find(d=>d.id===deviceId),scope=sampleDevices||visibleDevices,scale=mapping??state.mapping,frame=replayFrame??state.frame
 if(!device)return null
 const start=windowSize===60?0:60-windowSize,frames=Array.from({length:windowSize+1},(_,i)=>(start+i)*2),series=frames.map(f=>PacketData(historicalDevices(scope,f),f,scale).find(p=>p.device===device.id)!),current=PacketData(replayFrame===undefined?[device]:historicalDevices(scope,frame).filter(d=>d.id===device.id),frame,scale)[0]
 if(!current||series.some(p=>!p))return null
 const values=series.flatMap(p=>[p.value,p.raw/1000]).filter(Number.isFinite),lo=Math.min(0,...values),hi=Math.max(1,...values)*1.1
 const selectedCursor=cursor>=0?cursor:Math.max(0,Math.min(1,(frame/2-start)/windowSize))
 return <section className="data-signal-panel"><header><div><h3>{device.id} · {current.metric}</h3></div><div><strong>{current.status==='中断'?'—':current.value}<small>{current.unit}</small></strong><select aria-label="曲线时间范围" value={windowSize} onChange={e=>{setWindowSize(+e.target.value);setCursor(-1)}}><option value="60">全部 60 min</option><option value="30">后 30 min</option><option value="15">后 15 min</option></select></div></header>
 <div className="glass-data-plot">{tab==='曲线'||tab==='连续性'?<AnalysisFigure key={`${device.id}-${tab}-${windowSize}`} cursor={selectedCursor} onCursor={setCursor} onPick={n=>onFrame?.(Math.round((start+n*windowSize)*2))} figure={tab==='曲线'?{kind:'lines',title:'原值与标定结果',x:'场景时间 / min',y:current.unit,range:[start,60,lo,hi],lines:[series.map(p=>p.status==='中断'?NaN:p.raw/1000),series.map(p=>p.status==='已入库'?p.value:NaN)],labels:['归一化原值','标定结果']}:{kind:'heat',title:'回传连续性',x:'场景时间 / min',y:'链路',matrix:[series.map(p=>p.status==='中断'?0:p.status==='解析失败'?.5:1)],range:[start,60,0,1],labels:['0 中断','0.5 隔离','1 已入库']}}/>:tab==='字段对照'?<div className="glass-data-fields"><table><thead><tr><th>原始字段</th><th>原值</th><th>标准字段</th><th>结果</th></tr></thead><tbody><tr><td>device_id</td><td>{current.device}</td><td>设备</td><td>{device.name}</td></tr><tr><td>seq</td><td>{current.frame}</td><td>采样帧</td><td>{current.frame}</td></tr><tr><td>raw_value</td><td>{current.raw}</td><td>{current.metric}</td><td>{current.value} {current.unit}</td></tr><tr><td>quality</td><td>{current.status}</td><td>处置</td><td>{current.status==='已入库'?'标准存储':'隔离'}</td></tr></tbody></table><div className="glass-formula"><span>{current.raw}</span><small>÷ 1000 × {scale}</small><strong>{current.value} {current.unit}</strong></div></div>:<div className="glass-data-log"><p><span>01</span>采集 <b>{current.device}</b> <code>F{current.frame}</code></p><p><span>02</span>回传 <b>{current.protocol}</b> <code>{current.delay}</code></p><p><span>03</span>标定 <b>× {scale}</b> <code>{current.metric}</code></p><p><span>04</span>质量 <b>{current.status}</b></p><RecordSummary value={current}/></div>}</div>
 <div className="glass-view-tabs" role="tablist" aria-label="数据图面">{['曲线','连续性','字段对照','处理日志'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div></section>
}
