import {useEffect,useMemo,useState} from 'react'
import {ArrowUpRight,Download,Play,Pause,History,Radio,Activity} from 'lucide-react'
import {useDemo,seedDevices,PacketData,exportFile,type Device} from './store'
import {seedAcquisitionDevices} from './hardware'
import {seedPlatformDevices} from './sceneCatalog'
import {frameTime,historicalDevices,replayEvents} from './telemetry'
import {goWorkspace} from './navigation'

export function DeviceHistory({device}:{device:Device}){
 const {state}=useDemo(),[frame,setFrame]=useState(36),[playing,setPlaying]=useState(false),[snapshot,setSnapshot]=useState('')
 const base=useMemo(()=>[...seedDevices(),...seedAcquisitionDevices(),...seedPlatformDevices()],[])
 const historic=useMemo(()=>Array.from({length:121},(_,i)=>{const d=historicalDevices(base,i).find(d=>d.id===device.id)||device;return {device:d,packet:PacketData([d],i,1)[0]}}),[base,device])
 const snapshots=state.history.filter(s=>s.devices.some(d=>d.id===device.id)),archive=snapshots.find(s=>s.id===snapshot)
 const current=archive?.devices.find(d=>d.id===device.id)||historic[frame].device,packet=archive?.packets.find(p=>p.device===device.id)||historic[frame].packet
 const events=replayEvents.filter(e=>[0,112].includes(e.frame)||device.id===base[0].id&&[40,56,70].includes(e.frame)||device.id===base[1].id&&[78,90].includes(e.frame))
 const tasks=state.tasks.filter(t=>t.source?.deviceId===device.id),audit=state.audit.filter(a=>a.object===device.id)
 useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setFrame(f=>{if(f>=120){setPlaying(false);return 120}return f+1}),400);return()=>clearInterval(timer)},[playing])
 const values=historic.map(h=>h.packet.value),min=Math.min(...values),span=Math.max(.001,Math.max(...values)-min),xy=values.map((v,i)=>`${30+i*5.25},${170-(v-min)/span*128}`).join(' ')
 return <section className="device-history-panel"><header><div><History size={16}/><strong>历史与证据</strong></div><select aria-label="设备历史来源" value={snapshot} onChange={e=>{setSnapshot(e.target.value);setPlaying(false)}}><option value="">内置历史回放</option>{snapshots.map(s=><option key={s.id} value={s.id}>{s.time} · {s.label}</option>)}</select><button onClick={()=>exportFile(`${device.id}-历史证据.json`,JSON.stringify({device:device.id,source:archive?'本地操作快照':'内置历史工况',snapshot:archive||historic[frame],tasks,audit},null,2))}><Download size={15}/>证据包</button><button onClick={()=>goWorkspace({page:'trace',device:device.id,frame:String(archive?.frame??frame),snapshot:archive?.id})}>完整回溯<ArrowUpRight size={14}/></button></header>
 <div className="device-history-body"><div className="device-history-chart"><div><span>{packet.metric}</span><strong>{packet.value}<small>{packet.unit}</small></strong></div>{archive?<div className="device-frozen-evidence"><History size={32}/><strong>已冻结快照</strong><span>{archive.time}</span><small>此记录为单个时刻，不拼接为连续趋势</small></div>:<svg viewBox="0 0 690 200" aria-label="设备历史趋势"><defs><linearGradient id="device-history-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#89cad8" stopOpacity=".25"/><stop offset="1" stopColor="#89cad8" stopOpacity="0"/></linearGradient></defs>{[45,85,125,170].map(y=><path key={y} d={`M30 ${y}H660`} stroke="#adcbdc" strokeOpacity=".1"/>)}<path d={`M30 180L${xy.replaceAll(' ', 'L')}L660 180Z`} fill="url(#device-history-fill)"/><polyline points={xy} fill="none" stroke="#9dd6df" strokeWidth="2"/>{!archive&&<><path d={`M${30+frame*5.25} 28V181`} stroke="#e5c496" strokeDasharray="4 5"/><circle cx={30+frame*5.25} cy={170-(values[frame]-min)/span*128} r="5" fill="#ecd1ad"/></>}<text x="30" y="199">09:00</text><text x="620" y="199">10:00</text></svg>}<div className="device-history-player"><button disabled={!!archive} aria-label={playing?'暂停设备历史':'播放设备历史'} onClick={()=>{if(frame===120)setFrame(0);setPlaying(v=>!v)}}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><input aria-label="设备历史时刻" type="range" min="0" max="120" value={archive?.frame??frame} disabled={!!archive} onChange={e=>{setFrame(+e.target.value);setPlaying(false)}}/><time>{frameTime(archive?.frame??frame)}</time></div></div>
 <aside className="device-history-evidence"><div><Radio size={17}/><span>设备状态</span><strong>{current.status}</strong></div><div><Activity size={17}/><span>数据状态</span><strong>{packet.status}</strong></div><div><span>关联成果</span><strong>{tasks.length}</strong></div><div><span>维护记录</span><strong>{audit.length}</strong></div><small>{archive?archive.time:'内置历史工况 · 非现场记录'}</small></aside></div>
 <div className="device-history-events">{events.map(e=><button key={e.frame} aria-pressed={!archive&&frame===e.frame} onClick={()=>{setSnapshot('');setFrame(e.frame);setPlaying(false)}}><time>{frameTime(e.frame)}</time><span>{e.title}</span></button>)}</div></section>
}
