import { useDemo, PacketData } from './store'
import { hardwareModels, sensorFamily, type SensorFamily } from './hardware'
import { SensorScene } from './SensorScene'
export function HardwareSummary({family,onOpen}:{family:SensorFamily;onOpen:()=>void}){
 const {visibleDevices}=useDemo(),device=visibleDevices.find(d=>sensorFamily(d)===family&&(family!=='gnss'||d.type==='GNSS')),model=hardwareModels[family]
 return <div className="hardware-summary"><div className="hardware-summary-visual" data-widget-interactive><SensorScene family={family} compact thumbnail onSelect={onOpen}/></div><button className="hardware-summary-data" onClick={onOpen}><strong>{device?.id||'暂无设备'}</strong><span className={device?.status==='在线'?'ok':'warn'}>{device?.status}</span><small>{family==='micro'?'X / Y / Z 三分量':family==='daq'?'8 路同步采样':'多星座 / 定位授时'}</small><small>{family==='micro'?'有线差分':family==='daq'?'24 V / Ethernet':'后备电量 '+device?.battery+'%'}</small><em>{model.parts.length} 个部件 · 拆解查看 ↗</em></button></div>
}
export function DeviceSummary({kind,onOpen}:{kind:string;onOpen:()=>void}){
 const {state,visibleDevices}=useDemo(),online=visibleDevices.filter(d=>d.status==='在线').length,off=visibleDevices.filter(d=>d.status==='离线').length,parts=visibleDevices.flatMap(d=>Object.entries(d.parts||{}).map(([part,status])=>({device:d.id,part,status}))),packets=PacketData(visibleDevices,state.frame,state.mapping)
 if(kind==='channelManager')return <div className="channel-summary"><div className="compact-metrics"><span>采集板 <b>{visibleDevices.filter(d=>d.type==='数采板').length}</b></span><span>采样 <b>2 kHz</b></span><span>同步 <b>PPS</b></span></div><div className="channel-summary-grid">{Array.from({length:8},(_,i)=><button key={i} onClick={onOpen}><small>CH-{i+1}</small><svg viewBox="0 0 80 30"><path d={Array.from({length:40},(_,x)=>`${x?'L':'M'}${x*2} ${15+Math.sin(x*.6+i)*Math.exp(-Math.pow((x-20)/12,2))*11}`).join(' ')} fill="none" stroke="currentColor"/></svg><em>正常采样</em></button>)}</div></div>
 if(kind==='networkMonitor')return <div className="network-summary"><div className="mini-pipeline">{['设备','边缘网关','平台'].map(n=><button key={n} onClick={onOpen}>{n}</button>)}</div><div className="compact-metrics"><span>正常链路 <b>{online}</b></span><span>中断 <b>{off}</b></span><span>入库 <b>{packets.filter(p=>p.status==='已入库').length}</b></span></div><button onClick={onOpen} className="summary-text-link">查看心跳与通信记录 ↗</button></div>
 if(kind==='hardwareHealth')return <div className="health-summary"><div className="compact-metrics"><span>故障部件 <b>{parts.length}</b></span><span>待维护设备 <b>{visibleDevices.filter(d=>d.status==='待维护').length}</b></span></div><div className="mini-table">{(parts.length?parts.slice(0,3):visibleDevices.filter(d=>d.type==='GNSS'||d.type==='数采板').slice(0,3).map(d=>({device:d.id,part:'power',status:`后备电量 ${d.battery}%`}))).map(p=><button key={p.device+p.part} onClick={onOpen}><b>{p.device}</b><em>{p.status}</em></button>)}</div></div>
 if(kind==='maintenancePlan')return <div className="maintenance-summary"><div className="compact-metrics"><span>维护对象 <b>{visibleDevices.filter(d=>d.status!=='在线').length}</b></span><span>操作记录 <b>{state.audit.filter(a=>visibleDevices.some(d=>d.id===a.object)).length}</b></span></div><div className="mini-table">{visibleDevices.filter(d=>d.status!=='在线').slice(0,3).map(d=><button key={d.id} onClick={onOpen}><b>{d.id}</b><em className="warn">{d.status} · 待核查</em></button>)}</div><button className="summary-text-link" onClick={onOpen}>查看巡检与维护计划 ↗</button></div>
 if(['deviceOnline','deviceDonut','deviceHealth','offlineAnalysis'].includes(kind))return <div className="status-summary"><div className="status-triplet"><button onClick={onOpen}><strong>{online}</strong><small>在线</small></button><button onClick={onOpen}><strong className="warn">{off}</strong><small>离线</small></button><button onClick={onOpen}><strong>{visibleDevices.length-online-off}</strong><small>待维护</small></button></div><div className="mini-table">{visibleDevices.filter(d=>d.status!=='在线').slice(0,2).map(d=><button key={d.id} onClick={onOpen}><b>{d.id}</b><em>{d.status}</em></button>)}</div></div>
 return <><div className="compact-metrics"><span>建档 <b>{visibleDevices.length}</b></span><span>在线 <b>{online}</b></span><span>区域 <b>{new Set(visibleDevices.map(d=>d.area)).size}</b></span></div><div className="mini-table">{visibleDevices.slice(0,4).map(d=><button key={d.id} onClick={onOpen}><b>{d.id}</b><span>{d.type}</span><em className={d.status==='在线'?'ok':'warn'}>{d.status}</em></button>)}</div></>
}
