import {orbitSpeed,frameSeconds,getRotationMode} from './sceneMotion'
import { useEffect, useRef, useState } from 'react'
import * as T from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { createDeviceModel, disposeScene } from './threeModels'
import { makeMine, mineHeight } from './mineGeometry'
import {terrainContours} from './terrainContours'
import {makeCinematicTerrain,cinematicHeight} from './cinematicTerrain'
import { platformFor, platformPosition, observationFrame, platforms, type PlatformKind } from './sceneCatalog'
import {EquipmentIcon} from './WidgetSummary'
import type { Device } from './store'
export interface SceneLayers { paths:boolean; underground:boolean; coverage:boolean; sensors:boolean }
export function MineScene({devices,frame,selected,onSelect,layers,focus=0,view='orbit',compact=false,cinematic=false,terrainStyle='natural',auto=true,onInteraction}:{devices:Device[];frame:number;selected:string;onSelect:(id:string)=>void;layers:SceneLayers;focus?:number;view?:'orbit'|'feed';compact?:boolean;cinematic?:boolean;terrainStyle?:'natural'|'elevation';auto?:boolean;onInteraction?:()=>void}){
 const host=useRef<HTMLDivElement>(null),labels=useRef<Map<string,HTMLButtonElement>>(new Map()),live=useRef({devices,frame,selected,onSelect,layers,focus,auto,onInteraction}),[failed,setFailed]=useState(false);live.current={devices,frame,selected,onSelect,layers,focus,auto,onInteraction}
 const ids=devices.map(d=>d.id).join('|')
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}
  renderer.setPixelRatio(Math.min(devicePixelRatio,compact?1.3:2));renderer.setClearColor(cinematic?'#101f29':'#0a1724');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=!compact;renderer.shadowMap.type=T.PCFShadowMap;el.prepend(renderer.domElement)
  const scene=new T.Scene();scene.fog=new T.FogExp2('#0a1724',.00072);scene.add(new T.HemisphereLight('#c8e0fa','#667675',1.8));const key=new T.DirectionalLight('#e9ebd7',3.1);key.position.set(-170,350,140);key.castShadow=!compact;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-750;key.shadow.camera.right=750;key.shadow.camera.top=750;key.shadow.camera.bottom=-750;key.shadow.camera.far=1600;key.shadow.normalBias=1.7;key.shadow.bias=-.0005;scene.add(key);const fill=new T.DirectionalLight('#5f94bb',1.5);fill.position.set(150,150,-170);scene.add(fill)
  const camera=new T.PerspectiveCamera(view==='feed'?49:40,1,1,3500);camera.position.set(525,440,615);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,-10,0);controls.enableDamping=true;controls.autoRotateSpeed=orbitSpeed('terrain');controls.maxPolarAngle=Math.PI*.48;controls.minDistance=180;controls.maxDistance=1300;controls.enabled=view==='orbit';controls.enableZoom=false;renderer.domElement.addEventListener('wheel',e=>{controls.enableZoom=!compact&&e.ctrlKey},{capture:true,passive:true})
  if(cinematic){scene.fog=new T.FogExp2('#101f29',.00065);key.color.set('#f2ead6');key.intensity=2.7;fill.intensity=.95;key.position.set(-250,300,-220);camera.position.set(590,480,660);controls.target.set(-35,-4,-20);controls.minDistance=220;controls.maxDistance=1000;controls.addEventListener('start',()=>live.current.onInteraction?.())}
  const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)')
  const heightAt=cinematic?cinematicHeight:mineHeight
  const mine=cinematic?makeCinematicTerrain(compact,terrainStyle):makeMine();scene.add(mine.root);if(!cinematic){const floor=new T.GridHelper(1600,40,'#244257','#182e40');floor.position.y=-154;scene.add(floor)}
  if(cinematic&&terrainStyle==='elevation'){const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(terrainContours(compact?28:16),3));const contours=new T.LineSegments(geometry,new T.LineBasicMaterial({color:'#cfeced',transparent:true,opacity:.24,depthWrite:false}));scene.add(contours)}
  const pathGroup=new T.Group(),coverage=new T.Group();scene.add(pathGroup,coverage)
  for(const k of ['drone','rover','satellite'] as PlatformKind[]){const pts=Array.from({length:121},(_,i)=>{const p=platformPosition(k,i);if(k==='rover')p[1]=heightAt(p[0],p[2])+7;return new T.Vector3(...p)});pathGroup.add(new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineDashedMaterial({color:k==='satellite'?'#7285a2':k==='drone'?'#7dbde0':'#e1b774',dashSize:6,gapSize:4,transparent:true,opacity:.7})));(pathGroup.children.at(-1) as T.Line).computeLineDistances()}
  const spots=new Map<string,T.Object3D>(),models=new Map<string,ReturnType<typeof createDeviceModel>>();devices.forEach(d=>{const family=platformFor(d);let marker:T.Object3D;if(family){const m=createDeviceModel(family);models.set(d.id,m);marker=m.root;marker.scale.setScalar(family==='satellite'?8:family==='deep'?7:5.5)}else{const g=new T.Group(),pole=new T.Mesh(new T.CylinderGeometry(1,1,13,8),new T.MeshStandardMaterial({color:'#bacfda'}));pole.position.y=6.5;g.add(pole);const head=new T.Mesh(new T.CylinderGeometry(3.4,3.4,1.8,16),new T.MeshStandardMaterial({color:d.status==='在线'?'#a3cfec':'#d9a86b',emissive:d.status==='在线'?'#244f70':'#624529'}));head.position.y=14;g.add(head);marker=g}marker.userData.device=d.id;marker.traverse(o=>o.userData.device=d.id);spots.set(d.id,marker);scene.add(marker)})
  const ring=new T.Mesh(new T.RingGeometry(12,13.5,64),new T.MeshBasicMaterial({color:'#86c8ec',side:T.DoubleSide,transparent:true,opacity:.85}));ring.rotation.x=-Math.PI/2;scene.add(ring)
  const footprint=new T.Mesh(new T.CircleGeometry(62,64,0,Math.PI*.67),new T.MeshBasicMaterial({color:'#dfaf72',transparent:true,opacity:.24,side:T.DoubleSide,depthWrite:false}));footprint.rotation.x=-Math.PI/2;coverage.add(footprint)
  const aerial=new T.Mesh(new T.ConeGeometry(58,130,4,1,true),new T.MeshBasicMaterial({color:'#6dbbd6',transparent:true,opacity:.09,side:T.DoubleSide,depthWrite:false}));coverage.add(aerial)
  const ray=new T.Raycaster(),pointer=new T.Vector2(),project=new T.Vector3(),focusTarget=new T.Vector3(),focusCamera=new T.Vector3();let down=[0,0],raf=0,last=0,visible=true,seenFocus=-1,displayFrame=live.current.frame,focusing=false
  const observer=new IntersectionObserver(e=>{visible=e[0].isIntersecting});observer.observe(el)
  const resize=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}});resize.observe(el)
  const pd=(e:PointerEvent)=>down=[e.clientX,e.clientY];const pu=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=el.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects([...spots.values()],true)[0];if(hit)live.current.onSelect(hit.object.userData.device)};renderer.domElement.addEventListener('pointerdown',pd);renderer.domElement.addEventListener('pointerup',pu)
  const tick=(time:number)=>{raf=requestAnimationFrame(tick);if(!visible||document.hidden||time-last<32)return;const delta=time-last;last=time;const v=live.current;displayFrame=Math.abs(v.frame-displayFrame)>4?v.frame:displayFrame+(v.frame-displayFrame)*.2;pathGroup.visible=v.layers.paths;coverage.visible=v.layers.coverage;mine.events.visible=v.layers.underground;mine.strata.visible=v.layers.underground;(mine.terrain.material as T.MeshStandardMaterial).transparent=v.layers.underground;(mine.terrain.material as T.MeshStandardMaterial).opacity=v.layers.underground?.36:1
   if('benches' in mine&&mine.benches instanceof T.Group)mine.benches.traverse(o=>{if(o instanceof T.Mesh){const material=o.material as T.MeshStandardMaterial;material.transparent=v.layers.underground;material.opacity=v.layers.underground?.15:1;material.depthWrite=!v.layers.underground}})
   v.devices.forEach(d=>{const k=platformFor(d),m=spots.get(d.id)!;m.visible=!!k||v.layers.sensors;const p=k?platformPosition(k,observationFrame(d,displayFrame)):[d.x*1.65,0,d.y*1.7];if(!k||k==='rover'||k==='deep')p[1]=heightAt(p[0],p[2])+(k==='deep'?12:k==='rover'?8:0);m.position.set(p[0],p[1],p[2]);if(k==='drone')m.rotation.y=-displayFrame/120*Math.PI*2;if(k==='rover')m.rotation.y=-displayFrame/240*Math.PI*2;const online=d.status!=='离线';if(online&&k==='drone'&&Math.abs(v.frame-displayFrame)>.01)models.get(d.id)?.spin.forEach(s=>s.rotation.y+=delta*.06);const b=labels.current.get(d.id);if(b){project.copy(m.position).add(new T.Vector3(0,k?20:20,0)).project(camera);b.style.transform=`translate(-50%,-100%) translate(${(project.x*.5+.5)*el.clientWidth}px,${(-project.y*.5+.5)*el.clientHeight}px)`;b.style.display=project.z<1&&project.z>-1&&m.visible?'':'none';b.dataset.selected=String(v.selected===d.id)}
   });const current=spots.get(v.selected);if(current){ring.position.copy(current.position);ring.position.y=heightAt(current.position.x,current.position.z)+1.2;ring.scale.setScalar(1+(reducedMotion.matches?0:Math.sin(time*.002)*.07));if(v.focus!==seenFocus&&v.focus>0){focusTarget.copy(current.position);focusCamera.copy(current.position).add(new T.Vector3(160,130,220));focusing=true;seenFocus=v.focus}}
   if(focusing){const amount=reducedMotion.matches?1:.08;controls.target.lerp(focusTarget,amount);camera.position.lerp(focusCamera,amount);if(camera.position.distanceTo(focusCamera)<.2)focusing=false}controls.autoRotate=!focusing&&getRotationMode()>0;controls.autoRotateSpeed=orbitSpeed('terrain')
   const drone=spots.get(platforms.drone.id),rover=spots.get(platforms.rover.id);if(drone){aerial.position.copy(drone.position);aerial.position.y-=65;aerial.visible=v.devices.find(d=>d.id===platforms.drone.id)?.status!=='离线'}if(rover){footprint.position.copy(rover.position);footprint.position.y+=.2;footprint.rotation.z=time*.00015;footprint.visible=v.devices.find(d=>d.id===platforms.rover.id)?.status!=='离线'}
   if(view==='feed'){const target=current||drone;if(target){target.visible=false;ring.visible=false;const droneView=platformFor({id:v.selected})==='drone';camera.position.copy(target.position).add(new T.Vector3(0,droneView?-8:18,droneView?0:12));const tx=target.position.x*.3,tz=target.position.z*.3;camera.lookAt(tx,heightAt(tx,tz)+6,tz)}}else controls.update(frameSeconds(time,time-delta));renderer.render(scene,camera)
  };raf=requestAnimationFrame(tick)
  return()=>{cancelAnimationFrame(raf);resize.disconnect();observer.disconnect();controls.dispose();disposeScene(scene);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()}
 },[ids,view,compact,cinematic,terrainStyle])
 return <div ref={host} className={`mine-webgl ${compact?'is-compact':''} ${cinematic?'is-cinematic':''} ${view==='feed'?'is-feed':''}`} aria-label={view==='feed'?'设备巡检合成视景':'典型露天矿三维交互场景'}>{failed&&<div className="scene-fallback">WebGL 不可用。请使用支持硬件加速的浏览器；设备列表和详情仍可访问。</div>}{view==='orbit'&&devices.map(d=><button key={d.id} ref={e=>{if(e)labels.current.set(d.id,e);else labels.current.delete(d.id)}} className={`scene-pin ${platformFor(d)?'platform-pin':''} ${d.status==='离线'?'offline':''}`} onClick={()=>onSelect(d.id)} aria-label={`定位设备 ${d.id}`}><EquipmentIcon type={d.type} size={15}/><span className="scene-pin-label">{d.id}</span></button>)}</div>
}
