import {useBoardSelection} from './BoardSelection'
import {lazy,Suspense,useState} from 'react'
import {Play,Pause,LocateFixed,Box,Layers3,Radio,BatteryCharging,ArrowUpRight,Camera,Map,Clock3,Orbit} from 'lucide-react'
import {useDemo} from './store'
import {MineScene,type SceneLayers} from './MineScene'
import {DeviceModelView} from './DeviceModelView'
import {platformFor,platformKinds,platforms,platformTelemetry,observationFrame,sceneTime,missionEvents,type PlatformKind} from './sceneCatalog'
import {TelemetryChart,InspectionFeed,ImageComparison} from './SceneMedia'
import {PlatformWorkbench} from './PlatformWorkbench'
import {SensorModal} from './SensorStudio'
import {goWorkspace} from './navigation'
const CesiumReference=lazy(()=>import('./CesiumReference'))
export function MissionControl({initialMode='scene',onNavigate}:{initialMode?:'scene'|'terrain'|'replay'|'imagery'|'feed';onNavigate?:(page:string)=>void}){
 const {state,visibleDevices,selectDevice,control}=useDemo(),[mode,setMode]=useState(initialMode==='replay'?'scene':initialMode),[layer,setLayer]=useState('全部'),[layers,setLayers]=useState<SceneLayers>({paths:true,coverage:true,underground:false,sensors:true}),[focus,setFocus]=useState(0),[opened,setOpened]=useState(''),[detail,setDetail]=useState('状态')
 const selected=visibleDevices.find(d=>d.id===state.selectedDevice)||visibleDevices.find(d=>platformFor(d)==='drone')||visibleDevices[0],kind=platformFor(selected),spec=kind?platforms[kind]:null,telemetry=kind?platformTelemetry(kind,state.frame,selected):null
 const micro=selected?.type==='微震节点',daq=selected?.type==='数采板',sampleFrame=observationFrame(selected,state.frame)
 const devices=visibleDevices.filter(d=>layer==='全部'||layer==='传感器'&&!platformFor(d)||platformFor(d)===layer)
 const choose=(id:string)=>{selectDevice(id);setDetail('状态')}
 const replay=()=>control({playing:!state.playing,frame:state.frame>=120?0:state.frame})
 return <div className="mission-control"><div className="mission-heading"><div><small>KUANGDA / INTEGRATED MONITORING</small><h2>空天地深 · 协同监测</h2></div><div><span className="demo-badge">工况回放</span><span>{visibleDevices.filter(d=>d.status==='在线').length} / {visibleDevices.length} 在线</span></div></div>
 <div className="mission-layout"><section className="mission-stage"><div className="scene-toolbar"><div>{[['scene','矿区',Box],['terrain','地理参照',Map],['imagery','历史影像',Orbit]].map(([key,label,Icon])=>{const I=Icon as typeof Box;return <button key={String(key)} className={mode===key?'active':''} onClick={()=>setMode(key as typeof mode)}><I size={14}/>{String(label)}</button>})}</div><button onClick={()=>setFocus(v=>v+1)} disabled={mode!=='scene'}><LocateFixed size={15}/>定位选中</button></div>
  {mode==='terrain'?<Suspense fallback={<div className="terrain-loading">加载三维地理引擎…</div>}><CesiumReference devices={devices} selected={selected?.id||''} frame={state.frame} onSelect={choose}/></Suspense>:mode==='imagery'?<div className="mission-imagery"><ImageComparison/><div className="reference-image"><img src="./scene-assets/baiyun-ebo.jpg" alt="白云鄂博 2006 年 ASTER 历史影像"/><span>白云鄂博 / ASTER 2006.06.30 · NASA/GSFC/METI/ERSDAC/JAROS</span></div></div>:mode==='feed'?<InspectionFeed kind={kind&&platforms[kind].camera?kind:'drone'} devices={visibleDevices} frame={state.frame}/>:<><MineScene cinematic devices={devices} frame={state.frame} selected={selected?.id||''} onSelect={choose} layers={layers} focus={focus}/><div className="scene-watermark"><small>典型台阶式露天矿</small><span>本地概念场景 · 非实际矿区复刻</span></div><div className="scene-layers">{[['paths','轨迹'],['coverage','覆盖'],['underground','地下'],['sensors','测点']].map(([key,label])=><button key={key} className={layers[key as keyof SceneLayers]?'active':''} onClick={()=>setLayers(v=>({...v,[key]:!v[key as keyof SceneLayers]}))}><Layers3 size={12}/>{label}</button>)}</div><span className="scene-hint">拖动旋转 · Ctrl+滚轮缩放 · 点选设备</span></>}
 <div className="scene-filter">{[['全部','全部'],...platformKinds.map(k=>[k,`${platforms[k].layer} · ${platforms[k].name.slice(0,2)}`]),['传感器','监测点']].map(([key,label])=><button key={key} className={layer===key?'active':''} onClick={()=>setLayer(key)}>{label}<small>{visibleDevices.filter(d=>key==='全部'||key==='传感器'&&!platformFor(d)||platformFor(d)===key).length}</small></button>)}</div></section>
 <aside className="mission-inspector"><header><div><small>{spec?.english||'SENSOR'} / SELECTED</small><h3>{selected?.name||'选择设备'}</h3></div><span className={selected?.status==='离线'?'offline':'online'}>{selected?.status}</span></header><select aria-label="场景设备选择" value={selected?.id||''} onChange={e=>choose(e.target.value)}>{visibleDevices.map(d=><option key={d.id} value={d.id}>{d.id} · {d.name}</option>)}</select><div className="inspector-tabs">{['状态','监测'].map(t=><button key={t} className={detail===t?'active':''} onClick={()=>setDetail(t)}>{t}</button>)}</div>
 {detail==='状态'?<>{kind?<DeviceModelView kind={kind} cinematic compact/>:<div className="sensor-marker"><Radio size={50}/><strong>{selected?.type}</strong></div>}<div className="mission-stat-row"><span><BatteryCharging size={15}/>{micro?'供电来源':daq?'后备电量':'电量'}<b className={micro?'text-readout':''}>{micro?'数采侧供电':telemetry?.battery??selected?.battery}<small>{micro?'':'%'}</small></b></span><span><Radio size={15}/>链路<b className={micro?'text-readout':''}>{selected?.status==='离线'?'离线':micro?'有线差分':daq?'100':selected?.signal}<small>{selected?.status==='离线'||micro?'':daq?' Mbps':' dBm'}</small></b></span></div>{!micro&&<div className="mission-battery-track"><i style={{width:`${telemetry?.battery??selected?.battery??0}%`}}/></div>}<TelemetryChart kind={kind||'deep'} frame={sampleFrame}/></>:kind==='satellite'?<><img className="satellite-reference" src="./scene-assets/baiyun-ebo.jpg" alt="NASA 白云鄂博历史遥感影像"/><small>ASTER 2006.06.30 / 历史参考影像</small><button onClick={()=>setMode('imagery')}>影像对比 <ArrowUpRight size={14}/></button></>:kind&&spec?.camera?<><InspectionFeed kind={kind} devices={visibleDevices} frame={state.frame}/><button onClick={()=>setMode('feed')}><Camera size={15}/>展开巡检画面</button></>:<TelemetryChart kind="deep" frame={sampleFrame} mode="channels"/>}
 <button className="mission-open-device" disabled={!selected} onClick={()=>selected&&goWorkspace({page:'device',id:selected.id,device:selected.id})}><Box size={16}/>打开设备档案<ArrowUpRight size={15}/></button><small className="inspector-note">{spec?.protocol||'采样、供电与通信状态 / 样例'}</small></aside></div>
 <div className="mission-timeline"><button onClick={replay} aria-label={state.playing?'暂停工况回放':'播放工况回放'}>{state.playing?<Pause size={17}/>:<Play size={17}/>}</button><div className="mission-clock"><small>工况回放</small><strong>{sceneTime(state.frame)}</strong></div><div className="mission-timeline-track"><input aria-label="场景历史时间轴" type="range" min="0" max="120" value={state.frame} onChange={e=>control({frame:+e.target.value,playing:false})}/><div>{missionEvents.map(e=><button key={e.frame} style={{left:`${e.frame/120*100}%`}} onClick={()=>{control({frame:e.frame,playing:false});choose(platforms[e.kind].id)}}><i/>{e.title}</button>)}</div></div><select aria-label="回放倍速" value={state.speed} onChange={e=>control({speed:+e.target.value})}>{[1,2,4].map(x=><option key={x} value={x}>{x}×</option>)}</select>{onNavigate&&<button onClick={()=>goWorkspace({page:'trace',device:selected?.id,frame:String(state.frame)})}><Clock3 size={15}/>数据回溯</button>}</div>
 {opened&&<SensorModal deviceId={opened} onClose={()=>setOpened('')}/>}</div>
}
export function SceneWidget({kind,onOpen}:{kind:string;onOpen:()=>void}){const board=useBoardSelection();const {state,visibleDevices}=useDemo();const k=({satelliteTwin:'satellite',droneTwin:'drone',roverTwin:'rover',deepTwin:'deep'} as Record<string,PlatformKind>)[kind];return <div className="scene-widget" data-widget-interactive>{k?<><DeviceModelView kind={k} cinematic compact onSelect={()=>goWorkspace({page:'device',id:platforms[k].id,device:platforms[k].id})}/><button className="scene-widget-status quiet-button" aria-label={`查看 ${platforms[k].id} 设备`} onClick={()=>goWorkspace({page:'device',id:platforms[k].id,device:platforms[k].id})}><span>{platforms[k].id}</span><b>{visibleDevices.find(d=>d.id===platforms[k].id)?.status||'范围外'}</b></button></>:kind==='remoteSensingCompare'?<ImageComparison/>:kind==='inspectionFeed'?<InspectionFeed kind="drone" devices={visibleDevices} frame={state.frame}/>:<MineScene cinematic compact devices={visibleDevices} frame={state.frame} selected={state.selectedDevice} onSelect={id=>board?board.choose(id):goWorkspace({page:'device',id,device:id})} layers={{paths:true,coverage:true,underground:kind==='missionReplay',sensors:true}}/>}</div>}
export function SceneWorkbench({kind}:{kind:string}){const k=({satelliteTwin:'satellite',droneTwin:'drone',roverTwin:'rover',deepTwin:'deep'} as Record<string,PlatformKind>)[kind];return k?<PlatformWorkbench kind={k}/>:<MissionControl initialMode={kind==='terrainReference'?'terrain':kind==='remoteSensingCompare'?'imagery':kind==='inspectionFeed'?'feed':kind==='missionReplay'?'replay':'scene'}/>}
