import {useState} from 'react'
import {Activity,ArrowRight,Check,Download,FileUp,GitBranch,Info,Radio,Save,Search,ShieldCheck} from 'lucide-react'
import {type RecordItem,exportFile,useDemo,now} from './store'
import {operationView,defaultOperation,validOperation,operationSeries,thresholdRuns,reorderPackets,type OperationDraft} from './operationProfiles'
import {SignalTrace} from './ChannelWorkspace'
import {WorkspaceDrawer} from './WorkspaceDrawer'
export function OperationPanel(props:{kind:string;action:string;index:number;fields:string[];current?:RecordItem;allowed:boolean;onApply:(s:string,payload:OperationDraft)=>void}){if(!props.current)return null;return <OperationViewPanel key={props.kind+props.current.id+props.action} {...props} current={props.current}/>}
function OperationViewPanel({kind,action,index,fields,current,allowed,onApply}:{kind:string;action:string;index:number;fields:string[];current:RecordItem;allowed:boolean;onApply:(s:string,payload:OperationDraft)=>void}){
 const {visibleDevices,state}=useDemo(),view=operationView(kind,index),saved=current.operations?.[action]
 const [draft,setDraft]=useState<OperationDraft>(validOperation(saved)?saved:defaultOperation()),[query,setQuery]=useState(''),[inspected,setInspected]=useState(''),[info,setInfo]=useState(false),[notice,setNotice]=useState(''),[sort,setSort]=useState(false),[dedupe,setDedupe]=useState(true),[file,setFile]=useState<{name:string;size:number;hash:string;lines:number}|null>(null),[fileError,setFileError]=useState('')
 const device=visibleDevices.find(d=>d.id===draft.device)||visibleDevices.find(d=>d.id===state.selectedDevice)||visibleDevices[0],selected=visibleDevices.filter(d=>draft.targets.includes(d.id)),series=operationSeries(kind.length+index),hits=thresholdRuns(series,draft.threshold,draft.duration),steps=['草稿','核验','审批','就绪','归档'],checks=['对象与范围','参数有效性','权限与责任人','证据已留存'],change=(patch:Partial<OperationDraft>)=>{setDraft({...draft,...patch});setNotice('')},save=()=>{if(!allowed||!validOperation(draft))return;onApply(action,draft);setNotice('已保存本地记录')},toggle=(id:string)=>change({targets:draft.targets.includes(id)?draft.targets.filter(v=>v!==id):[...draft.targets,id]})
 const download=()=>exportFile(current.id+'-'+action+'.json',JSON.stringify({object:current.id,action,config:draft,record:current.values,source:'本地配置与合成工况',generatedAt:now()},null,2))
 return <section className="business-console operation-workspace" data-operation-view={view}><header className="business-console-bar"><span className="operation-object">{current.values[0]}</span><select aria-label="操作关联设备" value={device?.id||''} onChange={e=>change({device:e.target.value})}>{visibleDevices.map(d=><option key={d.id} value={d.id}>{d.id}</option>)}</select><button aria-label="操作数据来源" onClick={()=>setInfo(true)}><Info size={15}/></button><button onClick={download}><Download size={15}/>导出</button></header>
 {view==='inventory'&&<div data-view="record-inventory"><label className="adapter-search"><Search size={16}/><input aria-label="检索当前对象" placeholder="查找字段或状态" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="operation-inventory">{fields.map((field,i)=>({field,value:current.values[i]||'未配置'})).filter(r=>(r.field+r.value).includes(query)).map(r=><button key={r.field} aria-pressed={inspected===r.field} onClick={()=>setInspected(inspected===r.field?'':r.field)}><small>{r.field}</small><strong>{r.value.startsWith('{')?'结构化记录':r.value}</strong><ArrowRight size={15}/></button>)}</div>{inspected&&<div className="operation-inspected"><span>{inspected}</span><span>V{current.version}</span><span>{current.updated}</span><button onClick={download}>下载完整记录</button></div>}</div>}
 {view==='topology'&&<div className="business-two-panel"><div className="glass-business-panel"><svg className="operation-network" viewBox="0 0 660 340" role="img" aria-label={action+'关系图'}>{visibleDevices.slice(0,6).map((d,i)=>{const y=35+i*53;return <g key={d.id} role="button" tabIndex={0} onClick={()=>change({device:d.id})} onKeyDown={e=>e.key==='Enter'&&change({device:d.id})}><path d={'M160 '+y+' C250 '+y+' 230 170 320 170'} fill="none" stroke={device?.id===d.id?'#b5d9dd':'#7396ad50'} strokeWidth={device?.id===d.id?3:1}/><rect x="10" y={y-17} width="150" height="34" rx="12" fill={device?.id===d.id?'#3a5b6c':'#16313f'} stroke="#aacee233"/><text x="85" y={y+4} textAnchor="middle" fill="#bcd5dd" fontSize="12">{d.id}</text></g>})}<circle cx="355" cy="170" r="38" fill="#99c6d217" stroke="#9bcdd2"/><text x="355" y="174" textAnchor="middle" fill="#cee3e9" fontSize="12">{kind.includes('mqtt')?'Topic':'关联节点'}</text><path d="M393 170H510" stroke="#9bcdd277"/><rect x="510" y="143" width="135" height="54" rx="15" fill="#aacece10" stroke="#bbd2db44"/><text x="577" y="174" textAnchor="middle" fill="#bcd5dd" fontSize="12">本地配置</text></svg></div><div className="glass-business-panel business-editor"><h3>{device?.id}</h3><label>运行状态<strong>{device?.status}</strong></label><label>区域<strong>{device?.area}</strong></label><label>信号<strong>{device?.signal} dBm</strong></label><button aria-pressed={!!device&&draft.targets.includes(device.id)} onClick={()=>device&&toggle(device.id)}>{device&&draft.targets.includes(device.id)?'取消关联':'加入关联'}</button><span>{selected.length} 台已选</span></div></div>}
 {view==='trend'&&<div className="glass-business-panel"><div className="business-panel-label"><Activity size={16}/>{action}<span>96 个样本</span></div><SignalTrace values={series.map(v=>v-50)} limit={55}/><div className="operation-spark-bars">{series.filter((_,i)=>i%3===0).map((v,i)=><i key={i} style={{height:v+'%',background:v>draft.threshold?'#d2aa7999':undefined}}/>)}</div><div className="business-key-readings"><span><b>{Math.max(...series).toFixed(1)}</b>峰值</span><span><b>{(series.reduce((s,v)=>s+v,0)/series.length).toFixed(1)}</b>均值</span><span><b>{hits.filter(Boolean).length}</b>连续越阈点</span></div><label className="operation-range">阈值<input aria-label="趋势阈值" type="range" min="0" max="100" value={draft.threshold} onChange={e=>change({threshold:+e.target.value})}/>{draft.threshold}</label></div>}
 {view==='policy'&&<div className="business-two-panel"><div className="glass-business-panel"><div className="policy-blocks"><span>输入样本 <b>{series.length}</b></span><ArrowRight/><span>阈值 <b>{draft.threshold}</b></span><ArrowRight/><span>持续 <b>{draft.duration}</b></span></div><div className="policy-sample-grid">{series.map((v,i)=><button key={i} title={'#'+(i+1)+' / '+v.toFixed(1)} aria-label={'样本 '+(i+1)+' '+(hits[i]?'命中':'正常')} className={hits[i]?'hit':''} onClick={()=>setInspected('#'+(i+1)+' · '+v.toFixed(2))}/>)}</div><div className="business-panel-label">{inspected||'条件命中'}<span>{hits.filter(Boolean).length} / {series.length}</span></div></div><div className="glass-business-panel business-editor"><label>判定阈值<input type="number" min="0" max="100" value={draft.threshold} onChange={e=>change({threshold:Math.max(0,Math.min(100,+e.target.value))})}/></label><label>连续次数<input type="number" min="1" max="60" value={draft.duration} onChange={e=>change({duration:Math.max(1,Math.min(60,+e.target.value))})}/></label><small>条件变化后重新试算</small></div></div>}
 {view==='schedule'&&<div className="business-two-panel"><div className="glass-business-panel"><div className="business-panel-label">计划日期<input type="month" aria-label="计划月份" value={draft.date.slice(0,7)} onChange={e=>e.target.value&&change({date:e.target.value+'-01'})}/></div><div className="operation-calendar">{Array.from({length:new Date(Number(draft.date.slice(0,4)),Number(draft.date.slice(5,7)),0).getDate()},(_,i)=>{const date=draft.date.slice(0,8)+String(i+1).padStart(2,'0');return <button key={date} aria-pressed={draft.date===date} onClick={()=>change({date})}>{i+1}{draft.date===date&&<i/>}</button>})}</div></div><div className="glass-business-panel business-editor"><h3>{draft.date}</h3><label>对象<span>{device?.id}</span></label><label>责任人<span>{device?.owner}</span></label><label>事项<input maxLength={160} value={draft.note} placeholder={action} onChange={e=>change({note:e.target.value})}/></label><span>{selected.length||1} 台设备</span></div></div>}
 {view==='checklist'&&<div className="business-two-panel"><div className="operation-checklist">{checks.map((s,i)=><button key={s} aria-pressed={draft.checks.includes(s)} onClick={()=>change({checks:draft.checks.includes(s)?draft.checks.filter(v=>v!==s):[...draft.checks,s]})}><span>{draft.checks.includes(s)?<Check size={20}/>:String(i+1).padStart(2,'0')}</span><strong>{s}</strong><small>{draft.checks.includes(s)?'已核验':'待核验'}</small></button>)}</div><div className="glass-business-panel checklist-dial"><svg viewBox="0 0 180 180" aria-label="人工核验进度"><circle cx="90" cy="90" r="68" fill="none" stroke="#718e9a26" strokeWidth="8"/><circle cx="90" cy="90" r="68" fill="none" stroke="#a2cdbf" strokeWidth="8" strokeDasharray={draft.checks.length/4*427+' 427'} transform="rotate(-90 90 90)"/><text x="90" y="99" textAnchor="middle" fill="#c4dee3" fontSize="30">{draft.checks.length} / 4</text></svg><label>核验备注<input value={draft.note} maxLength={160} onChange={e=>change({note:e.target.value})}/></label></div></div>}
 {view==='sequence'&&<div className="glass-business-panel"><div className="business-panel-label">接收序列<span>{device?.id}</span></div><div className="packet-sequence">{(sort?reorderPackets([1,2,4,3,5,5,7,6,8,9,11,10],dedupe):[1,2,4,3,5,5,7,6,8,9,11,10]).map((n,i)=><button key={i} className={!sort&&[2,5,6,10].includes(i)?'out-of-order':''} onClick={()=>setInspected('序号 '+n+' · 到达位置 '+(i+1))}><Radio size={18}/><b>{n}</b><small>{i+1}</small></button>)}</div><div className="business-form-row"><button onClick={()=>setSort(v=>!v)}>{sort?'查看接收顺序':'按序重排'}</button><button aria-pressed={dedupe} onClick={()=>setDedupe(v=>!v)}>{dedupe?'重复折叠':'保留重复'}</button><span>{inspected}</span></div><div className="sequence-line">{['接收','排序','去重','输出'].map((s,i)=><span key={s}><i className={i===0||sort?'done':''}/>{s}</span>)}</div></div>}
 {view==='mapping'&&<div className="glass-business-panel"><div className="mapping-station"><div><small>原始值</small><strong>1250</strong></div><ArrowRight/><div className="business-editor"><label>比例<input type="number" step=".001" aria-label="换算比例" value={draft.scale} onChange={e=>change({scale:+e.target.value})}/></label><label>偏移<input type="number" step=".1" value={draft.offset} onChange={e=>change({offset:+e.target.value})}/></label></div><ArrowRight/><div><small>换算结果</small><strong>{(1250*draft.scale+draft.offset).toFixed(3)}</strong></div></div><div className="mapping-samples">{[0,500,1000,2000,5000].map(n=><div key={n}><span>{n}</span><ArrowRight size={13}/><strong>{(n*draft.scale+draft.offset).toFixed(2)}</strong></div>)}</div></div>}
 {view==='history'&&<div className="glass-business-panel"><div className="business-panel-label"><GitBranch size={17}/>操作轨迹<span>V{current.version}</span></div><div className="operation-history">{current.history.map((h,i)=><button key={i} aria-pressed={inspected===h} onClick={()=>setInspected(h)}><i/><span>{h}</span></button>)}</div>{inspected&&<div className="operation-inspected">{inspected}</div>}<button onClick={download}><Download size={16}/>导出版本记录</button></div>}
 {view==='files'&&<div className="business-two-panel"><label className="glass-business-panel operation-dropzone"><FileUp size={42}/><strong>选择本地文件</strong><span>最大 8 MB</span><input type="file" aria-label="检查本地文件" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setFile(null);setFileError('');if(f.size>8*1024*1024){setFileError('文件超过 8 MB');return}try{const bytes=await f.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes);setFile({name:f.name,size:f.size,hash:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join(''),lines:f.type.startsWith('text/')||/\.(txt|csv|json)$/i.test(f.name)?new TextDecoder().decode(bytes).split(/\r?\n/).length:0})}catch{setFileError('读取文件失败')}e.target.value=''}}/></label><div className="glass-business-panel business-editor">{file?<><h3>{file.name}</h3><label>大小<strong>{(file.size/1024).toFixed(1)} KB</strong></label><label>文本行<strong>{file.lines||'—'}</strong></label><label>SHA-256<span title={file.hash}>{file.hash.slice(0,12)}…</span></label><button onClick={()=>exportFile(file.name+'-校验.json',JSON.stringify(file,null,2))}>下载校验记录</button></>:<div className="protocol-await"><ShieldCheck size={36}/><span>{fileError||'等待文件校验'}</span></div>}</div></div>}
 {view==='scope'&&<div className="glass-business-panel"><div className="business-panel-label">生效范围<span>{selected.length} / {visibleDevices.length} 台</span></div><div className="business-form-row"><input aria-label="筛选范围设备" value={query} placeholder="设备 / 区域" onChange={e=>setQuery(e.target.value)}/><button onClick={()=>change({targets:visibleDevices.map(d=>d.id)})}>全选</button><button onClick={()=>change({targets:[]})}>清空</button></div><div className="operation-device-grid">{visibleDevices.filter(d=>(d.id+d.name+d.area).toLowerCase().includes(query.toLowerCase())).map(d=><button key={d.id} aria-pressed={draft.targets.includes(d.id)} onClick={()=>toggle(d.id)}><Radio size={16}/><span>{d.id}<small>{d.area} · {d.type}</small></span>{draft.targets.includes(d.id)&&<Check size={15}/>}</button>)}</div></div>}
 {view==='workflow'&&<div className="glass-business-panel"><div className="operation-workflow">{steps.map((s,i)=><button key={s} aria-pressed={draft.stage===i} onClick={()=>setInspected(s)}><b>{i<draft.stage?<Check size={23}/>:i+1}</b><span>{s}</span></button>)}</div><div className="workflow-inspector"><div><small>当前阶段</small><h3>{steps[draft.stage]}</h3><span>{inspected&&inspected!==steps[draft.stage]?'查看：'+inspected:device?.id}</span></div><label>操作记录<input aria-label="流程操作记录" value={draft.note} maxLength={160} onChange={e=>change({note:e.target.value})}/></label><button disabled={!allowed||!draft.note.trim()||draft.stage>=4} onClick={()=>{const next={...draft,stage:draft.stage+1};setDraft(next);onApply(action,next);setNotice('阶段记录已保存')}}>推进至{steps[Math.min(4,draft.stage+1)]}</button></div></div>}
 <footer className="business-console-status"><span role="status">{notice||'V'+current.version}</span>{!['inventory','history','files','sequence'].includes(view)&&<button disabled={!allowed||!validOperation(draft)} onClick={save}><Save size={14}/>保存{view==='checklist'?'核验':view==='schedule'?'计划':'配置'}</button>}</footer>
 {info&&<WorkspaceDrawer title="数据与操作范围" onClose={()=>setInfo(false)}><p>设备状态取自当前本地设备档案。趋势与接收序列为内置工况，趋势统一归一至 0–100；规则按当前参数实际试算。保存仅写入本机配置及审计，不执行远程重启、硬件下发或通知发送。文件校验在浏览器内计算 SHA-256，文件不会上传。</p></WorkspaceDrawer>}
 </section>
}
