import {RotationControl} from './RotationControl'
import {useState} from 'react'
import {BatteryCharging,Radio,Layers3,Rotate3D,ArrowUpRight,Camera,Activity,History,Box} from 'lucide-react'
import {useDemo} from './store'
import {DeviceModelView} from './DeviceModelView'
import {ImageComparison,InspectionFeed,TelemetryChart} from './SceneMedia'
import {platforms,platformKinds,platformTelemetry,sceneTime,missionEvents,type PlatformKind} from './sceneCatalog'

export function PlatformWorkbench({kind}:{kind:PlatformKind}){
 const {state,visibleDevices,can,update,control}=useDemo(),spec=platforms[kind],device=visibleDevices.find(d=>d.id===spec.id),[part,setPart]=useState(spec.parts[0].id),[spread,setSpread]=useState(0),[tab,setTab]=useState('结构与状态'),[notice,setNotice]=useState('')
 if(!device)return <div className="empty">当前角色范围内没有该设备。</div>
 const chosen=spec.parts.find(p=>p.id===part)||spec.parts[0],telemetry=platformTelemetry(kind,state.frame,device),fault=Object.keys(device.parts||{}).length>0
 const toggleFault=()=>{update('device',fault?'恢复三维设备（演示）':'模拟通信中断',device.id,s=>({...s,devices:s.devices.map(d=>d.id!==device.id?d:fault?{...d,...d.faultBackup,status:d.faultBackup?.status||'在线',parts:{},faultBackup:undefined,lastSeenFrame:undefined}:{...d,faultBackup:{status:d.status,battery:d.battery,signal:d.signal},status:'离线',lastSeenFrame:s.frame,signal:-112,parts:{[part]:'模拟通信中断'}})}));setNotice(fault?'链路恢复，操作已归档。':'离线工况已注入，画面与状态同步暂停。')}
 return <div className="platform-workbench"><header className="platform-heading"><div><small>{spec.english} / {device.id}</small><h2>{spec.name}</h2></div><span className={telemetry.online?'platform-status':'platform-status is-offline'}><i/>{device.status} · 样例</span></header><div className="platform-tabs">{[['结构与状态',Box],['监测成果',Activity],['供电与通信',Radio],['任务与历史',History]].map(([name,Icon])=>{const I=Icon as typeof Box;return <button key={String(name)} className={tab===name?'active':''} onClick={()=>setTab(String(name))}><I size={15}/>{String(name)}</button>})}</div>
 {tab==='结构与状态'?<div className="platform-detail-grid"><aside className="platform-parts">{spec.parts.map((p,i)=><button key={p.id} className={part===p.id?'active':''} onClick={()=>setPart(p.id)}><small>0{i+1}</small><span>{p.name}</span><i/></button>)}</aside><section className="platform-model"><DeviceModelView kind={kind} cinematic selected={part} onSelect={setPart} explode={spread} auto/><div className="platform-model-tools"><RotationControl/><button onClick={()=>setSpread(spread>0?0:1)}><Layers3 size={15}/>{spread>0?'收拢':'拆解'}</button><input aria-label="设备结构拆解程度" type="range" min="0" max="1" step=".01" value={spread} onChange={e=>setSpread(+e.target.value)}/></div></section><aside className="platform-readout"><small>部件诊断 / 概念样例</small><h3>{chosen.name}</h3><strong>{chosen.value}<small>{chosen.unit}</small></strong><div className="platform-mini-metrics"><span><BatteryCharging size={17}/>电量<b>{telemetry.battery}%</b></span><span><Radio size={17}/>链路<b>{telemetry.online?`${telemetry.signal} dBm`:'中断'}</b></span></div><TelemetryChart kind={kind} frame={state.frame}/><button disabled={!can('device')} className="platform-fault" onClick={toggleFault}>{fault?'恢复连接':'模拟通信中断'}</button><small role="status">{notice||'概念结构，不用于工程制造或安全判断。'}</small></aside></div>:
 tab==='监测成果'?<div className="platform-monitor-grid">{kind==='satellite'?<ImageComparison/>:kind==='deep'?<><TelemetryChart kind={kind} frame={state.frame} mode="channels"/><TelemetryChart kind={kind} frame={state.frame} mode="spectrum"/></>:<><InspectionFeed kind={kind} devices={visibleDevices} frame={state.frame}/><div><h3>{kind==='drone'?'航迹遥测':'雷达扫描剖面'}</h3><TelemetryChart kind={kind} frame={state.frame}/><div className="mission-stat-row"><span>{kind==='drone'?'离地高度':'扫描扇区'}<b>{kind==='drone'?telemetry.altitude:'120'}<small>{kind==='drone'?' m':' °'}</small></b></span><span>速度<b>{telemetry.speed}<small> m/s</small></b></span></div></div></>}{kind==='deep'&&<p className="visual-note">三分量波形与频谱为演示样例，地下探头与地表站分别建模。</p>}</div>:
 tab==='供电与通信'?<div className="platform-power"><div className="battery-visual"><BatteryCharging size={40}/><strong>{telemetry.battery}<small>%</small></strong><div>{Array.from({length:20},(_,i)=><i key={i} className={i<telemetry.battery/5?'filled':''}/>)}</div><small>样例电量 / 不代表厂商续航参数</small></div><div className="link-visual">{[spec.name,kind==='satellite'?'地面接收站':'边缘网关','接入服务','数据存储'].map((s,i)=><div key={s}><span className={telemetry.online?'':'offline'}><Radio size={22}/>{s}</span>{i<3&&<b className={telemetry.online?'flow-active':''}>········›</b>}</div>)}</div><p>{spec.protocol}</p></div>:
 <div className="platform-history"><div className="mission-event-list">{missionEvents.filter(e=>e.kind===kind).map(e=><button key={e.frame} onClick={()=>control({frame:e.frame,playing:false})}><History size={16}/><span>{sceneTime(e.frame)}</span><strong>{e.title}</strong><ArrowUpRight size={15}/></button>)}{state.audit.filter(a=>a.object===device.id).slice(0,6).map(a=><article key={a.id}><span>{a.time}</span><strong>{a.action}</strong></article>)}</div><TelemetryChart kind={kind} frame={state.frame}/><label className="platform-time">{sceneTime(state.frame)}<input aria-label="设备历史时间" type="range" min="0" max="120" value={state.frame} onChange={e=>control({frame:+e.target.value,playing:false})}/></label></div>}
 <footer className="platform-workbench-foot">{spec.model} · 独立数字档案 · 数据、轨迹和内部结构均为演示样例</footer></div>
}
export function PlatformGallery({onOpen}:{onOpen:(id:string)=>void}){const {visibleDevices}=useDemo();return <div className="platform-gallery">{platformKinds.map(kind=>{const spec=platforms[kind],d=visibleDevices.find(d=>d.id===spec.id);return d?<article key={kind}><header><small>{spec.layer} / {spec.english}</small><span><i/>{d.status}</span></header><DeviceModelView kind={kind} compact/><h3>{spec.name}</h3><footer><span>{spec.id}</span><button onClick={()=>onOpen(spec.id)}>设备档案 <ArrowUpRight size={14}/></button></footer></article>:null})}</div>}
