export type PresentationKind='wave'|'energy'|'layers'|'array'|'events'|'mechanism'|'fracture'|'forecast'|'risk'
export const presentationProfiles:Record<string,{kind:PresentationKind;title:string;control:string;views:[string,string,string]}>={
 'shot-gather':{kind:'wave',title:'测线与接收记录',control:'接收通道',views:['道集','测线','频谱']},
 taup:{kind:'energy',title:'慢度扫描',control:'扫描慢度',views:['扫描响应','接收记录','叠加能量']},
 fk:{kind:'energy',title:'传播能量',control:'波数切片',views:['频率—波数','接收记录','振幅谱']},
 'phase-shift-active':{kind:'energy',title:'相位聚焦',control:'频率切片',views:['能量面','脊线','接收记录']},
 'slant-stack':{kind:'energy',title:'信号叠加',control:'扫描位置',views:['叠加响应','通道记录','能量']},
 hrlrt:{kind:'energy',title:'模态分辨',control:'速度切片',views:['高分辨率','常规对照','迭代残差']},
 'dispersion-pick':{kind:'energy',title:'频散拾取',control:'频率位置',views:['能量与路径','拾取结果','接收记录']},
 'surface-inversion':{kind:'layers',title:'地下速度结构',control:'候选模型',views:['地层模型','拟合对照','迭代残差']},
 'section-imaging':{kind:'layers',title:'测线下方的地层',control:'测线位置',views:['连续剖面','候选模型','测线']},
 spac:{kind:'array',title:'环组与相关响应',control:'距离组',views:['相关响应','观测阵列','频散成果']},
 remi:{kind:'energy',title:'环境振动提取',control:'速度切片',views:['传播能量','窗口质量','测线']},
 maps:{kind:'wave',title:'台站之间的共同信号',control:'台站对',views:['相关道集','叠加结果','台站配对']},
 fh:{kind:'array',title:'径向传播响应',control:'积分环',views:['能量','积分阵列','径向响应']},
 'cmp-ts':{kind:'layers',title:'共中点叠加剖面',control:'中点位置',views:['剖面','中点分箱','覆盖次数']},
 beamforming:{kind:'array',title:'信号来向',control:'方位',views:['方向波束','圆形台阵','波束功率']},
 hvsr:{kind:'array',title:'场地共振',control:'频率位置',views:['谱比','三分量','窗口集合']},
 'passive-inversion':{kind:'layers',title:'联合约束的地层',control:'候选模型',views:['地层模型','频散拟合','H/V 约束']},
 'array-design':{kind:'array',title:'台站与覆盖',control:'覆盖切片',views:['台站布设','深度切片','方位分布']},
 'event-detection':{kind:'wave',title:'事件窗口',control:'观察窗口',views:['事件记录','触发依据','能量包络']},
 'ps-pick':{kind:'wave',title:'初至位置',control:'时间位置',views:['到时记录','触发依据','通道能量']},
 'velocity-model':{kind:'layers',title:'地下介质剖切',control:'剖切位置',views:['分层体','速度切片','层状模型']},
 'event-location':{kind:'events',title:'震源定位',control:'事件',views:['位置','残差','平面分布']},
 'magnitude-energy':{kind:'events',title:'事件规模',control:'事件',views:['位移谱','事件分布','幅值校正']},
 'moment-tensor':{kind:'mechanism',title:'岩体破裂方向',control:'观察方位',views:['震源机制','响应匹配','候选解']},
 'stress-inversion':{kind:'mechanism',title:'岩体受力方向',control:'观察方位',views:['主应力方向','三向应力','角度失配']},
 'fracture-network':{kind:'fracture',title:'裂缝与连通关系',control:'裂缝组',views:['裂缝网络','优势方向','密度切片']},
 permeability:{kind:'fracture',title:'流动路径与影响体积',control:'剖切位置',views:['影响体积','渗透率切片','连通路径']},
 'event-attributes':{kind:'events',title:'事件群的演变',control:'时间位置',views:['时空分布','事件密度','数量与能量']},
 'slope-stability':{kind:'layers',title:'边坡剖面',control:'归档工况',views:['边坡','工况对比','工程地层']},
 'gnss-prediction':{kind:'forecast',title:'测点位移',control:'时间位置',views:['观测与外推','拟合残差','时段增量']},
 'multi-risk':{kind:'risk',title:'风险与关联证据',control:'时间位置',views:['证据','多源对齐','关联区域']},
}
