import {useState} from 'react'
import {ArrowRight,Check,FileUp,GitBranch,Play,Radio,RotateCcw,Search,Upload,Download,Info} from 'lucide-react'
import {useDemo,now,exportFile} from './store'
import {useBusinessConfig} from './useBusinessConfig'
import {adapters,protocolSample,parseProtocolSample,versionDiff,defaultProtocol,validProtocol,type Adapter,type ParseTest,type ProtocolRelease} from './protocolConfig'
import {WorkspaceDrawer} from './WorkspaceDrawer'
const tabs=['协议检索','版本管理','样例测试','发布状态']
export function ProtocolWorkspace({initialTab='协议检索'}:{initialTab?:string}){
 const [id,setId]=useState<string>(adapters[0].id),[tab,setTab]=useState(initialTab),[query,setQuery]=useState('')
 const a=adapters.find(a=>a.id===id)||adapters[0]
 return <section className="business-console protocol-console" data-business="protocols"><header className="business-console-bar"><select aria-label="当前适配器" value={id} onChange={e=>setId(e.target.value)}>{adapters.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><nav>{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav></header>{tab==='协议检索'?<div data-view="adapter-catalog"><label className="adapter-search"><Search size={16}/><input aria-label="搜索适配器" placeholder="协议 / 设备 / 格式" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="adapter-cards">{adapters.filter(a=>(a.name+a.transport).toLowerCase().includes(query.toLowerCase())).map(a=><button key={a.id} onClick={()=>{setId(a.id);setTab('版本管理')}}><Radio size={28}/><strong>{a.name}</strong><span>{a.transport}</span><div className="adapter-mini-flow"><i>接收</i><ArrowRight size={13}/><i>映射</i><ArrowRight size={13}/><i>校验</i></div><small>{a.versions.length} 个版本 <ArrowRight size={13}/></small></button>)}</div></div>:null}<ProtocolDetail key={id} adapter={a} tab={tab} setTab={setTab}/></section>
}
function ProtocolDetail({adapter:a,tab,setTab}:{adapter:Adapter;tab:string;setTab:(s:string)=>void}){
 const cfg=useBusinessConfig('protocolSettings',a.id,defaultProtocol,'config',validProtocol),{visibleDevices}=useDemo()
 const [version,setVersion]=useState<string>('1.1'),[baseline,setBaseline]=useState<string>('1.0'),[text,setText]=useState(()=>protocolSample(a,a.versions[1])),[result,setResult]=useState<ParseTest|null>(null),[tested,setTested]=useState(''),[file,setFile]=useState('内置样本'),[targets,setTargets]=useState<string[]>([]),[confirm,setConfirm]=useState<ProtocolRelease|null>(null),[info,setInfo]=useState(false)
 const v=a.versions.find(v=>v.id===version)!,base=a.versions.find(v=>v.id===baseline)!,compatible=visibleDevices.filter(d=>d.type===a.device),scoped=targets.filter(t=>compatible.some(d=>d.id===t)),pass=!!result?.passed&&tested===version+'|'+text,active=cfg.value.releases.find(r=>r.id===cfg.value.active)
 const changeVersion=(id:string)=>{setVersion(id);setText(protocolSample(a,a.versions.find(v=>v.id===id)!));setResult(null);setTested('');setFile('内置样本')}
 const run=()=>{setResult(parseProtocolSample(text,a,v));setTested(version+'|'+text)}
 const publish=()=>{if(!pass||!scoped.length||!cfg.allowed)return;const release={id:crypto.randomUUID(),version,targets:scoped,time:now(),action:'发布'};cfg.save({active:release.id,releases:[release,...cfg.value.releases].slice(0,30)},'保存本地协议发布');setTab('发布状态')}
 const rollback=()=>{if(!confirm||!cfg.allowed)return;const targets=confirm.targets.filter(t=>compatible.some(d=>d.id===t));if(!targets.length)return;const release={...confirm,targets,id:crypto.randomUUID(),time:now(),action:'回滚'};cfg.save({active:release.id,releases:[release,...cfg.value.releases].slice(0,30)},'回滚本地协议配置');setConfirm(null)}
 if(tab==='协议检索')return null
 return <><div className="protocol-version-bar"><span>{a.name}</span><select aria-label="测试版本" value={version} onChange={e=>changeVersion(e.target.value)}>{a.versions.map(v=><option key={v.id} value={v.id}>V{v.id}</option>)}</select><button aria-label="协议执行范围" onClick={()=>setInfo(true)}><Info size={16}/></button></div>
 {tab==='版本管理'&&<div data-view="adapter-versions" className="business-two-panel"><div className="glass-business-panel"><div className="business-panel-label"><GitBranch size={18}/>版本差异<select aria-label="对比基线" value={baseline} onChange={e=>setBaseline(e.target.value)}>{a.versions.map(v=><option key={v.id} value={v.id}>基线 V{v.id}</option>)}</select></div><div className="adapter-diff">{versionDiff(base,v).map(d=><div key={d.field} className={d.changed?'changed':''}><small>{d.field}</small><span>{d.before}</span><ArrowRight size={16}/><strong>{d.after}</strong><em>{d.changed?'变更':'一致'}</em></div>)}</div></div><div className="glass-business-panel"><div className="adapter-version-path">{a.versions.map(v=><button key={v.id} aria-pressed={v.id===version} onClick={()=>changeVersion(v.id)}><GitBranch size={20}/><strong>V{v.id}</strong><span>{v.note}</span></button>)}</div><button onClick={()=>setTab('样例测试')}><Play size={15}/>测试此版本</button></div></div>}
 {tab==='样例测试'&&<div data-view="adapter-tests" className="business-two-panel"><div className="glass-business-panel"><div className="business-panel-label"><FileUp size={18}/>{file}<span>{new TextEncoder().encode(text).byteLength} B</span></div><div className="business-form-row"><button onClick={()=>{setText(protocolSample(a,v));setResult(null);setFile('正常样本')}}>正常样本</button><button onClick={()=>{setText(protocolSample(a,v,true));setResult(null);setFile('异常样本')}}>异常样本</button><label className="file-button">选择文件<input hidden type="file" accept=".json,.csv,.txt" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setTested('');if(f.size>262144){setResult({passed:false,errors:['文件超过 256 KB'],rows:[],total:0});return}try{setText(await f.text());setFile(f.name);setResult(null)}catch{setResult({passed:false,errors:['无法读取文件'],rows:[],total:0})}e.target.value=''}}/></label></div><div className="protocol-test-stages">{['格式识别','字段提取','单位换算','状态校验'].map((s,i)=><div key={s}><b>0{i+1}</b><span>{s}</span>{result?.passed&&<Check size={17}/>}</div>)}</div><div className="business-form-row"><button onClick={run}><Play size={15}/>执行解析</button><button onClick={()=>exportFile(a.id+'-样本.'+(a.format==='JSON'?'json':'csv'),text)}><Download size={15}/>下载样本</button></div></div><div className="glass-business-panel"><div className="business-panel-label">解析结果<span className={result&&!result.passed?'warn':'ok'}>{result?result.passed?'通过':'未通过':'待测试'}</span></div>{result?<><div className="business-key-readings"><span><b>{result.total}</b>输入</span><span><b>{result.rows.length}</b>通过</span><span><b>{result.total-result.rows.length}</b>异常</span></div>{result.errors.slice(0,6).map(e=><p className="test-error" key={e}>{e}</p>)}<div className="decoded-samples">{result.rows.slice(0,6).map((r,i)=><div key={i}><span>{r.device}<small>#{r.seq}</small></span><strong>{r.value.toFixed(3)} <small>{r.unit}</small></strong></div>)}</div>{result.passed&&<button onClick={()=>setTab('发布状态')}>选择生效设备 <ArrowRight size={15}/></button>}</>:<div className="protocol-await"><FileUp size={42}/><span>选择样本，执行解析</span></div>}</div></div>}
 {tab==='发布状态'&&<div data-view="adapter-releases" className="business-two-panel"><div className="glass-business-panel"><div className="business-panel-label"><Upload size={16}/>本地发布<span>{active?'V'+active.version:'未发布'}</span></div><div className="release-gates"><span className={pass?'ok':''}>{pass?<Check size={16}/>:<Play size={16}/>}版本测试</span><span>{scoped.length} / {compatible.length} 台</span></div><div className="release-targets">{compatible.map(d=><button key={d.id} aria-pressed={scoped.includes(d.id)} disabled={!cfg.allowed} onClick={()=>setTargets(scoped.includes(d.id)?targets.filter(x=>x!==d.id):[...targets,d.id])}><Radio size={17}/>{d.id}<small>{d.area}</small>{scoped.includes(d.id)&&<Check size={16}/>}</button>)}</div>{!compatible.length&&<p>当前范围没有匹配设备</p>}<div className="business-form-row"><button disabled={!pass||!scoped.length||!cfg.allowed} onClick={publish}>发布 V{version}</button>{!pass&&<button onClick={()=>setTab('样例测试')}>完成版本测试</button>}</div></div><div className="glass-business-panel"><h3>发布记录</h3><div className="adapter-release-history">{cfg.value.releases.map(r=><div key={r.id}><GitBranch size={17}/><span><strong>V{r.version} · {r.action}</strong><small>{r.time} · {r.targets.length} 台</small></span>{r.id===cfg.value.active?<em className="ok">当前</em>:<button disabled={!cfg.allowed||!r.targets.some(t=>compatible.some(d=>d.id===t))} onClick={()=>setConfirm(r)}><RotateCcw size={15}/>回滚</button>}</div>)}{!cfg.value.releases.length&&<span>暂无发布记录</span>}</div></div></div>}
 <footer className="business-console-status" role="status"><span>{cfg.notice}</span><span>{active?'当前配置 V'+active.version:'未发布'}</span></footer>
 {confirm&&<WorkspaceDrawer title="回滚协议配置" onClose={()=>setConfirm(null)}><p>恢复 V{confirm.version} 至 {confirm.targets.filter(t=>compatible.some(d=>d.id===t)).length} 台设备的本地配置。已有记录保留。</p><button disabled={!cfg.allowed} onClick={rollback}>确认回滚</button></WorkspaceDrawer>}
 {info&&<WorkspaceDrawer title="执行范围" onClose={()=>setInfo(false)}><p>解析测试在浏览器本地执行，支持 JSON 和简单无引号 CSV。发布与回滚仅保存本机配置记录，不向真实网关下发。版本测试通过后方可发布；切换版本或样本需重新测试。</p></WorkspaceDrawer>}</>
}
