import {useState} from 'react'
import {MineScene} from './MineScene'
import {platforms,platformTelemetry,observationFrame,sceneTime,type PlatformKind} from './sceneCatalog'
import type {Device} from './store'
export function ImageComparison(){const [split,setSplit]=useState(50);return <div className="image-comparison"><div className="compare-images"><img src="./scene-assets/mine-after.jpg" alt="宾厄姆峡谷 2013 年历史卫星影像"/><img src="./scene-assets/mine-before.jpg" alt="宾厄姆峡谷 2011 年历史航空影像" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}/><div className="compare-handle" style={{left:`${split}%`}}/><span>2011.07.20 / NAIP</span><span>2013.05.02 / EO-1</span></div><input aria-label="历史影像对比位置" type="range" min="0" max="100" value={split} onChange={e=>setSplit(+e.target.value)}/><small>独立历史案例：宾厄姆峡谷 · NASA Earth Observatory / NAIP · 非当前矿区实拍</small></div>}
export function InspectionFeed({kind,devices,frame}:{kind:PlatformKind;devices:Device[];frame:number}){
 const d=devices.find(d=>d.id===platforms[kind].id),t=platformTelemetry(kind,frame,d)
 return <div className="inspection-feed"><MineScene cinematic view="feed" devices={devices} frame={observationFrame(d,frame)} selected={platforms[kind].id} onSelect={()=>{}} layers={{paths:false,underground:false,coverage:false,sensors:false}}/><div className="feed-osd"><span>{kind==='drone'?'无人机':kind==='rover'?'雷达车':'深地站'}巡检 · 模拟</span><time>{sceneTime(observationFrame(d,frame))}</time>{!t.online?<span>链路离线 · 最后画面</span>:kind==='drone'&&<><span>高度 {t.altitude} m</span><span>速度 {t.speed} m/s</span></>}</div><div className="feed-crosshair"/></div>
}
export function TelemetryChart({kind,frame,mode='trend'}:{kind:PlatformKind;frame:number;mode?:'trend'|'spectrum'|'channels'}){
 const [picked,setPicked]=useState(-1);const points=Array.from({length:72},(_,i)=>{const value=mode==='spectrum'?Math.exp(-(((i-25)/9)**2))*95+Math.sin(i*1.7)*8:35+Math.sin(i*.24+frame*.07)*12+Math.cos(i*.71)*6+(kind==='deep'?Math.sin(i*2)*Math.exp(-(((i-38)/11)**2))*32:0);return [20+i*5.45,125-value]});
 return <div className="telemetry-chart"><svg viewBox="0 0 430 155" role="img" aria-label={mode==='spectrum'?'频谱样例':'遥测趋势样例'}>{[30,65,100,135].map(y=><path key={y} d={`M20 ${y}H415`} stroke="#345065" strokeWidth=".6"/>)}<path d={`M20 135L${points.map(p=>p.join(' ')).join('L')}L408 135Z`} fill="#4e9fc21a"/><polyline points={points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#83c7e5" strokeWidth="1.8"/>{mode==='channels'&&<polyline points={points.map(([x,y])=>`${x},${y*.7+40}`).join(' ')} fill="none" stroke="#dfb57e" strokeWidth="1.2"/>}{points.filter((_,i)=>i%6===0).map(([x,y],i)=><g key={i} role="button" tabIndex={0} aria-label={`查看第 ${i+1} 组样本`} onClick={()=>setPicked(i)} onKeyDown={e=>e.key==='Enter'&&setPicked(i)}><circle cx={x} cy={y} r="12" fill="transparent"/><circle cx={x} cy={y} r={picked===i?4:2} fill="#a6d5e8"/></g>)}<text x="20" y="151" fill="#90aabc" fontSize="10">{mode==='spectrum'?'0 Hz':'09:00'}</text><text x="370" y="151" fill="#90aabc" fontSize="10">{mode==='spectrum'?'250 Hz':'10:00'}</text></svg><small>{picked<0?'点击采样点查看样例值':`样本 ${picked+1} · 幅值 ${(135-points[picked*6][1]).toFixed(2)} a.u. · ${sceneTime(frame)}`}</small></div>
}
