import {RotationControl} from './RotationControl'
import {useAutoOrbit} from './useAutoOrbit'
import { useEffect, useId, useRef, useState, type PointerEvent } from 'react'
import { RotateCcw, Rotate3D, Layers3, Play, Minus, Plus } from 'lucide-react'
import { hardwareModels, type SensorFamily, type HardwarePart } from './hardware'
type Point=[number,number,number]
export function SensorScene({family='gnss',selected='',onSelect,compact=false,faultPart='',exploded=true,thumbnail=false,cinematic=false}:{cinematic?:boolean;thumbnail?:boolean;family?:SensorFamily;selected?:string;onSelect?:(id:string)=>void;compact?:boolean;faultPart?:string;exploded?:boolean}){
 const model=hardwareModels[family],id=useId().replaceAll(':',''),[spread,setSpread]=useState(exploded?65:0),[current,setCurrent]=useState(0),[yaw,setYaw]=useState(-.52),[pitch,setPitch]=useState(.62),[zoom,setZoom]=useState(1),[flow,setFlow]=useState(true)
 const drag=useRef<{x:number;y:number;yaw:number;pitch:number;moved:boolean}|null>(null),pose=useRef(0),dragged=useRef(false)
 useEffect(()=>{let handle=0;const step=()=>{const diff=spread-pose.current;pose.current=Math.abs(diff)<.15?spread:pose.current+diff*.12;setCurrent(pose.current);if(pose.current!==spread)handle=requestAnimationFrame(step)};handle=requestAnimationFrame(step);return()=>cancelAnimationFrame(handle)},[spread])
 const orbitHost=useAutoOrbit(setYaw,drag)
 useEffect(()=>{setSpread(exploded?65:0)},[family,exploded])
 const zOf=(p:HardwarePart,i:number)=>p.z+(model.parts.length-1-i)*current*.33
 const project=([x,y,z]:Point)=>{const u=x*Math.cos(yaw)-y*Math.sin(yaw),v=x*Math.sin(yaw)+y*Math.cos(yaw);return [330+u*1.7*zoom,352+(v*Math.sin(pitch)-z*Math.cos(pitch))*1.25*zoom]}
 const depth=([x,y,z]:Point)=>((x*Math.sin(yaw)+y*Math.cos(yaw))*Math.cos(pitch)+z*Math.sin(pitch))
 const poly=(pts:Point[])=>pts.map(p=>project(p).join(',')).join(' ')
 const faceData=model.parts.flatMap((p,i)=>{const z=zOf(p,i),corners:[number,number][]=p.shape==='cylinder'?Array.from({length:32},(_,j)=>[Math.cos(j*Math.PI/16)*p.width/2,Math.sin(j*Math.PI/16)*p.depth/2]):[[-p.width/2,-p.depth/2],[p.width/2,-p.depth/2],[p.width/2,p.depth/2],[-p.width/2,p.depth/2]];const top:Point[]=corners.map(c=>[...c,z+p.height]);return [...corners.map((c,j)=>{const next=corners[(j+1)%corners.length],pts:Point[]=[[...c,z],[...next,z],[...next,z+p.height],[...c,z+p.height]];return {part:p,points:pts,side:true,depth:pts.reduce((s,p)=>s+depth(p),0)/4,shade:.58+(j/corners.length)*.35}}),{part:p,points:top,side:false,depth:top.reduce((s,p)=>s+depth(p),0)/top.length,shade:1}]})
 const sorted=faceData.sort((a,b)=>a.depth-b.depth)
 const choose=(partId:string)=>{if(!dragged.current)onSelect?.(partId)}
 const down=(e:PointerEvent<SVGSVGElement>)=>{if(e.button!==0)return;dragged.current=false;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,yaw,pitch,moved:false}}
 return <div ref={orbitHost} className={`sensor-scene ${compact?'compact':''} ${cinematic?'sensor-cinematic':''}`}>
 {!compact&&<div className="sensor-scene-tools"><div className="sensor-tool-left"><RotationControl/><button aria-pressed={spread>0} onClick={()=>setSpread(spread>0?0:80)}><Layers3 size={13}/>{spread>0?'收拢':'展开'}</button><button className={flow?'active':''} onClick={()=>setFlow(v=>!v)}><Play size={13}/>信号路径</button></div><div className="sensor-tool-right"><button aria-label="缩小模型" onClick={()=>setZoom(v=>Math.max(.65,v-.1))}><Minus size={13}/></button><button aria-label="放大模型" onClick={()=>setZoom(v=>Math.min(1.35,v+.1))}><Plus size={13}/></button><button onClick={()=>{setYaw(-.52);setPitch(.62);setZoom(1);setSpread(65)}}><RotateCcw size={13}/>复位</button></div></div>}
 <svg viewBox={thumbnail?"175 115 310 320":"0 0 660 490"} aria-label={`${model.title}交互爆炸图`} role="img" onPointerDown={down} onPointerMove={e=>{const d=drag.current;if(!d)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>4)d.moved=true;if(d.moved){setYaw(d.yaw+(e.clientX-d.x)*.008);setPitch(Math.max(.25,Math.min(1.05,d.pitch+(e.clientY-d.y)*.005)))}}} onPointerUp={e=>{dragged.current=!!drag.current?.moved;drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>drag.current=null}>
 <defs><radialGradient id={`${id}halo`}><stop stopColor="#4f839a" stopOpacity=".28"/><stop offset="1" stopColor="#112432" stopOpacity="0"/></radialGradient><pattern id={`${id}grid`} width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="#527281" strokeWidth=".4" opacity=".22"/></pattern><linearGradient id={`${id}metal`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#e5eef1"/><stop offset=".5" stopColor="#a5bdc9"/><stop offset="1" stopColor="#678b9f"/></linearGradient></defs>
 <rect width="660" height="490" fill={`url(#${id}grid)`}/><ellipse cx="330" cy="367" rx="260" ry="126" fill={`url(#${id}halo)`}/><ellipse cx="330" cy="381" rx="170" ry="44" fill="none" stroke="#416176" opacity=".5"/><ellipse cx="330" cy="381" rx="210" ry="56" fill="none" stroke="#416176" opacity=".18"/>
 <text x="26" y="33" fill="#7696a9" fontSize="11" letterSpacing="2">KUANGDA / {family.toUpperCase()}</text><text x="26" y="51" fill="#4f7185" fontSize="10">概念工业结构 · 非真实硬件 CAD</text>
 {sorted.map((face,i)=><polygon key={i} className="sensor-part-face" points={poly(face.points)} fill={face.part.id===faultPart?'#be7750':face.part.shape==='pcb'?face.part.color:face.side?face.part.color:`url(#${id}metal)`} stroke={face.part.id===selected?'#89d4e0':face.part.id===faultPart?'#f3b978':'#b8d3e140'} strokeWidth={face.part.id===selected?1.8:.55} opacity={selected&&face.part.id!==selected? .64:1} style={{filter:face.side?`brightness(${face.shade})`:undefined}} onClick={()=>choose(face.part.id)}/>)}
 {model.parts.map((p,i)=>{const z=zOf(p,i)+p.height+1;return <g key={p.id} onClick={()=>choose(p.id)}>{p.shape==='pcb'&&<>{Array.from({length:family==='daq'?12:6},(_,j)=>{const x=-p.width*.32+(j%4)*p.width*.21,y=-p.depth*.27+Math.floor(j/4)*p.depth*.23;return <g key={j}><polygon points={poly([[x,y,z],[x+13,y,z],[x+13,y+10,z],[x,y+10,z]])} fill="#182a32" stroke="#82a697" strokeWidth=".5"/><path d={`M${project([x+6,y+11,z]).join(' ')} L${project([x+6,y+17,z]).join(' ')}`} fill="none" stroke="#bbbd72" strokeWidth="1.1"/></g>})}{[-1,1].map(side=><g key={side}>{Array.from({length:8},(_,j)=><polygon key={j} points={poly([[side*p.width*.47,-p.depth*.35+j*5,z],[side*p.width*.40,-p.depth*.35+j*5,z],[side*p.width*.40,-p.depth*.35+j*5+2,z],[side*p.width*.47,-p.depth*.35+j*5+2,z]])} fill="#d9bb67"/>)}</g>)}</>}{p.shape==='cylinder'&&p.id.includes('sensor')&&Array.from({length:7},(_,j)=><polyline key={j} points={poly(Array.from({length:33},(_,n)=>[Math.cos(n*Math.PI/16)*p.width/2,Math.sin(n*Math.PI/16)*p.depth/2,z-j*2]))} fill="none" stroke="#e8b875" strokeWidth=".6" opacity=".5"/>)}{p.shape==='box'&&p.id==='power'&&Array.from({length:3},(_,j)=><polygon key={j} points={poly([[-p.width/3+j*22,-p.depth*.3,z],[-p.width/3+14+j*22,-p.depth*.3,z],[-p.width/3+14+j*22,p.depth*.3,z],[-p.width/3+j*22,p.depth*.3,z]])} fill="#2b434f" stroke="#8babb940"/>)}
 </g>})}
 {flow&&model.parts.slice(1).map((p,i)=>{const a=project([0,0,zOf(model.parts[i],i)]),b=project([0,0,zOf(p,i+1)+p.height]);return <path key={p.id} className="signal-pulse" d={`M${a.join(' ')} L${b.join(' ')}`} fill="none" stroke={faultPart?'#d89958':'#67c7c4'} strokeDasharray="3 8" strokeWidth="1.5" opacity=".9"/>})}
 {model.parts.map((p,i)=>{const anchor=project([p.width*.48,0,zOf(p,i)+p.height/2]),right=i%2===0,labelX=right?517:22,labelY=95+i*53;return (!cinematic||selected===p.id)&&<g key={p.id} role="button" aria-label={`查看部件${p.name}`} tabIndex={0} className="sensor-part-label" onPointerDown={e=>e.stopPropagation()} onClick={()=>onSelect?.(p.id)} onKeyDown={e=>e.key==='Enter'&&onSelect?.(p.id)}><path d={`M${anchor.join(' ')} L${right?496:164} ${labelY} H${right?515:147}`} fill="none" stroke={selected===p.id?'#81d2db':'#446a7e'} strokeWidth=".8"/><circle cx={anchor[0]} cy={anchor[1]} r="3" fill={faultPart===p.id?'#e8b36a':'#69a5b5'}/><rect x={labelX-5} y={labelY-17} width="126" height="38" rx="4" fill={selected===p.id?'#274755':'#132c3b'} stroke={selected===p.id?'#73b9c8':'#294653'}/><text x={labelX+4} y={labelY-2} fill="#c1d7e3" fontSize="11">{p.name}</text><text x={labelX+4} y={labelY+12} fill={faultPart===p.id?'#e6ab67':'#5e8596'} fontSize="9">{faultPart===p.id?'异常 · 点击诊断':`0${i+1} / 查看运行状态`}</text></g>})}
 <text x="28" y="459" fill="#517b91" fontSize="10">X ─ E　/　Z ↑</text><text x="632" y="459" textAnchor="end" fill="#688d9e" fontSize="10">拖动旋转 · 点选部件</text>
 </svg>

 </div>
}
