import { useEffect, useState } from 'react'
import { moduleCatalog, widgetCatalog, widgetCategoryOrder } from '../data/catalog'
import {Download,FileText,FolderTree,Search,Check} from 'lucide-react'
import {WorkbenchStatus} from './ScientificUI'
import { escapeHTML, exportFile, useDemo } from './store'
export function SolutionStudio(){
 const {can}=useDemo(),[selected,setSelected]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('kuangda-solution-v3')||'null')||['siteMap','deviceOnline','deviceLedger','algorithm-taup','algorithm-multi-risk','riskReport']}catch{return[]}}),[category,setCategory]=useState('全部'),[query,setQuery]=useState(''),[name,setName]=useState('矿大 · 北帮边坡综合监测项目'),[tab,setTab]=useState('功能选配')
 useEffect(()=>localStorage.setItem('kuangda-solution-v3',JSON.stringify(selected)),[selected])
 const modules=widgetCatalog.filter(w=>selected.includes(w.kind)),algorithms=modules.filter(w=>w.moduleId),dependencies=[...new Set(algorithms.flatMap(w=>moduleCatalog.find(m=>m.id===w.moduleId)?.dependencyIds||[]))]
 const config={customer:'矿大',project:name,mode:'offline-demo',components:modules.map(w=>({id:w.kind,name:w.name,category:w.category,features:w.features||[]})),dependencies,scope:'不含真实设备接入、身份认证及工程算法求解'}
 const html=()=>`<!DOCTYPE html><meta charset="utf-8"><title>${escapeHTML(name)}</title><style>body{font:14px/1.8 sans-serif;max-width:1000px;margin:50px auto;color:#203c57}h1{border-bottom:3px solid #1b58a1}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ccd9e5;padding:10px;text-align:left}</style><h1>${escapeHTML(name)} · 功能方案</h1><p>客户：矿大 / 已选 ${modules.length} 项能力，其中算法 ${algorithms.length} 项。</p><h2>功能与实施工作包</h2><table><tr><th>类别</th><th>模块</th><th>工作范围</th></tr>${modules.map(w=>`<tr><td>${w.category}</td><td>${escapeHTML(w.name)}</td><td>${escapeHTML(w.description)}<br>${escapeHTML(w.features?.join('、')||'查询、交互、成果展示')}</td></tr>`).join('')}</table><h2>依赖与联调</h2><p>${dependencies.map(d=>escapeHTML(moduleCatalog.find(m=>m.id===d)?.name||d)).join('、')||'基础设备、空间对象与标准数据接口'}</p><h2>实施阶段</h2><ol><li>数据标准、设备协议与场景确认</li><li>算法接口、参数约束与验证样例</li><li>业务闭环、角色权限与集成联调</li><li>性能验证、现场试运行与验收交付</li></ol><h2>交付边界</h2><p>${config.scope}。工期与报价需依据协议数量、数据质量、算法成熟度和验收指标单独评估。</p>`
 return <div className="solution-workbench glass-solution"><header className="product-section-heading"><div><h1>客户方案</h1></div><div className="glass-analysis-actions"><button onClick={()=>exportFile('矿大-方案配置.json',JSON.stringify(config,null,2))}><Download size={15}/>配置</button><button onClick={()=>exportFile('矿大-客户功能方案.html',html(),'text/html')}><FileText size={15}/>导出方案</button></div></header>
 <div className="glass-solution-heading"><label>项目名称<input aria-label="项目名称" value={name} onChange={e=>setName(e.target.value)}/></label><div className="glass-solution-counts"><span><b>{modules.length}</b>功能</span><span><b>{algorithms.length}</b>算法</span><span><b>{dependencies.length}</b>依赖</span></div></div>
 <div className="product-subnav">{['功能选配','交付预览','依赖与工作包'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='功能选配'?<><div className="haze-library-tools"><label><Search size={15}/><input aria-label="搜索组件功能" placeholder="搜索功能" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="方案功能分类" value={category} onChange={e=>setCategory(e.target.value)}>{['全部',...widgetCategoryOrder].map(c=><option key={c}>{c}</option>)}</select><button disabled={!can('config')} onClick={()=>setSelected(widgetCatalog.map(w=>w.kind))}>全选</button><button disabled={!can('config')} onClick={()=>setSelected([])}>清空</button></div><div className="solution-grid">{widgetCatalog.filter(w=>(category==='全部'||category===w.category)&&`${w.name}${w.description}`.toLowerCase().includes(query.toLowerCase())).map(w=><label key={w.kind} className={selected.includes(w.kind)?'selected':''} title={w.description}><input type="checkbox" checked={selected.includes(w.kind)} disabled={!can('config')} onChange={e=>setSelected(v=>e.target.checked?[...new Set([...v,w.kind])]:v.filter(x=>x!==w.kind))}/><div><small>{w.category}</small><strong>{w.name}</strong></div>{selected.includes(w.kind)&&<Check size={14}/>}</label>)}</div></>:tab==='交付预览'?<div className="glass-solution-preview">{modules.length?widgetCategoryOrder.filter(c=>modules.some(w=>w.category===c)).map(c=><section key={c}><header><FolderTree size={17}/><h2>{c}</h2><small>{modules.filter(w=>w.category===c).length}</small></header>{modules.filter(w=>w.category===c).map(w=><details key={w.kind}><summary>{w.name}</summary><p>{w.features?.join('、')||w.description}</p></details>)}</section>):<div className="empty">请先选择功能。</div>}</div>:<><section className="dependency-panel"><h2>上游依赖</h2><div className="chips">{dependencies.map(d=><span key={d}>{moduleCatalog.find(m=>m.id===d)?.name||d}</span>)}</div>{!dependencies.length&&<p>设备、空间对象与标准数据接口</p>}</section><div className="work-package-grid">{['设备协议与数据标准','算法实现与科学验证','业务流程与权限','现场联调与验收'].map((title,i)=><article key={title}><small>0{i+1}</small><h3>{title}</h3><p>{['协议梳理、字段映射、采样时钟、补传与异常隔离。','输入约束、数值求解、计算调度、基准样例与不确定性。','配置版本、数据范围、审批留痕、风险闭环与报告。','环境适配、负载测试、现场标定、用户培训与验收指标。'][i]}</p></article>)}</div><details className="glass-scope"><summary>交付范围</summary><p>{config.scope}。工期与报价以接口、数据质量及验收指标确认为准。</p></details></>}
 <WorkbenchStatus><span>{can('config')?'可编辑':'只读'}</span><span>已选 {modules.length} / {widgetCatalog.length}</span><span>选配自动保存</span></WorkbenchStatus></div>
}
