import {SpacOverview} from './SpacOverview'
import {useEffect,useRef,useState,type ReactNode} from 'react'
import {Activity,ArrowLeft,Check,ChevronDown,Download,FileText,FolderOpen,Grid2X2,HelpCircle,Home,MousePointer2,Play,Plus,RotateCcw,Save,Settings2,Square,Target,Undo2,Ellipsis,SlidersHorizontal,Pin,X,ZoomIn,ZoomOut} from 'lucide-react'
import {useDemo,exportFile,exportCSV} from './store'
import {goWorkspace} from './navigation'
import {SpacPlot,type SpacView,type PickMode} from './SpacPlot'
import {addSpacPick,computeSpac,energyAt,fitSpacPicks,spacDatasets,spacDefaults,spacSource,validateSpac,validateSpacPicks,type SpacPick,type SpacRequest,type SpacResult} from './spacSampleEngine'
import {ScienceIcon,Modal} from './DesktopControls'

const KEY='kuangda-spac-workbench-v1'
type DialogName='data'|'params'|'array'|'help'|'point'|'replace'|null
function restore(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.schema===1){validateSpac(saved.request);return {request:saved.request as SpacRequest,picks:validateSpacPicks(saved.picks,saved.request),saved:true}}}catch{/* Retain corrupt storage; start an independent sample. */}return {request:{dataset:'SPAC-A01',params:{...spacDefaults}},picks:[],saved:false}}

export function SpacWorkbench({deviceId}:{deviceId?:string}){
 const {can,visibleDevices}=useDemo(),allowed=can('algorithm'),[initial]=useState(restore)
 const [draft,setDraft]=useState<SpacRequest>(initial.request),[result,setResult]=useState<SpacResult>(()=>computeSpac(initial.request)),[picks,setPicks]=useState<SpacPick[]>(initial.picks),[history,setHistory]=useState<SpacPick[][]>([]),[selected,setSelected]=useState(-1),[view,setView]=useState<SpacView>('频散能量'),[mode,setMode]=useState<PickMode>('inspect'),[menu,setMenu]=useState(''),[dialog,setDialog]=useState<DialogName>(null),[candidate,setCandidate]=useState(initial.request.dataset),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState(''),[saved,setSaved]=useState(initial.saved),[grid,setGrid]=useState(true),[crosshair,setCrosshair]=useState(true),[showPicks,setShowPicks]=useState(true),[showFit,setShowFit]=useState(false),[zoom,setZoom]=useState(1),[pan,setPan]=useState(0),[palette,setPalette]=useState('雾蓝'),[cursor,setCursor]=useState<SpacPick|null>(null),[numeric,setNumeric]=useState<SpacPick>({f:8,c:400})
 const [overview,setOverview]=useState(true)
 const canvas=useRef<HTMLCanvasElement>(null),worker=useRef<Worker|null>(null),file=useRef<HTMLInputElement>(null)
 const data=spacDatasets.find(d=>d.id===result.request.dataset)!,changed=JSON.stringify(draft)!==JSON.stringify(result.request),associated=visibleDevices.find(d=>d.id===deviceId),fit=fitSpacPicks(picks)
 useEffect(()=>()=>worker.current?.terminate(),[])
 const close=()=>{setDialog(null);setMenu('')},resetView=()=>{setZoom(1);setPan(0);setCursor(null)}
 const editPicks=(next:SpacPick[])=>{if(!allowed||busy||changed)return;setHistory(h=>[...h,picks].slice(-40));setPicks(next);setSaved(false);setSelected(-1)}
 const undo=()=>{if(!history.length||!allowed||busy||changed)return;setPicks(history.at(-1)!);setHistory(h=>h.slice(0,-1));setSaved(false);setSelected(-1)}
 const point=(v:SpacPick)=>{if(mode==='add')editPicks(addSpacPick(picks,v));else if(picks.length){let nearest=0;picks.forEach((p,i)=>{if(Math.hypot((p.f-v.f)/30,(p.c-v.c)/1000)<Math.hypot((picks[nearest].f-v.f)/30,(picks[nearest].c-v.c)/1000))nearest=i});if(mode==='delete'&&Math.hypot((picks[nearest].f-v.f)/30,(picks[nearest].c-v.c)/1000)<.04)editPicks(picks.filter((_,i)=>i!==nearest));else setSelected(nearest)}}
 const serialize=()=>({schema:1,request:result.request,picks,source:spacSource,engineVersion:result.version})
 const save=()=>{if(!allowed||changed||busy)return;try{localStorage.setItem(KEY,JSON.stringify(serialize()));setSaved(true);setMessage('处理配置与拾取点已保存。')}catch{setMessage('本地保存失败，请导出项目配置。')}}
 const exportConfig=()=>exportFile(`${data.id}.spacproj.json`,JSON.stringify(serialize(),null,2))
 const exportPicks=()=>exportCSV(`${data.id}-拾取.csv`,['频率(Hz)','相速度(m/s)','波长(m)','匹配度'],picks.map(v=>[v.f,v.c,+(v.c/v.f).toFixed(3),+energyAt(result,v).toFixed(4)]))
 const exportPlot=()=>{const el=canvas.current;if(!el)return;exportFile(`${data.id}-${view}.svg`,`<svg xmlns="http://www.w3.org/2000/svg" width="${el.width}" height="${el.height}" viewBox="0 0 ${el.width} ${el.height}"><image width="100%" height="100%" href="${el.toDataURL('image/png')}"/></svg>`,'image/svg+xml')}
 const run=(request=draft)=>{if(!allowed||busy)return;try{validateSpac(request)}catch(e){setMessage((e as Error).message);return}setDialog(null);setMenu('');setBusy(true);setProgress(0);setMessage('');worker.current?.terminate();const w=new Worker(new URL('./spacSample.worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{if(e.data.progress!==undefined)setProgress(e.data.progress);if(e.data.result){setResult(e.data.result);setDraft(e.data.result.request);setPicks([]);setHistory([]);setSelected(-1);setSaved(false);setBusy(false);setView('频散能量');setMode('inspect');resetView();w.terminate();worker.current=null}if(e.data.error){setBusy(false);setMessage(e.data.error);w.terminate();worker.current=null}};w.onerror=()=>{setBusy(false);setMessage('计算未完成，原结果保持不变。');w.terminate();worker.current=null};w.postMessage(request)}
 const requestRun=()=>{try{validateSpac(draft);picks.length?setDialog('replace'):run()}catch(e){setMessage((e as Error).message)}}
 const stop=()=>{worker.current?.terminate();worker.current=null;setBusy(false);setMessage('已停止，保留上次计算结果。')}
 const chooseMode=(value:PickMode)=>{setOverview(false);setMode(value);setView('频散能量');setMenu('')}
 const setParam=<K extends keyof SpacRequest['params']>(key:K,value:SpacRequest['params'][K])=>{setDraft(v=>({...v,params:{...v.params,[key]:value}}));setSaved(false)}
 const menuItems:Record<string,{name:string;run:()=>void;disabled?:boolean}[]>={
  '文件':[{name:'打开内置数据…',run:()=>{setCandidate(draft.dataset);setDialog('data')},disabled:!allowed||busy},{name:'打开项目配置…',run:()=>file.current?.click(),disabled:!allowed||busy},{name:'保存项目',run:save,disabled:!allowed||changed||busy},{name:'导出项目配置',run:exportConfig,disabled:busy||changed},{name:'返回算法目录',run:()=>goWorkspace({page:'algorithm'})}],
  '观测系统':[{name:'查看台阵布设',run:()=>{setOverview(false);setView('观测阵列')}},{name:'观测参数…',run:()=>setDialog('array')},{name:'通道波形',run:()=>{setOverview(false);setView('波形')}}],
  '预处理':[{name:'波形预览',run:()=>{setOverview(false);setView('波形')}},{name:'去趋势 / 归一化…',run:()=>setDialog('params')}],
  '频散分析':[{name:'分析参数…',run:()=>setDialog('params')},{name:'运行 SPAC',run:requestRun,disabled:!allowed||busy},{name:'空间自相关曲线',run:()=>{setOverview(false);setView('自相关')}},{name:'频散能量图',run:()=>{setOverview(false);setView('频散能量')}}],
  '拾取':[{name:'添加拾取点',run:()=>chooseMode('add'),disabled:!allowed||changed||busy},{name:'数值拾取…',run:()=>{setNumeric({f:8,c:400});setDialog('point')},disabled:!allowed||changed||busy},{name:'删除拾取点',run:()=>chooseMode('delete'),disabled:!allowed||!picks.length||changed||busy},{name:'撤销',run:undo,disabled:!allowed||!history.length||changed||busy},{name:'拾取结果',run:()=>{setOverview(false);setView('拾取结果')}}],
  '显示':[{name:'复位视图',run:resetView},{name:grid?'隐藏网格':'显示网格',run:()=>setGrid(v=>!v)},{name:crosshair?'关闭十字线':'显示十字线',run:()=>setCrosshair(v=>!v)},{name:'导出当前图面',run:exportPlot,disabled:view==='拾取结果'}],
  '帮助':[{name:'操作与数据来源',run:()=>setDialog('help')}],
 }
 return <section className="glass-spac" aria-label="SPAC 频散分析工作区">
 <header className="lab-header"><div className="lab-title-block"><button aria-label="返回算法目录" onClick={()=>goWorkspace({page:'algorithm'})}><ArrowLeft size={17}/></button><h1>SPAC 频散分析</h1></div><div className="glass-analysis-actions" aria-label="SPAC 分析工具"><button aria-pressed={!overview} onClick={()=>setOverview(v=>!v)}>{overview?'专业分析':'成果视景'}</button><button onClick={()=>setDialog('params')}><SlidersHorizontal size={15}/>参数</button>{busy?<button onClick={stop}><Square size={15}/>停止 {progress}%</button>:<button className="primary" disabled={!allowed} onClick={requestRun}><Play size={15}/>运行</button>}<button disabled={!allowed||busy||changed} onClick={save}><Save size={15}/>{saved?'已保存':'保存'}</button><details className="lab-more glass-spac-more"><summary aria-label="更多 SPAC 操作"><Ellipsis size={19}/></summary><div onClick={e=>{if((e.target as HTMLElement).closest('button'))e.currentTarget.parentElement?.removeAttribute('open')}}>{Object.entries(menuItems).map(([name,items])=><section key={name}><small>{name}</small>{items.map(item=><button key={item.name} disabled={item.disabled} onClick={item.run}>{item.name}</button>)}</section>)}</div></details></div></header>
 <div className="lab-outcome-bar"><div className="lab-outcome-context"><button disabled={!allowed||busy} onClick={()=>{setCandidate(draft.dataset);setDialog('data')}}><FolderOpen size={14}/>{data.id}</button>{associated&&<button onClick={()=>goWorkspace({page:'device',id:associated.id})}>{associated.id}</button>}<button title="数据与方法" aria-label="SPAC 数据与方法" onClick={()=>setDialog('help')}><HelpCircle size={14}/></button></div><div className="lab-outcome-metrics"><span><small>通道</small><b>{data.channels}</b></span><span><small>采样率</small><b>{data.sampleRate}</b><em>Hz</em></span><span><small>时长</small><b>{data.duration}</b><em>s</em></span></div></div>
 {overview?<SpacOverview result={result} onInspect={v=>{setView(v);setOverview(false)}}/>:<><div className="glass-spac-viewbar"><div className="glass-view-tabs" role="tablist" aria-label="SPAC 成果视图">{(['频散能量','波形','自相关','观测阵列','拾取结果'] as SpacView[]).map(v=><button key={v} role="tab" aria-selected={view===v} onClick={()=>{setView(v);setCursor(null)}}>{v}</button>)}</div><div className="glass-analysis-actions"><button aria-pressed={mode==='add'} disabled={!allowed||changed||busy} onClick={()=>chooseMode(mode==='add'?'inspect':'add')}><Pin size={14}/>拾取</button><button title="撤销拾取" aria-label="撤销拾取" disabled={!allowed||!history.length||changed||busy} onClick={undo}><Undo2 size={15}/></button><details className="lab-more"><summary aria-label="拾取与图层"><Settings2 size={16}/></summary><div><button disabled={!allowed||!picks.length||changed||busy} onClick={()=>chooseMode('delete')}>删除拾取点</button><button disabled={!allowed||changed||busy} onClick={()=>setDialog('point')}>数值拾取</button><button disabled={!picks.length} onClick={exportPicks}>导出拾取数据</button><label><input type="checkbox" checked={showPicks} onChange={e=>setShowPicks(e.target.checked)}/>拾取点</label><label><input type="checkbox" checked={showFit} disabled={fit.length===0} onChange={e=>setShowFit(e.target.checked)}/>拟合曲线</label></div></details></div></div>
 {changed&&<div className="spac-pending"><span>参数已修改 · 图面仍为上次结果</span><button disabled={busy} onClick={()=>setDraft(structuredClone(result.request))}>撤回修改</button><button disabled={busy||!allowed} onClick={requestRun}>重新计算</button></div>}
 {message&&<div className="spac-notification" role="status">{message}<button aria-label="关闭提示" onClick={()=>setMessage('')}><X size={13}/></button></div>}
 <div className="spac-workspace"><div className="spac-figure-head"><strong>{view==='频散能量'?'频散能量图':view==='自相关'?'空间自相关曲线':view==='波形'?'多通道波形':view==='观测阵列'?'台阵布设':'拾取数据'}</strong><span>{view==='频散能量'?'SPAC':view==='波形'?'预览 0–8 s':data.id}</span><div className="spac-plot-tools">{view==='频散能量'&&<><select aria-label="图面配色" value={palette} onChange={e=>setPalette(e.target.value)}>{['雾蓝','蓝黄','彩虹','灰度'].map(v=><option key={v}>{v}</option>)}</select><button aria-label="复位图面" title="复位" onClick={resetView}><Home size={17}/></button><button aria-label="放大频率轴" title="放大频率轴" disabled={zoom>=4} onClick={()=>{setZoom(v=>Math.min(4,v+1));setPan(0)}}><ZoomIn size={17}/></button><button aria-label="缩小频率轴" title="缩小频率轴" disabled={zoom===1} onClick={()=>{setZoom(v=>Math.max(1,v-1));setPan(0)}}><ZoomOut size={17}/></button><i/><button aria-label="浏览图面" title="浏览" aria-pressed={mode==='inspect'} onClick={()=>setMode('inspect')}><MousePointer2 size={16}/></button><button aria-label="十字线" title="十字线" aria-pressed={crosshair} onClick={()=>setCrosshair(v=>!v)}><Target size={16}/></button></>}{view!=='拾取结果'&&<button aria-label="坐标网格" title="坐标网格" aria-pressed={grid} onClick={()=>setGrid(v=>!v)}><Grid2X2 size={16}/></button>}<button aria-label="图面导出" title="导出图面" disabled={view==='拾取结果'} onClick={exportPlot}><Download size={16}/></button></div></div>
 {view==='拾取结果'?<div className="spac-pick-table"><div><span>{picks.length} 个拾取点</span><button disabled={!allowed||selected<0||changed||busy} onClick={()=>editPicks(picks.filter((_,i)=>i!==selected))}>删除选中</button><button disabled={!picks.length} onClick={exportPicks}>导出 CSV</button></div><table><thead><tr><th>序号</th><th>频率 / Hz</th><th>相速度 / m·s⁻¹</th><th>波长 / m</th><th>匹配度</th></tr></thead><tbody>{picks.map((v,i)=><tr key={i} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><td><button aria-label={`选择拾取点 ${i+1}`} onClick={()=>setSelected(i)}>{i+1}</button></td><td>{v.f.toFixed(3)}</td><td>{v.c.toFixed(2)}</td><td>{(v.c/v.f).toFixed(2)}</td><td>{energyAt(result,v).toFixed(4)}</td></tr>)}</tbody></table>{!picks.length&&<p>点击“拾取”在能量图上添加点，或使用“数值”输入坐标。</p>}</div>:<SpacPlot result={result} view={view} picks={picks} selected={selected} mode={changed||busy||!allowed?'inspect':mode} grid={grid} crosshair={crosshair} showPicks={showPicks} showFit={showFit} zoom={zoom} pan={pan} palette={palette} onPoint={point} onCursor={setCursor} canvasRef={canvas}/>}
 {view==='频散能量'&&zoom>1&&<div className="spac-pan"><span>频率轴 {zoom}×</span><input aria-label="平移频率轴" type="range" min="0" max="1" step=".01" value={pan} onChange={e=>setPan(+e.target.value)}/></div>}
 </div>
 </>}
 <footer className="glass-workspace-status spac-readout"><span className="spac-ready">{busy?<span className="spac-progress"><i style={{width:progress+'%'}}/></span>:<Check size={13}/>} {busy?`计算中 ${progress}%`:changed?'待重新计算':saved?'已保存':'就绪'}</span><span>频率 <output>{cursor?cursor.f.toFixed(2):'—'} Hz</output></span><span>相速度 <output>{cursor?cursor.c.toFixed(1):'—'} m/s</output></span><span>波长 <output>{cursor?(cursor.c/cursor.f).toFixed(1):'—'} m</output></span><div><span>{allowed?'内置数据':'只读 · 内置数据'}</span><button onClick={()=>setDialog('help')} aria-label="SPAC 操作帮助"><HelpCircle size={13}/>帮助</button></div></footer>
 <input ref={file} hidden type="file" accept=".json" aria-label="打开 SPAC 项目配置文件" onChange={async e=>{const el=e.currentTarget,f=el.files?.[0];if(!f)return;try{if(!allowed||busy)throw Error('当前不能导入。');if(f.size>1024*1024)throw Error('配置文件不能超过 1 MB。');const v=JSON.parse(await f.text());if(v.schema!==1)throw Error('仅支持本工具导出的 SPAC 项目配置。');validateSpac(v.request);const points=validateSpacPicks(v.picks,v.request),out=computeSpac(v.request);setDraft(v.request);setResult(out);setPicks(points);setHistory([]);setSaved(false);setSelected(-1);resetView();setMessage('已打开项目配置。')}catch(e){setMessage('打开失败：'+(e as Error).message)}finally{el.value=''}}}/>
 {dialog==='data'&&<Modal title="打开数据" onClose={close} footer={<><button onClick={close}>取消</button><button disabled={!allowed||busy} onClick={()=>{setDraft(v=>({...v,dataset:candidate}));setDialog(null);setMessage('已选择数据，请运行以更新图面。')}}>打开</button></>}><div className="spac-data-choices">{spacDatasets.map(d=><button key={d.id} className={candidate===d.id?'selected':''} onClick={()=>setCandidate(d.id)}><ScienceIcon kind="wave"/><span><strong>{d.name}</strong><small>{d.id} · {d.channels} 通道 · {d.sampleRate} Hz · {d.duration} s</small></span></button>)}</div><p className="spac-dialog-note">内置合成数据。切换后，原图面和拾取点保留至重新计算。</p></Modal>}
 {dialog==='params'&&<Modal title="SPAC 分析参数" onClose={close} footer={<><button onClick={close}>关闭</button><button disabled={!allowed||busy} onClick={()=>{setDraft(v=>({...v,params:{...spacDefaults}}))}}>默认值</button><button disabled={!allowed||busy} onClick={requestRun}>运行</button></>}>{message&&<p role="alert" className="spac-dialog-note">{message}</p>}<fieldset disabled={!allowed||busy}><legend>扫描范围</legend>{([['fmin','起始频率','Hz',1,39],['fmax','终止频率','Hz',2,40],['cmin','最低相速度','m/s',80,1499],['cmax','最高相速度','m/s',81,1500],['step','速度步长','m/s',2,30],['window','统计窗口','s',5,60],['smooth','相关曲线平滑','点',1,9]] as const).map(([k,label,unit,min,max])=><label key={k} className="spac-form-row"><span>{label}</span><input aria-label={label} type="number" min={min} max={max} step={k==='fmin'||k==='fmax'?.5:1} value={draft.params[k]} onChange={e=>setParam(k,+e.target.value)}/><small>{unit}</small></label>)}</fieldset><fieldset disabled={!allowed||busy}><legend>波形预览</legend><label><input type="checkbox" checked={draft.params.detrend} onChange={e=>setParam('detrend',e.target.checked)}/>去趋势</label><label><input type="checkbox" checked={draft.params.normalize} onChange={e=>setParam('normalize',e.target.checked)}/>幅值归一化</label></fieldset><p className="spac-dialog-note">运行使用当前参数重新生成结果；现有拾取点将提示确认后清空。波形预处理仅作用于配套波形预览。</p></Modal>}
 {dialog==='array'&&<Modal title="观测参数" onClose={close}><h2>{data.name}</h2><dl><dt>通道</dt><dd>{data.channels} / Z 分量</dd><dt>采样率</dt><dd>{data.sampleRate} Hz</dd><dt>记录时长</dt><dd>{data.duration} s</dd><dt>距离组</dt><dd>{data.radii.join(' / ')} m</dd><dt>输入</dt><dd>合成环组自相关系数</dd></dl><button onClick={()=>{setOverview(false);setView('观测阵列');close()}}>查看台阵图</button></Modal>}
 {dialog==='point'&&<Modal title="数值拾取" onClose={close} footer={<><button onClick={close}>取消</button><button disabled={!allowed||busy||changed||!Number.isFinite(numeric.f)||!Number.isFinite(numeric.c)||numeric.f<result.request.params.fmin||numeric.f>result.request.params.fmax||numeric.c<result.request.params.cmin||numeric.c>result.request.params.cmax} onClick={()=>{editPicks(addSpacPick(picks,numeric));setOverview(false);setView('频散能量');close()}}>添加</button></>}><label className="spac-form-row"><span>频率</span><input aria-label="拾取频率" type="number" step=".1" min={result.request.params.fmin} max={result.request.params.fmax} value={numeric.f} onChange={e=>setNumeric(v=>({...v,f:+e.target.value}))}/><small>Hz</small></label><label className="spac-form-row"><span>相速度</span><input aria-label="拾取相速度" type="number" step="1" min={result.request.params.cmin} max={result.request.params.cmax} value={numeric.c} onChange={e=>setNumeric(v=>({...v,c:+e.target.value}))}/><small>m/s</small></label></Modal>}
 {dialog==='replace'&&<Modal title="重新计算" onClose={close} footer={<><button onClick={close}>取消</button><button onClick={exportConfig}>导出当前配置</button><button onClick={()=>run()}>重新计算并清空拾取</button></>}><p>当前有 {picks.length} 个拾取点。新结果不能沿用旧图面的拾取位置，请先保存或导出需要保留的结果。</p><p>本地已保存的项目不会被覆盖，除非再次点击“保存”。</p></Modal>}
 {dialog==='help'&&<Modal title="操作与数据来源" onClose={close}><h2>SPAC 频散分析</h2><ol><li>打开数据，查看波形与阵列。</li><li>设置频率和速度范围，运行扫描。</li><li>在能量图上拾取，或按坐标输入。</li><li>查看拾取数据，保存配置或导出。</li></ol><p>{spacSource}</p><p>拟合曲线为拾取点在对数频率域的二次最小二乘拟合，不是地层反演。统计窗口用于控制合成系数的扰动水平。</p><p>支持本工具导出的 JSON 配置；未接入 SEG-Y、MiniSEED 或现场设备。</p><a href="https://geopsy.org/wiki/index.php/Ambient_vibration_array" target="_blank" rel="noreferrer">SPAC 关系参考：Geopsy 文档 ↗</a></Modal>}
 </section>
}
