import {RecordSummary} from './RecordSummary'
import { useEffect, useState } from 'react'
import { Play, Pause, SkipBack, ChevronRight, History, FileJson, ArrowRight, GitCompareArrows, Radio, BatteryLow, Activity, CheckCircle2 } from 'lucide-react'
import { useDemo, seedDevices, PacketData, exportFile, type Device } from './store'
import { seedAcquisitionDevices } from './hardware'
import { frameTime, historicalDevices, replayEvents, sourceFor } from './telemetry'
import { MineMap } from './MineMap'
import {MineScene} from './MineScene'
import {seedPlatformDevices} from './sceneCatalog'
import { moduleCatalog } from '../data/catalog'
import { specFor } from './algorithms'
import {goWorkspace} from './navigation'
import {computeAnalysis} from './analysisEngine'
import {AnalysisFigure} from './AnalysisFigure'
import {WorkspaceDrawer} from './WorkspaceDrawer'
import {DataSignalPanel} from './DataSignalPanel'
import {WorkbenchStatus} from './ScientificUI'
import {AnalysisTrace} from './AnalysisTrace'

export function TraceStudio(props:{deviceId?:string;initialTab?:string;taskId?:string;initialFrame?:number;initialSnapshot?:string}){const {state}=useDemo();return props.taskId&&state.tasks.find(t=>t.id===props.taskId)?.analysis?<AnalysisTrace taskId={props.taskId}/>:<LegacyTraceStudio {...props}/>}

function LegacyTraceStudio({deviceId,initialTab='历史回放',taskId:initialTaskId='',initialFrame=36,initialSnapshot=''}:{deviceId?:string;initialTab?:string;taskId?:string;initialFrame?:number;initialSnapshot?:string}){
 const {state,visibleDevices}=useDemo(),[tab,setTab]=useState(initialTab),[frame,setFrame]=useState(Number.isFinite(initialFrame)?Math.max(0,Math.min(120,initialFrame)):36),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[selectedDevice,setSelectedDevice]=useState(deviceId||visibleDevices[0]?.id||''),[snapshotId,setSnapshotId]=useState(initialSnapshot),[query,setQuery]=useState(''),[taskId,setTaskId]=useState(initialTaskId),[node,setNode]=useState(0),[compareId,setCompareId]=useState('')
 const [view,setView]=useState('空间'),[archiveOpen,setArchiveOpen]=useState(false),[detailsOpen,setDetailsOpen]=useState(false)
 const scope=(d:Device)=>visibleDevices.some(x=>x.id===d.id)
 const archived=state.history.find(h=>h.id===snapshotId),base=[...seedDevices(),...seedAcquisitionDevices(),...seedPlatformDevices()],devices=(archived?archived.devices:historicalDevices(base,frame)).filter(scope),packets=(archived?archived.packets:PacketData(devices,frame,1)).filter(p=>devices.some(d=>d.id===p.device)),current=devices.find(d=>d.id===selectedDevice)||devices[0],packet=packets.find(p=>p.device===current?.id)
 const tasks=state.tasks.filter(t=>!t.analysis).filter(t=>{const source=sourceFor(t,state.devices,36,state.mapping);return source&&visibleDevices.some(d=>d.id===source.deviceId)}).filter(t=>`${t.id}${t.algorithm}${t.input}${t.source?.packet.trace||''}`.toLowerCase().includes(query.toLowerCase()))
 const task=tasks.find(t=>t.id===taskId)||tasks[0],source=task?sourceFor(task,state.devices,36,state.mapping):null,risks=state.risks.filter(r=>r.task===task?.id&&visibleDevices.some(d=>d.id===r.device)),spec=task?specFor(task.algorithm):null
 const old=state.history.find(h=>h.id===compareId)||state.history[1],newer=archived||state.history[0]
 useEffect(()=>{if(!playing||snapshotId)return;const h=window.setInterval(()=>setFrame(v=>{const next=Math.min(120,v+speed);if(next===120)setPlaying(false);return next}),500);return()=>clearInterval(h)},[playing,speed,snapshotId])
 const jump=(value:number)=>{setFrame(value);setSnapshotId('');setPlaying(false)}
 return <div className="trace-studio">{archiveOpen&&<WorkspaceDrawer title="成果归档" onClose={()=>setArchiveOpen(false)}><AnalysisArchive deviceId={deviceId}/></WorkspaceDrawer>}<div className="trace-navigation-row"><div className="product-subnav">{['历史回放','成果证据链','快照对比'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setPlaying(false)}}>{t}</button>)}</div><button onClick={()=>setArchiveOpen(true)}><History size={14}/>成果归档</button></div>
 {tab==='历史回放'&&<><div className="trace-toolbar"><select aria-label="回溯设备" value={current?.id||''} onChange={e=>setSelectedDevice(e.target.value)}>{devices.map(d=><option key={d.id} value={d.id}>{d.id} / {d.name}</option>)}</select><select aria-label="回溯数据来源" value={snapshotId} onChange={e=>{setSnapshotId(e.target.value);setPlaying(false)}}><option value="">内置场景 / 09:00—10:00</option>{state.history.map(h=><option key={h.id} value={h.id}>{h.time} · {h.label}</option>)}</select><button onClick={()=>exportFile(`${current?.id||'历史'}-回溯快照.json`,JSON.stringify({source:archived?'操作归档':'内置场景',time:archived?.time||frameTime(frame),device:current,packet},null,2))}><FileJson size={14}/>导出快照</button></div><div className="trace-replay-layout"><div className="trace-map-panel"><div className="trace-map-header"><div className="glass-inline-tabs">{['曲线','空间'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</div><strong>{archived?.time||`2026/09/21 ${frameTime(frame)}`}</strong></div>{view==='曲线'&&!archived?<DataSignalPanel key={current?.id} deviceId={current?.id} replayFrame={frame} onFrame={jump} sampleDevices={base} mapping={1}/>:view==='曲线'?<div className="glass-frozen-snapshot"><History size={32}/><strong>归档快照</strong><span>{archived?.time}</span><div><b>{packet?.value} <small>{packet?.unit}</small></b><span>{packet?.status}</span></div><button onClick={()=>setView('空间')}>查看空间状态</button><button onClick={()=>setDetailsOpen(true)}>查看冻结报文</button></div>:<MineScene cinematic devices={devices} frame={archived?.frame??frame} selected={current?.id||''} onSelect={setSelectedDevice} layers={{paths:true,coverage:true,underground:false,sensors:true}}/>}</div><aside className="trace-state-panel"><h2>{current?.id}</h2><span className={`status ${current?.status==='在线'?'ok':'warn'}`}>{current?.status}</span><dl><dt>后备电量</dt><dd>{current?.type.includes('微震')?'无独立电池':`${current?.battery}%`}</dd><dt>通信信号</dt><dd>{current?.signal} dBm</dd><dt>采样频率</dt><dd>{current?.rate}</dd><dt>数据质量</dt><dd>{packet?.status}</dd><dt>{packet?.metric}</dt><dd>{packet?.value} {packet?.unit}</dd></dl><button onClick={()=>setDetailsOpen(true)}>报文明细 <ArrowRight size={14}/></button></aside></div>
 <div className="trace-player"><button aria-label="回到历史起点" onClick={()=>jump(0)}><SkipBack size={16}/></button><button className="primary" disabled={!!snapshotId} onClick={()=>{if(frame===120)setFrame(0);setPlaying(v=>!v)}}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'暂停回放':'播放历史'}</button><input aria-label="历史回放时间" type="range" min="0" max="120" disabled={!!snapshotId} value={frame} onChange={e=>jump(+e.target.value)}/><span>{frameTime(frame)}</span><select aria-label="历史回放速度" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[1,2,4,8].map(n=><option key={n} value={n}>{n}×</option>)}</select></div><div className="replay-events">{replayEvents.map(e=><button key={e.frame} title={e.detail} className={!snapshotId&&frame>=e.frame&&(replayEvents.find(n=>n.frame>e.frame)?.frame||121)>frame?'active':''} aria-pressed={!snapshotId&&frame>=e.frame&&(replayEvents.find(n=>n.frame>e.frame)?.frame||121)>frame} onClick={()=>{jump(e.frame);const id=[40,56,70].includes(e.frame)?base[0]?.id:[78,90].includes(e.frame)?base[1]?.id:undefined;if(id&&visibleDevices.some(d=>d.id===id))setSelectedDevice(id)}}><span className="replay-event-symbol">{e.frame===70?<BatteryLow size={19}/>:e.frame===40||e.frame===56?<Radio size={19}/>:e.frame===78||e.frame===90?<Activity size={19}/>:<CheckCircle2 size={19}/>}</span><small>{frameTime(e.frame)}</small><strong>{e.title.replace('监测开始','开始监测')}</strong></button>)}</div>{detailsOpen&&<WorkspaceDrawer title="该时刻报文与标准化记录" onClose={()=>setDetailsOpen(false)}><div className="trace-packet-details"><div className="trace-packet"><div><h3>该时刻原始报文</h3><RecordSummary value={{device_id:packet?.device,seq:packet?.frame,raw_value:packet?.raw,protocol:packet?.protocol,quality:packet?.status}}/></div><div><h3>标准化记录</h3><RecordSummary value={packet}/></div></div></div></WorkspaceDrawer>}</>}
 {tab==='成果证据链'&&<><div className="trace-toolbar"><input placeholder="查询任务号、算法、设备或 traceId" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="追溯算法任务" value={task?.id||''} onChange={e=>{setTaskId(e.target.value);setNode(0)}}>{tasks.map(t=><option key={t.id} value={t.id}>{t.id} / {moduleCatalog.find(m=>m.id===t.algorithm)?.name} / V{t.version}</option>)}</select><button disabled={!task} onClick={()=>exportFile(`${task?.id}-证据包.json`,JSON.stringify({task,source,risks,scope:'离线演示证据包，非工程安全结论'},null,2))}>导出完整证据包</button></div>{task&&source?<><div className="evidence-summary"><div><small>当前成果</small><strong>{moduleCatalog.find(m=>m.id===task.algorithm)?.name}</strong><span>{task.id} / V{task.version}</span></div><div><small>输入追踪</small><strong>{source.deviceId}</strong><span>{source.packet.trace}</span></div><div><small>关联风险</small><strong>{risks.length} 个</strong><span>{task.source?'使用任务创建时冻结的输入快照':'旧任务使用内置基准样例'}</span></div></div><div className="trace-chain">{['设备采集','原始报文','标准化数据','算法任务','风险处置','报告证据'].map((label,i)=><button key={label} className={node===i?'active':''} onClick={()=>setNode(i)}><small>0{i+1}</small><strong>{label}</strong><span>{[source.deviceId,source.packet.id,`映射系数 ${source.mapping}`,`V${task.version}`,`${risks.length} 个关联事件`,'可导出证据包'][i]}</span>{i<5&&<ChevronRight size={17}/>}</button>)}</div><div className="trace-node-detail"><section><h2>{['设备采集快照','原始字段与序列','解析与单位换算','算法参数与版本','风险确认及处置','报告证据索引'][node]}</h2>{node===3&&<div className="trace-algorithm-steps">{spec?.steps.map((s,i)=><div key={s}><b>{i+1}</b>{s}<ArrowRight size={12}/></div>)}</div>}{node===4&&risks.length===0&&<div className="empty">暂无关联风险</div>}{node===4&&risks.map(r=><article className="trace-risk" key={r.id}><h3>{r.id} / {r.title}</h3><p>{r.note}</p>{r.history.map((h,i)=><div key={i}>{h.time} · {h.action}</div>)}</article>)}{node===2&&<div className="mapping-equation"><span>{source.packet.raw}<small>原始值</small></span><b>÷ 1000 ×</b><span>{source.mapping}<small>标定系数</small></span><b>≈</b><span>{source.packet.value}<small>{source.packet.unit}</small></span></div>}</section><RecordSummary value={node===0?{device:source.deviceId,input:source.inputLabel,frame:source.frame,immutable:true}:node===1?{device_id:source.deviceId,seq:source.frame,raw_value:source.packet.raw}:node===2?source.packet:node===3?{id:task.id,algorithm:task.algorithm,version:task.version,params:task.params,excluded:task.excluded,status:task.status}:node===4?risks:{taskId:task.id,traceId:source.packet.trace,riskIds:risks.map(r=>r.id),hasClosure:risks.some(r=>r.stage===4)}}/></div></>:<div className="empty">没有符合条件且在当前角色范围内的任务。</div>}</>}
 {tab==='快照对比'&&<><div className="trace-toolbar"><GitCompareArrows size={19}/><select aria-label="较早快照" value={old?.id||''} onChange={e=>setCompareId(e.target.value)}>{state.history.map(h=><option key={h.id} value={h.id}>{h.time} · {h.label}</option>)}</select><span>对比</span><select aria-label="较新快照" value={newer?.id||''} onChange={e=>setSnapshotId(e.target.value)}>{state.history.map(h=><option key={h.id} value={h.id}>{h.time} · {h.label}</option>)}</select></div>{old&&newer?<><table><thead><tr><th>设备</th><th>历史状态</th><th>对比状态</th><th>电量变化</th><th>报文状态</th><th>结论</th></tr></thead><tbody>{newer.devices.filter(scope).map(d=>{const before=old.devices.find(x=>x.id===d.id),a=old.packets.find(p=>p.device===d.id),b=newer.packets.find(p=>p.device===d.id),changed=before?.status!==d.status||before?.battery!==d.battery||a?.status!==b?.status;return <tr key={d.id} className={changed?'comparison-changed':''}><td>{d.id}</td><td>{before?.status||'不存在'}</td><td>{d.status}</td><td>{before?.battery??'—'}% → {d.battery}%</td><td>{a?.status||'—'} → {b?.status||'—'}</td><td>{changed?'存在变化':'一致'}</td></tr>})}</tbody></table></>:<div className="empty">至少需要两条快照</div>}</>}
 <WorkbenchStatus><span>{snapshotId?'冻结快照':playing?'回放中':'历史记录'}</span><span>{current?.id}</span><span>{archived?.time||frameTime(frame)}</span><span>{snapshotId?'快照':'回放'}</span></WorkbenchStatus></div>
}
function AnalysisArchive({deviceId}:{deviceId?:string}){const {state,visibleDevices}=useDemo(),tasks=state.tasks.filter(t=>t.analysis&&(!t.source||visibleDevices.some(d=>d.id===t.source?.deviceId))&&(!deviceId||t.source?.deviceId===deviceId));if(!tasks.length)return <p>暂无归档成果。算法运行后可归档至此。</p>;return <section className="analysis-archive"><header><h2>分析成果归档</h2><span>{tasks.length} 个版本</span></header><div>{tasks.slice(0,8).map(t=><button key={t.id} onClick={()=>goWorkspace({page:'trace',task:t.id,device:t.source?.deviceId})}><AnalysisFigure compact figure={(t.analysis!.result||computeAnalysis(t.analysis!.request)).figures[0]}/><strong>{moduleCatalog.find(m=>m.id===t.algorithm)?.name}</strong><small>V{t.version} · {t.analysis!.digest}</small><span>{t.time}</span></button>)}</div></section>}
