import {useState,type CSSProperties} from 'react'
import {SummaryDetails,type SummarySelection,type SummaryRow} from './SummaryDetails'
import {Activity,Radio,Satellite,Plane,Truck,ScanLine,Cpu,Workflow,FileCheck2,Settings2,ShieldCheck} from 'lucide-react'
import {widgetCatalog} from '../data/catalog'
import {useDemo,PacketData,roles,riskStages,type Device} from './store'
import {historicalDevices} from './telemetry'
import {AnalysisFigure} from './AnalysisFigure'
import {sceneTime} from './sceneCatalog'
import {goWorkspace,moduleRoute} from './navigation'

const colors=['#93c9d7','#e7b579','#667d94','#b5a5d4','#6da5dd']
const deviceRow=(d:Device):SummaryRow=>({id:d.id,name:d.id,detail:`${d.name} · ${d.area} · 电量 ${d.battery}%`,value:d.status,route:{page:'device',id:d.id,device:d.id}})
export function EquipmentIcon({type,size=25}:{type:string;size?:number}){const Icon=type==='遥感卫星'?Satellite:type==='巡检无人机'?Plane:type==='雷达巡检车'?Truck:type==='数采板'?Cpu:type==='微震节点'?Activity:type==='深地感知站'?ScanLine:Radio;return <Icon size={size} strokeWidth={1.4}/>}
export function StatusRing({values,labels,onSelect}:{values:number[];labels:string[];onSelect:(index:number|null)=>void}){
 const total=values.reduce((a,b)=>a+b,0);let offset=0
 return <div className="summary-distribution"><button className="quiet-button summary-ring-trigger" aria-label={`查看全部 ${total} 项`} onClick={()=>onSelect(null)}><svg viewBox="0 0 120 120" role="img" aria-label={labels.map((s,i)=>`${s} ${values[i]}`).join('，')}><circle cx="60" cy="60" r="45" fill="none" stroke="#263f4e" strokeWidth="8"/>{values.map((n,i)=>{const start=offset;offset+=total?n/total*100:0;return <circle key={labels[i]} cx="60" cy="60" r="45" fill="none" stroke={colors[i%colors.length]} strokeWidth="8" pathLength="100" strokeDasharray={`${total?n/total*100:0} 100`} strokeDashoffset={-start} transform="rotate(-90 60 60)" onClick={e=>{e.stopPropagation();onSelect(i)}}/>})}<text x="60" y="63" textAnchor="middle" className="ring-number">{total}</text><text x="60" y="80" textAnchor="middle" className="ring-unit">总计</text></svg></button><dl>{labels.map((s,i)=><div key={s}><dt><i style={{background:colors[i%colors.length]}}/>{s}</dt><dd><button className="quiet-button summary-number-trigger" aria-label={`查看${s} ${values[i]} 项`} onClick={()=>onSelect(i)}>{values[i]}</button></dd></div>)}</dl></div>
}
export function DeviceVisualSummary({kind}:{kind:string}){
 const {visibleDevices}=useDemo(),[selection,setSelection]=useState<SummarySelection|null>(null)
 const lists=[visibleDevices.filter(d=>d.status==='在线'),visibleDevices.filter(d=>d.status==='离线'),visibleDevices.filter(d=>!['在线','离线'].includes(d.status))],labels=['在线','离线','维护 / 其他']
 const choose=(title:string,list:Device[])=>setSelection({title,rows:list.map(deviceRow),empty:'当前范围内没有该类设备'})
 const groups=Array.from(new Set(visibleDevices.map(d=>d.type)))
 return <>{['deviceOnline','deviceDonut','deviceHealth','offlineAnalysis','hardwareHealth'].includes(kind)?<StatusRing values={lists.map(l=>l.length)} labels={labels} onSelect={i=>choose(i===null?'全部设备':`${labels[i]}设备`,i===null?visibleDevices:lists[i])}/>:<div className="summary-fleet">{groups.map(type=>{const list=visibleDevices.filter(d=>d.type===type);return <button className="quiet-button" key={type} title={`${type} · ${list.length} 台`} aria-label={`查看${type}设备`} onClick={()=>choose(type,list)}><EquipmentIcon type={type}/><b>{list.length}</b><span>{type}</span></button>})}{!groups.length&&<span>暂无设备</span>}</div>}<SummaryDetails selection={selection} onClose={()=>setSelection(null)}/></>
}
export function DataVisualSummary({kind}:{kind:string}){
 const {state,visibleDevices}=useDemo(),[selection,setSelection]=useState<SummarySelection|null>(null),packets=PacketData(visibleDevices,state.frame,state.mapping),p=packets.find(p=>p.device===state.selectedDevice)||packets[0]
 const statuses=['已入库','解析失败','中断'],labels=['入库','隔离','中断']
 if(['quality','dataAccessOverview','parseFailure','dataContinuity'].includes(kind))return <><StatusRing values={statuses.map(s=>packets.filter(p=>p.status===s).length)} labels={labels} onSelect={i=>setSelection({title:i===null?'全部回传':`${labels[i]}记录`,rows:packets.filter(p=>i===null||p.status===statuses[i]).map(p=>({id:p.id,name:p.device,detail:p.metric,value:p.status,route:{page:'data',device:p.device}}))})}/><SummaryDetails selection={selection} onClose={()=>setSelection(null)}/></>
 if(!p)return <div className="summary-empty">暂无记录</div>
 const series=Array.from({length:61},(_,i)=>PacketData(historicalDevices(visibleDevices,i*2),i*2,state.mapping).find(r=>r.device===p.device)!),max=Math.max(1,...series.map(r=>r.value))
 return <div className="summary-signal"><div><button className="quiet-button summary-signal-value" aria-label={`查看 ${p.device} 当前数据`} onClick={()=>goWorkspace({page:'data',device:p.device})}><span>{p.device}</span><strong>{p.status==='中断'?'—':p.value}<small>{p.unit}</small></strong></button></div><div className="summary-plot-action summary-signal-plot"><button className="quiet-button summary-plot-trigger" aria-label={`查看 ${p.device} 回传数据`} onClick={()=>goWorkspace({page:'data',device:p.device})}/><AnalysisFigure compact figure={{kind:'lines',title:'回传信号',x:'时间 / min',y:p.unit,range:[0,60,0,max*1.1],lines:[series.map(r=>r.status==='已入库'?r.value:NaN)],labels:[p.metric]}}/></div><div className="summary-packet-strip" aria-label="各设备回传状态">{packets.map(r=><button key={r.id} className={`quiet-button ${r.status==='已入库'?'ok':'warn'}`} title={`${r.device} · ${r.status}`} aria-label={`${r.device} ${r.status}`} onClick={()=>goWorkspace({page:'data',device:r.device})}/>)}</div></div>
}
function RiskMap({devices,ids,onSelect}:{devices:Device[];ids:Set<string>;onSelect:(id:string)=>void}){
 return <svg viewBox="0 0 260 120" role="group" aria-label="风险测点分布"><g fill="none" stroke="#405967" strokeWidth=".7">{[0,1,2,3,4,5].map(i=><ellipse key={i} cx="130" cy="64" rx={110-i*15} ry={51-i*7} transform="rotate(-10 130 64)"/>)}</g>{[...devices].sort((a,b)=>Number(ids.has(a.id))-Number(ids.has(b.id))).map(d=><g key={d.id} role="button" tabIndex={0} aria-label={`查看 ${d.id}${ids.has(d.id)?' 预警':' 设备'}`} onClick={()=>onSelect(d.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(d.id)}}}><title>{`${d.id}${ids.has(d.id)?' · 待处置':''}`}</title><circle cx={130+d.x*.65} cy={60+d.y*.45} r="9" fill="transparent"/>{ids.has(d.id)&&<circle cx={130+d.x*.65} cy={60+d.y*.45} r="12" fill="#dda96e22" stroke="#dda96e"/>}<circle cx={130+d.x*.65} cy={60+d.y*.45} r={ids.has(d.id)?4:2} fill={ids.has(d.id)?'#e7b579':'#7dabb6'}/></g>)}</svg>
}
export function RiskVisualSummary({kind}:{kind:string}){
 const {state,visibleDevices}=useDemo(),[selection,setSelection]=useState<SummarySelection|null>(null),risks=state.risks.filter(r=>visibleDevices.some(d=>d.id===r.device)),open=risks.filter(r=>r.stage<4),report=['riskReport','riskReportArchive','reviewClosure','dispositionStats'].includes(kind)
 const choose=(title:string,list:typeof risks)=>setSelection({title,rows:list.map(r=>({id:r.id,name:r.title,detail:`${r.device} · ${r.level} · ${r.owner}`,value:riskStages[r.stage],route:{page:'risk',id:r.id}})),empty:'当前范围内没有该阶段事件'})
 const selectPoint=(id:string)=>{const matches=open.filter(r=>r.device===id);if(matches.length===1)goWorkspace({page:'risk',id:matches[0].id});else if(matches.length)choose(`${id} 预警`,matches);else goWorkspace({page:'device',id,device:id})}
 return <>{report?<div className="summary-report" data-summary="report"><div><button className="quiet-button summary-report-total" aria-label="查看已闭环事件" onClick={()=>choose('已闭环事件',risks.filter(r=>r.stage===4))}><FileCheck2 size={32} strokeWidth={1}/><strong>{risks.filter(r=>r.stage===4).length}<small>已闭环 / {risks.length}</small></strong></button></div><div className="summary-stage-bars">{['确认','派发','处置','复核','关闭'].map((label,i)=><div key={label}><button className="quiet-button" aria-label={`查看${riskStages[i]}事件`} onClick={()=>choose(riskStages[i],risks.filter(r=>r.stage===i))}><span>{risks.filter(r=>r.stage===i).length}</span><i style={{height:`${10+50*risks.filter(r=>r.stage===i).length/Math.max(1,risks.length)}px`}}/><small>{label}</small></button></div>)}</div></div>:<div className="summary-risk" data-summary="risk"><RiskMap devices={visibleDevices.filter(d=>!['遥感卫星','巡检无人机'].includes(d.type))} ids={new Set(open.map(r=>r.device))} onSelect={selectPoint}/><div><button className="quiet-button summary-risk-total" aria-label={`查看待处置 ${open.length} 项预警`} onClick={()=>choose('待处置预警',open)}><strong>{open.length}</strong><small>待处置</small></button></div></div>}<SummaryDetails selection={selection} onClose={()=>setSelection(null)}/></>
}
export function AccountVisualSummary(){
 const {state}=useDemo(),[selection,setSelection]=useState<SummarySelection|null>(null)
 const choose=(title:string,accounts:typeof state.accounts)=>setSelection({title,rows:accounts.map(a=>({id:a.id,name:a.name,detail:`${a.role} · ${a.scope}`,value:a.enabled?'启用':'停用'})),empty:'该角色暂无账号'})
 return <><div className="summary-accounts"><div className="summary-avatar-group">{state.accounts.slice(0,7).map((a,i)=><button className="quiet-button" key={a.id} aria-label={`查看账号 ${a.name}`} title={`${a.name} · ${a.role}${a.enabled?'':' · 停用'}`} style={{'--avatar-color':colors[i%5],opacity:a.enabled?1:.35} as CSSProperties} onClick={()=>choose(a.name,[a])}>{a.name.slice(-1)}</button>)}</div><div className="summary-role-bars">{roles.map((r,i)=><div key={r} style={{flex:Math.max(.15,state.accounts.filter(a=>a.role===r).length)}}><button className="quiet-button" aria-label={`查看${r}账号`} onClick={()=>choose(r,state.accounts.filter(a=>a.role===r))}><span style={{background:colors[i]}}/><small>{r.replace('项目管理员','管理').replace('设备管理员','设备').replace('算法工程师','算法').replace('风险处置员','处置').replace('客户访客','访客')}</small></button></div>)}</div></div><SummaryDetails selection={selection} onClose={()=>setSelection(null)}/></>
}
export function TraceVisualSummary(){const {state}=useDemo();return <div className="summary-trace"><div><button className="quiet-button" aria-label="回放当前时刻" onClick={()=>goWorkspace({page:'trace',frame:String(state.frame)})}><strong>{sceneTime(state.frame)}</strong></button><button className="quiet-button" aria-label="查看全部快照" onClick={()=>goWorkspace({page:'trace',tab:'快照对比'})}><span>{state.history.length} 份快照</span></button></div><div className="summary-time-track"><i style={{left:`${state.frame/120*100}%`}}/>{state.history.slice(0,18).map(s=><button key={s.id} style={{left:`${s.frame/120*100}%`}} title={s.label} aria-label={`查看快照 ${s.label}`} onClick={()=>goWorkspace({page:'trace',snapshot:s.id,frame:String(s.frame)})}/>)}</div><div className="summary-time-labels"><span>09:00</span><span>10:00</span></div></div>}
export function TaskVisualSummary(){
 const {state,visibleDevices}=useDemo(),[selection,setSelection]=useState<SummarySelection|null>(null),tasks=state.tasks.filter(t=>!t.source||visibleDevices.some(d=>d.id===t.source?.deviceId)),lists=[tasks.filter(t=>t.status==='已完成'),tasks.filter(t=>t.status==='运行中'),tasks.filter(t=>!['已完成','运行中'].includes(t.status))],labels=['完成','运行','待处理']
 return <><StatusRing values={lists.map(l=>l.length)} labels={labels} onSelect={i=>setSelection({title:i===null?'全部算法任务':`${labels[i]}任务`,rows:(i===null?tasks:lists[i]).map(t=>({id:t.id,name:t.id,detail:t.input,value:t.status,route:{page:'algorithm',id:t.algorithm,task:t.id,device:t.source?.deviceId}}))})}/><SummaryDetails selection={selection} onClose={()=>setSelection(null)}/></>
}
export function ConfigurationSummary({kind}:{kind:string}){
 const {state}=useDemo(),w=widgetCatalog.find(w=>w.kind===kind),Icon=w?.category==='预警闭环'?ShieldCheck:kind.includes('flow')?Workflow:Settings2
 return <div className="summary-capabilities"><Icon size={38} strokeWidth={1}/><div>{(w?.features||['查询','配置','执行','记录']).slice(0,4).map((f,i)=><button className="quiet-button" key={f} onClick={()=>goWorkspace(moduleRoute(kind))}><i/>{f}</button>)}</div>{state.records[kind]?.length>0&&<span className="summary-count">{state.records[kind].length}</span>}</div>
}
