import test from 'node:test'
import assert from 'node:assert/strict'
import {build} from 'esbuild'
import {createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
const root=fileURLToPath(new URL('..',import.meta.url))
const bundle=await build({stdin:{contents:`export * from './src/studio/analysisEngine';export * from './src/studio/algorithms';export * from './src/studio/navigation';`,resolveDir:root,loader:'ts'},bundle:true,write:false,platform:'node',format:'cjs'})
const m={exports:{}};new Function('require','module','exports',bundle.outputFiles[0].text)(createRequire(import.meta.url),m,m.exports);const a=m.exports
const request=id=>({id,dataset:a.defaultDataset(id),params:a.defaultParams(id),excluded:[]})
test('31 methods have three domain-specific figures and an explicit source',()=>{const signatures=new Set();for(const spec of a.algorithmSpecs){const r=a.computeAnalysis(request(spec.id));assert.equal(r.figures.length,3,spec.id);assert.ok(r.source&&r.method);assert.equal(r.mode,a.localMethods.has(spec.id)?'computed':'reference');signatures.add(r.figures.map(f=>f.title).join('|'));for(const f of r.figures){assert.ok(f.x&&f.y);if(f.matrix)assert.ok(f.matrix.flat().every(Number.isFinite))}}assert.equal(signatures.size,31)})
test('FFT identifies a known bin and rejects invalid sample lengths',()=>{const signal=Array.from({length:256},(_,i)=>Math.sin(2*Math.PI*16*i/256)),s=a.fft(signal);assert.equal(s.power.indexOf(Math.max(...s.power)),16);assert.ok(Math.abs(s.power[16]-.5)<1e-9);assert.throws(()=>a.fft([1,2,3]))})
test('linear regression recovers a known trend exactly',()=>{const fit=a.linearFit(Array.from({length:30},(_,i)=>3+2*i));assert.equal(fit.slope,2);assert.equal(fit.intercept,3);assert.equal(fit.rmse,0)})
test('STA/LTA thresholds control actual event windows',()=>{assert.deepEqual(a.triggerWindows([0,1,4,5,2,0,0,6,0],3),[[2,5],[7,8]]);assert.deepEqual(a.triggerWindows([0,1,4,5,2],10),[])})
test('parameter changes affect computed output and leave old records immutable',()=>{const r=request('event-detection'),before=JSON.stringify(r),base=a.computeAnalysis(r);const next=a.computeAnalysis({...r,params:{...r.params,'触发比':8}});assert.notEqual(base.digest,next.digest);assert.notDeepEqual(base.figures[1],next.figures[1]);assert.equal(JSON.stringify(r),before);assert.deepEqual(a.computeAnalysis(JSON.parse(before)),base)})
test('excluded channels affect the wave input and its analysis',()=>{const r=request('phase-shift-active'),base=a.computeAnalysis(r),next=a.computeAnalysis({...r,excluded:['CH-03']});assert.equal(next.figures[2].lines.length,23);assert.notDeepEqual(base.figures[0].matrix,next.figures[0].matrix)})
test('invalid parameter values fail without inventing results',()=>{const r=request('taup');assert.throws(()=>a.computeAnalysis({...r,params:{...r.params,'时间窗':-1}}));assert.throws(()=>a.computeAnalysis({...r,params:{...r.params,'时间窗':NaN}}))})
test('method inputs are typed and cannot relabel a seismic record as GNSS',()=>{assert.throws(()=>a.computeAnalysis({...request('fk'),dataset:'GNSS-24H'}));assert.deepEqual(a.datasetsFor('gnss-prediction').map(d=>d.id),['GNSS-24H','GNSS-24H-V2']);assert.throws(()=>a.computeAnalysis({...request('fk'),id:'not-a-method'}))})
test('phase velocity limits agree across primary and ridge figures',()=>{const r=request('phase-shift-active'),out=a.computeAnalysis({...r,params:{...r.params,'最高相速度':1300}});assert.equal(out.figures[0].range[3],1300);assert.equal(out.figures[1].range[3],1300)})
test('HV component spectra and labels follow the same retained windows',()=>{const r=request('hvsr'),base=a.computeAnalysis(r),filtered=a.computeAnalysis({...r,excluded:['CH-01','CH-02']});assert.equal(filtered.figures[0].lines.length,7);assert.equal(filtered.figures[0].labels[0],'窗口 3');assert.equal(filtered.figures[2].matrix.length,6);assert.notDeepEqual(base.figures[1].lines,filtered.figures[1].lines)})
test('observations stop at history boundary instead of stretching into forecast',()=>{const result=a.computeAnalysis(request('gnss-prediction')),lines=result.figures[0].lines;assert.equal(lines[0].length,lines[1].length);assert.ok(lines[0].slice(48).every(Number.isNaN))})
test('routes preserve device, dataset, task and Chinese tab context',()=>{const route={page:'algorithm',id:'event-location',device:'MS-002',dataset:'EVT-006',task:'AN-01',tab:'成果证据链',frame:'36'};assert.deepEqual(a.parseRoute(a.routeHash(route)),route);assert.equal(a.parseRoute('#dashboard').page,'preview');assert.equal(a.parseRoute('#/missing').page,'overview');assert.deepEqual(a.moduleRoute('algorithm-fk'),{page:'algorithm',id:'fk'})})
