import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
import {build} from 'esbuild'
const root=fileURLToPath(new URL('..',import.meta.url))
const result=await build({stdin:{contents:`export * from './src/studio/sceneCatalog';export * from './src/studio/threeModels';export {widgetCatalog} from './src/data/catalog';export {packetData} from './src/studio/telemetry'`,resolveDir:root,loader:'ts'},bundle:true,write:false,platform:'node',format:'cjs'})
const module={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);const a=module.exports
test('four independent platform devices are uniquely addressable and included in component catalogue',()=>{const ds=a.seedPlatformDevices();assert.equal(new Set(ds.map(d=>d.id)).size,4);for(const d of ds)assert.ok(a.platformFor(d));for(const kind of a.sceneKinds)assert.ok(a.widgetCatalog.some(w=>w.kind===kind));assert.equal(new Set(a.widgetCatalog.map(w=>w.kind)).size,154)})
test('all four meshes expose actual pickable parts and explode reversibly',()=>{for(const kind of a.platformKinds){const m=a.createDeviceModel(kind),expected=a.platforms[kind].parts.map(p=>p.id);assert.deepEqual([...m.parts.keys()].sort(),expected.sort());const before=[...m.parts.values()].map(g=>g.position.toArray());m.setExplode(1);assert.notDeepEqual([...m.parts.values()].map(g=>g.position.toArray()),before);m.setExplode(0);assert.deepEqual([...m.parts.values()].map(g=>g.position.toArray()),before);let meshes=0;m.root.traverse(o=>{if(o.isMesh){meshes++;assert.ok(o.geometry.attributes.position.count>0)}});assert.ok(meshes>20);a.disposeScene(m.root)}})
test('GLB exports have valid binary headers and embedded mesh data',()=>{for(const k of a.platformKinds){const b=readFileSync(new URL(`../public/scene-assets/${k}.glb`,import.meta.url));assert.equal(b.toString('ascii',0,4),'glTF');assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);assert.ok(b.length>50000)}})
test('bounded telemetry and replay positions are deterministic without mutating devices',()=>{const ds=a.seedPlatformDevices(),before=JSON.stringify(ds);for(const d of ds){const k=a.platformFor(d);assert.deepEqual(a.platformPosition(k,36),a.platformPosition(k,36));for(const f of [-10,0,60,120,1000]){const t=a.platformTelemetry(k,f,d);assert.ok(t.battery>=0&&t.battery<=100);assert.ok(t.progress>=0&&t.progress<=100);assert.ok(a.platformPosition(k,f).every(Number.isFinite))}assert.equal(a.platformTelemetry(k,36,{...d,status:'离线'}).online,false)}assert.equal(JSON.stringify(ds),before);assert.equal(a.sceneTime(0),'09:00:00');assert.equal(a.sceneTime(120),'10:00:00')})
test('public terrain and historic imagery are packaged for offline demonstration',()=>{const dem=JSON.parse(readFileSync(new URL('../public/scene-assets/baiyun-dem.json',import.meta.url),'utf8'));assert.equal(dem.heights.length,dem.width*dem.height);assert.ok(dem.heights.every(Number.isFinite));assert.ok(Math.max(...dem.heights)-Math.min(...dem.heights)>100);assert.ok(dem.source.includes('USGS'));for(const name of ['baiyun-ebo.jpg','mine-before.jpg','mine-after.jpg']){const b=readFileSync(new URL(`../public/scene-assets/${name}`,import.meta.url));assert.equal(b.readUInt16BE(0),0xffd8)}})
test('new devices use domain-specific packet metrics rather than displacement for everything',()=>{const p=a.packetData(a.seedPlatformDevices(),36,1);assert.deepEqual(p.map(p=>p.metric),['观测任务进度','离地高度','巡检速度','关联探头幅值']);assert.deepEqual(p.map(p=>p.unit),['%','m','m/s','mV']);for(const d of a.seedPlatformDevices())assert.equal(a.packetData([{...d,status:'离线'}],36,1)[0].status,'中断')})
test('offline moving devices freeze at the actual last observed demo frame',()=>{const d={...a.seedPlatformDevices()[1],status:'离线',lastSeenFrame:36};assert.equal(a.observationFrame(d,90),36);assert.deepEqual(a.platformTelemetry('drone',36,d),a.platformTelemetry('drone',90,d));assert.equal(a.observationFrame({...d,status:'在线'},90),90)})
