// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveExport(arg1:string,arg2:string):Promise<string>;

export function SaveSolution(arg1:string,arg2:string):Promise<string>;
