// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveExport(arg1, arg2) {
  return window['go']['main']['App']['SaveExport'](arg1, arg2);
}

export function SaveSolution(arg1, arg2) {
  return window['go']['main']['App']['SaveSolution'](arg1, arg2);
}
